### ISSUE TITLE
Bug with messaging between uTox and qTox

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#1001]
I'm using uTox 0.2.p, my colleague qTox 1.0. Systems are Win 8.1 x64 and Win 7 x64 respectively.

Since start chat every incoming message, which my colleague send, shows in my chat many times.
And all messages keep going come every 20 seconds over and over again.

Bug in qTox issues (https://github.com/tux3/qTox/issues/1556).

**Comment by GrayHatter** [comment]
This is a qtox issue, also make sure you've both already updated your clients, sounds like your friend hasn't.

**Comment by zetok** [comment]
@GrayHatter qTox 1.0 is on new api, and it indeed looks like problem with qTox's message DB..

**Comment by GrayHatter** [comment]
Closed as qTox issue, tag me or reopen if you can provide any information to make me think differently
