### ISSUE TITLE
"Close to tray" doesn't work in Linux

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#1002]
under i3wm after closing µTox window, it just exits, instead of minimizing to tray when ``Close To Tray`` is set to ``Yes``

**Comment by irungentoo** [comment]
https://github.com/notsecure/uTox/commit/2a85c62b451bfc0e88f02dd265dc38463a306802

**Comment by Ansa89** [comment]
Tested under XFCE, I get the "Closing to tray." message, utox doesn't exit, but there is no tray icon to click to reopen utox.

**Comment by theCoolkal** [comment]
@Ansa89 The tray icon on X11 is currently a blank square.
It's going to have an icon soon.

**Comment by Ansa89** [comment]
But I can't see any "blank space" in my traybar...By the way I will wait for a proper icon to be added.
