### ISSUE TITLE
uTox sending corrupted messages and initiating false file transfers (ver 1.0-768)

### ISSUE THREAD

**Issue by shalnoff** [notsecure/uTox#1003]
I just update uTox to the new version 1.0-768 (updated form around 1 month old version). 
The application 
a) corrupting messages (cutting it and adding extra pseudo-symbols) 
b) trying sending files rigth after start and sometimes when I send mesage to anyone. Files has random unreadable names as well.

**Comment by LittleVulpix** [comment]
@shalnoff This is caused due to the incompatibility of old api (which your friends have) and new api (which you have now since you updated). Tell your friends to update, there is no other solution.

**Comment by GrayHatter** [comment]
@LittleVulpix is correct, you can reopen this after your friend updates, if you still need to!
