### ISSUE TITLE
imposible to switch typing notification off for another party

### ISSUE THREAD

**Issue by shalnoff** [notsecure/uTox#1004]
can't find how to make my typing notification ivisible for interlocutor. would be great to have ability to switch this feature on/off.

**Comment by GrayHatter** [comment]
Do you want to stop getting typing notifications? or do you want to stop sending them?

**Comment by fcore117** [comment]
i would too like option to turn off sending typing notification to others.

**Comment by shalnoff** [comment]
> Do you want to stop getting typing notifications? or do you want to stop sending them?
sending

**Comment by tsudoko** [comment]
fixed by #1033?
