### ISSUE TITLE
permanent quick online/offile switching (blinking)

### ISSUE THREAD

**Issue by shalnoff** [notsecure/uTox#1015]
I have installed last version form repository on two neighbour PCs (same subnet). Each see other online and successfully exchanging messages for several minutes. Then they both start quickly and periodically switching online/offline statement. It's looks like quick blinking.

(Linux Mint ver. 1.0-781)

**Comment by tsudoko** [comment]
One of my contacts behaves like that, only one though.

**Comment by irungentoo** [comment]
If you disable ipv6 on one of the clients does it still happen?

**Comment by shalnoff** [comment]
> If you disable ipv6 on one of the clients does it still happen?
It looks like it helps! (I have switched IPv6 off just on one side, as you reccomend)

**Comment by GrayHatter** [comment]
@irungentoo do you know why it does that?

**Comment by irungentoo** [comment]
@GrayHatter core issue which I think I fixed
