### ISSUE TITLE
Improvement of the screenshot tool

### ISSUE THREAD

**Issue by azlux** [notsecure/uTox#1021]
I've try the new qTox and I think it's a good feature to give the possibility to cancel a screenshot and to resize it. And because we need the mouse to making the screenshot , i propose to implement a button to validate the screenshot in additional to press "enter" button.

**Comment by tsudoko** [comment]
I don't like that "enter" part.

**Comment by fcore117** [comment]
perhaps simpler way would be cancel screenshot when clicking on single dot and even when size is some pixels so there is nothing to see.

**Comment by tsudoko** [comment]
1x1 should be good, but being able to press esc to cancel would be fine too.

**Comment by matti-san** [comment]
There really should be a choice between a full screen and a selected area. What happens when someone with dual screens sends a screenshot to someone with a single screen - the double wide screenshot detail is too small to even read.
