### ISSUE TITLE
µTox shows no window on Debian Jessie

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#1025]
uTox 1.0-809 (and a few builds before too).
On Debian Jessie it starts, but no window is shown, so it has to be terminated. Nothing special in the terminal output. The last working version is uTox 0.2.p.

The problem is not associated in any way with the Debian version (uTox 0.2.p works fine, except for the avatars of course) .

**Comment by tsudoko** [comment]
Does it still happen if you remove/copy the `utox_save` file?

**Comment by ElLamparto** [comment]
I did not try to remove utox_save.
1.0-809 is shown by Synaptic. The client comes always from the Tox repo.

**Comment by theCoolkal** [comment]
Maybe the Start in Tray setting has been enabled since it was added to the utox_save file in a block of data which was previously undefined.  Try clicking the µTox tray icon, which is currently a blank white square.

**Comment by GrayHatter** [comment]
there is a fix that would check for this in #1027 pull that branch and launch with `./utox --set=show-window`

**Comment by ElLamparto** [comment]
1. Deleting utox_save fixes the problem,
2. There is no tray icon (xfce)

**Comment by GrayHatter** [comment]
@ElLamparto you didn't happen to save your utox_save file did you? I've very much like to take a look at it.

Also are you using a separate tray/window manager/dock/taskbar with xfce?

**Comment by ElLamparto** [comment]
@GrayHatter, probably @theCoolkal was right ("Maybe the Start in Tray setting has been enabled").
Unfortunately I've deleted utox_save backup.

I have a pretty standard Xfce on Wheezy and Jessy. Applications have no problem in showing tray icons. µTox shows no icon. Is there any way I could help ?
