### ISSUE TITLE
"Show me as away when inactive for ... minutes"

### ISSUE THREAD

**Issue by xur86x** [notsecure/uTox#1026]
Skype has this feature and it's pretty convenient, if you want friends to know that you are currently not using your computer and therefore can't answer.

**Comment by tsudoko** [comment]
dup of #604 
I tried to implement that some time ago, but I wasn't sure where to get idle time from.

**Comment by xur86x** [comment]
Did you look at LapFox's result and how they did it?

**Comment by GrayHatter** [comment]
dup, please use #604
