### ISSUE TITLE
message bugs

### ISSUE THREAD

**Issue by linuxes** [notsecure/uTox#1028]
When I'm texting to another utox client, a man on the other side gets an offer to 4GB file(which i didnt offered him, and even it cant be accepted) and sometimes, my message derrives shorted of two starting chars.
http://mineland.eu/upload/uxes/win.png
And then when i obtain an message, it starts with some unexpected chars.Then, its impossible to send printscreens.
http://mineland.eu/upload/uxes/lin.png
And yes, as you can see a man on other side has no nickname and has no possibility to change it even after reinstall(windows version0.2.0).

Os: archlinux, 
version: aur utox-git, 
installed: 12.05.2015
utox --version
0.2.r

Sorry for my english.

**Comment by KapitanGertruda** [comment]
I have the same problem on Ubuntu 14.04. Weird characters keep appearing before the message and sometimes the user sends (he doesn't, but it appears for me) a large file, that I cannot accept. This happens also, when I am on qTox, the other user is on uTox - the characters still appear.

**Comment by GrayHatter** [comment]
someone somewhere's client is out of date. upgrade your toxcore and utox and qtox to the newest version.
