### ISSUE TITLE
Echo on the voice chat

### ISSUE THREAD

**Issue by dogstarxxx** [notsecure/uTox#1035]
It's impossible to voice chat without headset. I got echo. With headset I hear myself. On Skype all is fine with the same machines.
On two machines installeted last night build. Thanks

**Comment by irungentoo** [comment]
Did you try the updater build or the jenkins build?

**Comment by dogstarxxx** [comment]
I dowloaded build from utox.com, then I "google" about the echo problem and found "jenkins" page with 17 may build. I tied it, but result was the same.

**Comment by ElLamparto** [comment]
@dogstarxxx, of course the echo cancellation is very important. However with a few simple rules, you can have excellent audio chat without headphones.

1. Speakers far from microphone,
2. Limited volume on both sides,
3. Cut low frequencies.

**Comment by dogstarxxx** [comment]
@ElLamparto @irungentoo 
I (and partner) are using notebooks with fixed microphone/speakers by manufacture. 
As I'm already said: We does not have echo problem on the same hardware with Skype.

I'm 100% sure that it's software problem.Tox need some advanced echo reduction algoritms to clean received sound stream from recorded microphone stream.

Maybe need to record "what user last said" and compare that with "listen stream". Then cut "what user said" from listen stream if found. 

Maybe there are some more advanced algos&technique already done by somebody. I don't know, but I think really need to do something with this.

ps. Sorry for my English. Hope you understand what I wrote and thans for answers.

**Comment by irungentoo** [comment]
uTox should have working echo cancellation. What OS are you on?

**Comment by dogstarxxx** [comment]
@irungentoo we are all at Windows. Also I have low speed uplink(out) internet connection and seems it's give us delay that effect the echo. But as already said Skype work perfect.
Today I test uTox with my other friend and can confirm that problem exists without headset.

**Comment by ElLamparto** [comment]
@irungentoo, is echo cancellation always active, or only when the audio filer is on ?

**Comment by irungentoo** [comment]
only when the audio filter is on.

**Comment by lunixgeek** [comment]
echo suppression is a must.  I am signing up here so that I can be alerted to test any version offering a solution.

**Comment by ElLamparto** [comment]
irungentoo: In my opinion, the echo cancellation must be independent on the audio filter.
Personally I am never in a noisy environment, so I never use the audio filter, since it degrades considerably the audio quality.

Still, if the codec allows it, the echo should be supressed without other sound processing.

**Comment by matti-san** [comment]
I second lunixgeek and ElLamparto. 

Also elsewhere in utox issues, the workaround for unknown line quality was offered as "turn off audio filter" ending in a conflict of fixes and problems. Separate echo suppression from other sound processing.

**Comment by Garve** [comment]
Echo cancellation does not work for me. 
I am using uTox 0.3.4 Alpha on Fedora 22, my partner uses uTox 0.3.4 Alpha on Windows 8.
Also Skype has working echo cancellation with the same hardware setup between me and my partner. 

Looking forward to when this would work, because other than that Tox is perfect and I would love to kick out Skype! Thanks for this program.

**Comment by zen2** [comment]
I got the echo and it's not a problem of echo cancellation since we are both using headsets and I hear my own voice when my contact hear me. If my contact raise the master volume on his side, I hear myself louder !!!
