### ISSUE TITLE
Timed history clear

### ISSUE THREAD

**Issue by fcore117** [notsecure/uTox#1037]
Clear messages after X time would be very useful for those that do not use remember history but keep uTox running in places where closing is not needed but auto clear would be good.

**Comment by GrayHatter** [comment]
@fcore117 can you describe a usage case?

**Comment by fcore117** [comment]
Automatic history clear from chat window after predefined time, just like manual clear. Maybe this way that if someone disables logging then option appears(gray when history is enabled) to clear running session history automatically, eliminates need for closing.

Second way would be if text is read by person then even changing chat window or minimizing would clear previous chat.

I dont know exactly what is best by developers point of view but anything would be useful in future for public pc-s or semi public pc-s like family pc. Please discuss this with all developers and find best way.

**Comment by GrayHatter** [comment]
sounds like an interesting idea, a "security mode" where utox aggressively tries to not hold any data. Sounds like a data loss nightmare, any ideas on how to make sure utox doesn't remove data the user wants to keep?

**Comment by Serverkill** [comment]
For starters I think it would be good if it could automatically delete messages older than like five minutes or whatever. So you don't have to worry that someone who is physically there can read your chat messages when you leave your computer.
Well, atleast that what I think could be useful.
