### ISSUE TITLE
Please add Tox ID requirements to website

### ISSUE THREAD

**Issue by dbb** [notsecure/uTox#1038]
I tried registering a few of my preferred usernames on http://register.utox.org/ and got an insufficient length error each time. It would be nice if the page clearly stated what the required length is, as well as any other requirements and restrictions, so that users don't have to continually enter arbitrary attempts hoping to get a valid one.

**Comment by irungentoo** [comment]
Your Tox ID is given to you by your Tox client.

**Comment by dbb** [comment]
Well, that explains that. Still wish it would have been described on the site. There doesn't appear to be any documentation at all.
