### ISSUE TITLE
Usability issue: pick up and hang up button

### ISSUE THREAD

**Issue by dogstarxxx** [notsecure/uTox#1039]
I noticed an unpleasant usability issue that affected me and my friends with pick up/hang button. 
When somebody calling: you as a regular user tryng to pick up the phone and click on the button, then you feel that connection not estabilished and click again on the same place after 0.1-0.5 seconds. You get dissconected. ;) See log: 
- Phone call started 0:16
- Phone call canceled 0:16 (at the same time)

On the skype the same issue resolved by changing the place of the hang out button after your clicked pick up button. It's good.
Other another solution to the problem is to make 2 fixed buttons for there actions.

**Comment by GrayHatter** [comment]
done by @Encrypt
