### ISSUE TITLE
voice quality is worse than in skype

### ISSUE THREAD

**Issue by thigg** [notsecure/uTox#1040]
We wanted to switch to uTox but the voice quality is worse than in skype.

It sounds not as "smooth" as with skype.

Would be nice if this could be improved.

**Comment by GrayHatter** [comment]
where'd you get your uTox version?

**Comment by ElLamparto** [comment]
µTox voice quality is excellent, better than Skype. However Skype handles better poor Internet connection - only in that case, Skype voice quality is superior to µTox (my experience).

**Comment by thigg** [comment]
Got it from utox.org. And I guess it is because of a poor connection.

**Comment by ElLamparto** [comment]
Nope

**Comment by jf99** [comment]
If voice quality is bad, you should check your internet connection. It is likely that Tox fails to connect to your friend directly. In such a case the traffic is redirected over another node, which might not have enough capacity. Forwarding ports 33445 in your (and your friends) router might fix this problem.

**Comment by thigg** [comment]
How to check this?

Am 23. Mai 2015 16:42:52 MESZ, schrieb jf99 <notifications@github.com>:
>If voice quality is bad, you should check your internet connection. It
>is likely that Tox fails to connect to your friend directly. In such a
>case the traffic is redirected over another node, which might not have
>enough capacity. Forwarding ports 33445 in your (and your friends)
>router might fix this problem.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/notsecure/uTox/issues/1040#issuecomment-104904078

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jf99** [comment]
Unfortunately, uTox doesn't provide such information afaik. So you need to use other tools to analyse your traffic. Windows has resmon.exe for example, with which you can sort connections by data throughput. When calling your friend, you should see that most traffic goes from your computer to your friend's ip. Another useful program might be wireshark.

A simpler method would be to just setup the port forwarding in router and see if this solves the problem.

**Comment by irungentoo** [comment]
try disabling audio filtering.

**Comment by ElLamparto** [comment]
@jf99, "Forwarding ports 33445 in your (and your friends) router might fix this problem"
TCP, UDP or both ??

**Comment by fcore117** [comment]
i have good audio on desktop where i can open(forward) ports but is bad too on laptop mobile internet and ports cannot be forwarded because of permanent port block by isp. Lot of companies block ports here and some require lot of money to open ports and others refuse to open altogether.

thigg: do you isp allow opening ports and can you open ports in your router or whatever place you get internet?

**Comment by jf99** [comment]
@ElLamparto I don't know. Personally I have forwarded both UDP and TCP, but i guess you just have to try it out.

**Comment by GrayHatter** [comment]
stale, and I think outdated try with the new ToxAV and open https://github.com/GrayHatter/uTox/issues if needed
