### ISSUE TITLE
Compilation Failure from https://wiki.tox.im/UTox: ➜  uTox git:(master) gcc -o uTox *.c -lX11 -lXft -lXrender -ltoxcore -ltoxav -ltoxdns -lopenal -pthread -lresolv -ldl -lm -lfontconfig -lv4lconvert -lvpx -I/usr/include/freetype2 -DV4L In file included from avatar.c:1:0: main.h:20:21: fatal error: tox/tox.h: No such file or directory  #include <tox/tox.h>                      ^ compilation terminated.

### ISSUE THREAD

**Issue by v6** [notsecure/uTox#1042]
Hi! I followed the instructions from https://wiki.tox.im/UTox to the letter, to no avail. 

    ➜  proj git clone https://github.com/notsecure/uTox.git
    ➜  proj cd uTox
    ➜  uTox git:(master) gcc -o uTox *.c -lX11 -lXft -lXrender -ltoxcore -ltoxav -ltoxdns -lopenal -pthread -lresolv -ldl -lm -lfontconfig -lv4lconvert -lvpx -I/usr/include/freetype2 -DV4L
    In file included from avatar.c:1:0:
    main.h:20:21: fatal error: tox/tox.h: No such file or directory
     #include <tox/tox.h>
                         ^
    compilation terminated.

...

    ➜  uTox git:(master) uname -a   
    Linux yeOldeHosteName 3.16.0-38-generic #52-Ubuntu SMP Thu May 7 10:51:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I get error spam of the same variety, turtles all the way down. 

Should the compilation instructions be updated? Am I doing it wrong?

**Comment by GrayHatter** [comment]
install toxcore

**Comment by v6** [comment]
// , 

How, exactly, does one install toxcore? 

Does the package just need to be installed? Should its files be in the same directory?

**Comment by GrayHatter** [comment]
4.1 Apt/Aptitude (Debian, Ubuntu, Mint, etc.)
4.1.1 Notice: we recently revoked our keys and remade our repo
4.1.1.1 Please re-add it if you used it before.
Tox currently maintains Apt and Yum-compatible repos for our Linux clients.
Keep in mind that while we're currently working on packages for all of them, uTox, Toxic, qTox, ratox and tox-bootstrapd (the daemon for running a bootstrap node) are currently listed.
Use this shell script:
#remove old key
sudo apt-key del 0C2E03A0
 
sudo sh -c 'echo "deb https://repo.tox.im/ nightly main" > /etc/apt/sources.list.d/tox.list'
wget -qO - https://repo.tox.im/pubkey.gpg | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update -qq
echo "Tox Repository Installed."
echo "You can now install utox, qtox, toxic, ratox and tox-bootstrapd"

**Comment by v6** [comment]
// , Does this solve the issues with compiling from source?

**Comment by GrayHatter** [comment]
the problem you're having is that toxcore isn't installed on your system. If you install toxcore and then try to run the command `make` in your git directory. It should compile...

**Comment by v6** [comment]
Ah. Is that what the repository instructions were for? 

Can I just install toxcore from the repository, or do I need to build toxcore from source, as described in the following: 
https://github.com/irungentoo/toxcore/blob/master/INSTALL.md#most-unix-like-oses

I tried the instructions mentioned earlier for installing the repository for Ubuntu, and this did not allow me to install `toxcore`: 
    ➜  ~   sudo apt-key del 0C2E03A0
    [sudo] password for nathan:
    OK
    ➜  ~  sudo sh -c 'echo "deb https://repo.tox.im/ nightly main" > /etc/apt/sources.list.d/tox.list'
    ➜  ~   wget -qO - https://repo.tox.im/pubkey.gpg | sudo apt-key add -
    OK
    ➜  ~   sudo apt-get install apt-transport-https
    Reading package lists... Done
    Building dependency tree   
    Reading state information... Done
    apt-transport-https is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    ➜  ~   sudo apt-get update -qq
    W: GPG error: http://repos.codelite.org utopic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6856E1DB1AC82609
    W: Failed to fetch http://repos.codelite.org/wx3.0.2/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

    W: Failed to fetch http://repos.codelite.org/wx3.0.2/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

    E: Some index files failed to download. They have been ignored, or old ones used instead.
    ➜  ~  sudo apt-get install toxcore
    Reading package lists... Done
    Building dependency tree   
    Reading state information... Done
    E: Unable to locate package toxcore
    ➜  ~

https://github.com/irungentoo/toxcore/blob/master/INSTALL.md#most-unix-like-oses

P.S. How do I re-open the issue?

**Comment by GrayHatter** [comment]
this is not a utox issue, it's a support request. 

You can get live help in #tox on irc.freenode.net or you can wait for @stqism to explain how to add the tox repos to your ubuntu

**Comment by v6** [comment]
// , 

If toxcore is a build dependency, why isn't it listed in https://wiki.tox.im/UTox? 

The tox repos don't have toxcore as a package, and the documentation does not see fit to mention that it is a prerequisite to even attempt to build uTox from source. 

If I hadn't tried the channel already, I wouldn't have opened this issue, Hatter. 

It looks like the procedure is to first build AND install `toxcore` from source, manually ensure, by means according to the OS involved, that it is added to the system path, and *then* attempt to build uTox from source, right?

**Comment by v6** [comment]
// , I can figure out a pull request, or something. My week's free, man.

**Comment by GrayHatter** [comment]
@v6 I'm ideling in that channel, highlight me and Ill get your build enviroment working
