### ISSUE TITLE
Clean up old firewall rules

### ISSUE THREAD

**Issue by LittleVulpix** [notsecure/uTox#1043]
Not sure if this is a problem on Linux, but on windows, since each utox binary has the version name embedded in it, you will end up with tons of old redundant firewall rules.

Is it possible to remove these programmatically? Since someone could be using multiple versions at the same time, it should be possible to check whether the target binary exists, and if not, remove the firewall rule for utox.

Sample of the current state of utox firewall rules of someone who's been using it for a long time:

![Firewall](http://i.imgur.com/y3qX7GX.png)

**Comment by tsudoko** [comment]
Thought the new updater fixed it by using a single binary name.

**Comment by LittleVulpix** [comment]
@tsudoko "new updater" ? I updated today and it still gets the binary as win64-0.3.0. Is the new updater in the works, or something I have to get separately? : o

**Comment by tsudoko** [comment]
I think it's been out for a while.
https://github.com/notsecure/utox-update/releases/download/latest/utox_runner.zip

**Comment by LittleVulpix** [comment]
@tsudoko Oh, you are right! Would it be possible for the utox_updater to update itself? Or at least tell the user to do so? I've been using the older updater probably, but I had no idea it had been updated.

Additionally, since utox is now called utox.exe regardless of the version, would it be possible to remove those old entries programmatically, or is that not feasible?

**Comment by GrayHatter** [comment]
@LittleVulpix it's a compile time option, you can compile that feature in yourself. Or wait until the settings page is fixed and it'll be an option added in there

**Comment by LittleVulpix** [comment]
@GrayHatter I'll wait for the page; after all, I am able to get rid of those entries myself; it's more for people who don't want to fiddle about with their firewall settings. Should I leave this issue open?

**Comment by GrayHatter** [comment]
yeah, until someone makes a decision on what we're going to do with this, it should stay open. Either way theres' a few people who have all these rules. And it also lets us know how many want to see an updater rolled into the utox bin

**Comment by matti-san** [comment]
Yes, please roll updater into the utox bin.
