### ISSUE TITLE
Change and manage nospam

### ISSUE THREAD

**Issue by fcore117** [notsecure/uTox#1044]
Please add nospam manual and random changing and managing of multiple spam id-s so i can create list where my contacts comes and remove what is not needed.

**Comment by GrayHatter** [comment]
Needs toxcore support that doesn't exist yet

**Comment by fcore117** [comment]
i meant as of currently at least something like qTox has

**Comment by GrayHatter** [comment]
old repo, please open https://github.com/GrayHatter/uTox/issues if you need to change nospam
