### ISSUE TITLE
Not starting after fresh install - utox_save not found

### ISSUE THREAD

**Issue by kehugter** [notsecure/uTox#1048]
After a fresh install following this instructions for Apt https://wiki.tox.im/Binaries#Linux, uTox crashes at start with this output

    File not found (/home/asdf/.config/tox/utox_save)
    File not found (utox_save)
    File not found (utox_save)
    0
    have GTK
    new tox object ipv6: 1 udp: 1 proxy: 0  0
    trying without proxy, err 9
    trying without ipv6, err 9
    tox_new() failed 9

Same result using the latest binary from here https://jenkins.libtoxcore.so/view/Clients/job/uTox_Linux_pkg/

I have qTox installed, which also uses ~/.config/tox. Removing that directory and reinstalling uTox didn't work. An empty utox_save file neither.

---

Linux Mint Cinnamon 17.1 64bit

**Comment by irungentoo** [comment]
Should be fixed now.

**Comment by kehugter** [comment]
Indeed, thanks!
