### ISSUE TITLE
Version 0.3.0 does not start on XP 32bit. Previous versions work ok

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#1051]
![toxstart](https://cloud.githubusercontent.com/assets/9163437/7835293/02669292-0478-11e5-9926-7a0940d93190.PNG)

**Comment by irungentoo** [comment]
Where did you get the binary?

**Comment by ElLamparto** [comment]
From https://wiki.tox.im/Binaries, Other Builds, µTox 32bit

**Comment by LittleVulpix** [comment]
@ElLamparto https://github.com/notsecure/uTox/pull/1029 ?

**Comment by ElLamparto** [comment]
It seems that the problem is solved in version 0.3.2.
