### ISSUE TITLE
won't remember several settings

### ISSUE THREAD

**Issue by mmirco** [notsecure/uTox#1052]
In uTox v0.3.0 running in Windows 7,
the client is not remembering following settings after closing and restarting.

- close to tray
- start into tray
- style (jumps back to default)

- launch with system startup (it does start, but the the box says 'no')

Best Wishes

P.S.: Sorry for maybe not using the original wording for the functions, but it installed with my locale and there is no option for changing the language within the client.

**Comment by mmirco** [comment]
You what's really scary - ALL of the reported issues where gone right after posting it here...

**Comment by mmirco** [comment]
You know what's scary - all (but the style) issues where gone after posting this here...

**Comment by LittleVulpix** [comment]
@mmirco I just had the exact same thing happen to me. Got latest utox, set it all up and then (while tox was running) I set PC to reboot. After reboot, tox did come up - but all of the other options were forgotten.

**Comment by mmirco** [comment]
@LittleVulpix I can't remember for sure if I did a reboot or not. But I'll try with deinstall make clean reinstall and see what happens, now paying better attention.

**Comment by mmirco** [comment]
Everything is fine by now. Deinstalled, cleaned leftovers and registry and reinstalled. Settings are remembered after reboot with uTox running or closing and restarting. Only the style jumps back to default.
