### ISSUE TITLE
uTox closed unexpectedly

### ISSUE THREAD

**Issue by matti-san** [notsecure/uTox#1056]
"uTox assert failure:***Error in 'uTox':double free or corruption(out): 0x00007f999c000af0***"
Ubuntu 15.04 (vivid) 64-bit
Kernel 3.19.0-18-generic
uTox version - Daily build as of 5/28 update

**Comment by irungentoo** [comment]
what were you doing before it crashed?

**Comment by matti-san** [comment]
Second instance of the same crash with different uTox daily build  1.0.899 and at different address:
"0x00007f4998000af0"
This occurred during the night while the machine was idle with two applications open, uTox and Google Hangouts.
