### ISSUE TITLE
get Tox-ID back

### ISSUE THREAD

**Issue by mmirco** [notsecure/uTox#1059]
I registered the ID with a username on http://register.utox.org/. After reinstalling uTox I, of course, got a new ID. How can I get the old ID back so I can use it again with the registered username?
(uTox v0.3.0, Win7)

**Comment by tsudoko** [comment]
You can't.

**Comment by mmirco** [comment]
Is that a missing feature or on purpose?

**Comment by tsudoko** [comment]
It's on purpose. I don't think reinstallation should delete your ID, though.

**Comment by mmirco** [comment]
I cleaned all leftovers and removed anything related from the registry (Windows). I think, that's why it is gone. But that also means, I can't use the same Tox-ID on different sysems, dosn't it?

**Comment by tsudoko** [comment]
Yes, that's right, for now. Multi-device support is planned.
Your ID is the `%APPDATA%\tox\tox_save.tox` file.

**Comment by mmirco** [comment]
Great!! Thanks for the support :-) !

**Comment by linux-modder** [comment]
I personally  do a cp -r ~/.config/tox/*  /%{USB,ExternalHDD}storage  anytime I add/remove a contact and weekly  otherwise  for that very reason (including the saveQrCode)

**Comment by GrayHatter** [comment]
I haven't heard of µTox destroying any data in over 100 commits, that should be unnecessary. Backups are a good thing, but before and after contacts is overkill

**Comment by linux-modder** [comment]
Multi devices hence why


2 laptops and a android
