### ISSUE TITLE
Pending transfers to offline friends can't be cancelled

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#1063]
Steps to reproduce:

1. Start a transfer
2. Wait for the friend to come offline

**Comment by GrayHatter** [comment]
@tsudoko what's the error message from the debug output?

**Comment by tsudoko** [comment]
I don't think there was any, but I'll check it when I get home

**Comment by tsudoko** [comment]
Widget text: "File transfer broken"
After clicking the 'x' button:
```
FileTransfer:   Toxcore doesn't like us! (6 & 0)
FileTransfer:   Unable to send command, Friend (0) offline!
```
Another friend:
```
FileTransfer:   Toxcore doesn't like us! (26 & 0)
FileTransfer:   Unable to send command, Friend (0) offline!
```
FT widget gets duplicated after the friend comes online, clicking 'x' on the original one will cancel the new one.
The transfer works like expected when the receiver accepts it after coming back online.

GrayHatter/uTox@2919226fd219751a456450be744dadc885edd99

**Comment by GrayHatter** [comment]
would you rather it auto switch to a paused state?

I'm not sure how I feel about that UX for the receiver

thoughts?

**Comment by tsudoko** [comment]
Two things I don't like about the current way:
 - when a friend goes offline, the transfer gets uncancellable and will be resubmitted after the friend is back online (the second part is fine, I just want to be able to cancel it before that happens)
 - after going back online a separate FT widget is created

**Comment by GrayHatter** [comment]
@tsudoko is this still broken with the new UI? 

if so I need to add this to my repo

**Comment by tsdko** [comment]
Seems to be fine now
