### ISSUE TITLE
DPI 250% — µTox hangs, 100% CPU usage

### ISSUE THREAD

**Issue by 2a03** [notsecure/uTox#1071]
This issue was found while experiencing [Issue 856](https://github.com/notsecure/uTox/issues/856) on Win7 x64 (not by me).  Howewer, that bug was reproduced both on Linux (Gentoo x64) & Win7 x64.

** Steps to reproduce: **
1. Go to Settings, set DPI to 100%.
2. Resize window to absolute minimum, allowed by µTox.
3. Set DPI to 250%.
4. Without moving or resizing window click on any contact in contact list.

** Result: **
µTox window becomes irresponsive, CPU usage goes up to 100%.

** Intended behaviour: **
Resize window to minimum allowed with current DPI when it is changed and/or don't hang after following in steps mentioned above.

**Comment by GrayHatter** [comment]
I've tried to duplicate this, but can't if you can still make this happen would you re-open this at https://github.com/GrayHatter/uTox/issues
