### ISSUE TITLE
Play sound when call ends

### ISSUE THREAD

**Issue by codedust** [notsecure/uTox#1077]
When a call ends due to an error (especially on unreliable internet connections) there is no acoustical feedback of the event. This can be really annoing when an application runs in fullscreen mode and you don't see any notifications.

**Comment by GrayHatter** [comment]
#624

**Comment by tsudoko** [comment]
@GrayHatter there's no "call ended" sound there

**Comment by GrayHatter** [comment]
@tsudoko there is in the zamaudio repo

**Comment by codedust** [comment]
OK. Thanks!
