### ISSUE TITLE
Audio device is kept open even when not in use

### ISSUE THREAD

**Issue by flussence** [notsecure/uTox#1086]
OpenAL has [a thing specifically for this](http://kcat.strangesoft.net/openal-extensions/SOFT_pause_device.txt), as of a few months ago.

**Comment by towlie** [comment]
I think because of this uTox causes CPU usage through audiodg.exe (Windows Audio Service) which normally means a sound is played.

**Comment by GrayHatter** [comment]
should be fixed 

open again here https://github.com/GrayHatter/uTox/issues if not
