### ISSUE TITLE
Tox GUI Defunc

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#1089]
I'm running Archlinux, using the PKGBUILDs provided here: https://github.com/Tox/arch-repo-tox

I just updated my tox and now this happened:
![](https://img.ourl.ca/24-1.png)
(i did the censoring :P)

The GUI is pretty much a whole mess, as if something is terribly broken.

It says version 0.3.2 btw

**Comment by stal888** [comment]
A full source clean and recompile should fix it.

**Comment by Sorunome** [comment]
That fixed it, thanks!

**Comment by GrayHatter** [comment]
awesome is okay i3 is way better... just thought you would like to know...
