### ISSUE TITLE
Move DPI scaling to a start flag, and compile time default.

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#1090]
If you set the DPI too high then there won't be any horizontal scroll bars, so if somebody is having a small screen and tries setting the DPI to 250% there won't be a way to change it back, as the settings are outside of the window then.

**Comment by GrayHatter** [comment]
IIRC dpi doesn't save across restarts, or does it?

Either way, 250% is insanely huge. I'm thinking we should just remove it as an option, and see if anyone complains... 

But what's relevant to the title is, do we need horizontal scrollbars for anything else? Or would fixing the DPI issue be the only need for them?

**Comment by Sorunome** [comment]
Seems to me like only the whole settings case would need them, unless you have like a 300px wide screen.

**Comment by LapFox** [comment]
250% probably scales quite well on 4K monitors approx ~32 inches, best to keep options for users rather than remove them.

I have a 4K 42 inch TV I can test on, I'll check this evening.

**Comment by GrayHatter** [comment]
is this something we even want to make a UI feature? We have good command flag support; perhaps we should make that a launch flag? it would make it MUCH easier to tweak the UI if we do it that way...

**Comment by LapFox** [comment]
Sorry, I forgot to add my follow-up to my above comment.

uTox is near enough impossible to use anything sub-250 at a normal distance from the TV. Monitors will be different, but on my 1440p monitor, 150% is comfortable.

**Comment by LapFox** [comment]
Launch flag seems acceptable to me, since its not very commonly changed. Perhaps a dialogue which allows you to slide up and down the scale percentage when you first open uTox? (So that the feature isn't forgotten). It's normally a one-time thing anyways

**Comment by GrayHatter** [comment]
should be fixed with new DPI settings, if not open at https://github.com/GrayHatter/uTox/issues
