### ISSUE TITLE
  // , uTox tox.db file? 

### ISSUE THREAD

**Issue by v6** [notsecure/uTox#1091]
// , There doesn't seem to be any mention of tox.db in the code. 

I searched, and didn't find anything. 

https://github.com/irungentoo/toxcore/search?q=tox.db&type=Code&utf8=%E2%9C%93

Is there any documentation on the tox database?

**Comment by tsudoko** [comment]
I think it was used by Venom

**Comment by v6** [comment]
// , I'm going to try cracking it open with `sqlite`.

**Comment by v6** [comment]
// , 

    ➜  tox  sudo apt-get install sqlite
             ... 
    ➜  tox  sqlite tox.db              
    Unable to open database "tox.db": file is encrypted or is not a database

**Comment by GrayHatter** [comment]
for anything in the `tox_save.tox` file you'd better ask in the toxcore repo. tox.db as far as I know was never a utox file...

**Comment by v6** [comment]
// , 

Hahaha, thanks, GrayHatter!

tsudoku, I think you're on to something, and it may be specific to Venom. I'll link to the issue I have made here when I open an issue there: https://github.com/naxuroqa/Venom/search?utf8=%E2%9C%93&q=tox.db

P.S. 

By the way, I did finally get the build to work. 
[TeamCity][Ø] time, bitches!  

[Ø]:https://www.jetbrains.com/buy/opensource/?product=teamcity

**Comment by v6** [comment]
// , Just looking up Venom, checking the latest issues, ["Aaaaaaaaaaaand it's gone."][$]


[$]: https://youtu.be/-DT7bX-B1Mg?t=27s
