### ISSUE TITLE
Suggestion: Plugin Capability

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#1097]
Just got an awesome idea: some kind of plugin capabilities so that users can write their own plugins!

So that you can modify with a plugin things like message send or before displaying it to the chat.

**Comment by SkyzohKeyx** [comment]
:+1:

**Comment by SkyzohKeyx** [comment]
@GrayHatter why did u marked it as unpossible ? O.o

**Comment by GrayHatter** [comment]
That's merely a joke label for requests that would take months to get to a
working condition with support from a lot of other parts of the utox code.

Something that would be done when we're more stable, or with a huge code
refactor.

**Comment by GrayHatter** [comment]
not this this should be closed, but I'm trying to clear out issues from this repo, please reopen this at https://github.com/GrayHatter/uTox/issues if you really think µTox needs this
