### ISSUE TITLE
µTox trims outcoming messages in message log

### ISSUE THREAD

**Issue by 2a03** [notsecure/uTox#1098]
** Steps to reproduce: **
0. Make sure that Logging is set to «Yes» in uTox Settings → User Interface
1. Send large amount ot text (>1KiB) to any recipient.
2. Restart µTox or check log files to see that outcoming message haven't been logged in its entirety. Incoming messages aren't trimmed.

** Intended behaviour: **
Save every message exactly as it was send or recieved.

**Comment by GrayHatter** [comment]
how µTox does messages needs to be re-written, would you be so kind as to open this at https://github.com/GrayHatter/uTox/issues
