### ISSUE TITLE
No UI when running uTox

### ISSUE THREAD

**Issue by kozross** [notsecure/uTox#1100]
I am on the AUR build of uTox. Basically, it seems to start OK, but I never see any UI. When I try running in the terminal, it doesn't segfault, and I apparently even get messages, which I cannot reply to.

**Comment by burlito** [comment]
Hi,

Try revert 2a85c62b451bfc0e88f02dd265dc38463a306802 and it should work.

On 07/01/2015 05:23 AM, Koz Ross wrote:
> I am on the AUR build of uTox. Basically, it seems to start OK, but I
> never see any UI. When I try running in the terminal, it doesn't
> segfault, and I apparently even get messages, which I cannot reply to.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notsecure/uTox/issues/1100>.
> 

-- 
Kind regards,
b.

**Comment by GrayHatter** [comment]
@kozross does "--set=show-window" fix the problem?

**Comment by kozross** [comment]
@GrayHatter Yeah, that fixed it. Thanks very much!
