### ISSUE TITLE
uTox does not support Unicode

### ISSUE THREAD

**Issue by J2TeaM** [notsecure/uTox#1103]
I can not use uTox to chat in Vietnamese because it does not support unicode input. Screenshot:

![image](https://cloud.githubusercontent.com/assets/5250117/8744653/f313c956-2ca2-11e5-9ad2-97318018c8ab.png)

**Comment by GrayHatter** [comment]
What OS/Distro are you using?

**Comment by tsudoko** [comment]
Looks like Windows.

**Comment by J2TeaM** [comment]
@GrayHatter : I'm using Windows 7 (x86).

**Comment by Jeeppler** [comment]
@J2TeaM are you sure about the x86? Can you look under control panel -> system how many bit your operating system have?

**Comment by J2TeaM** [comment]
@Jeeppler yeah, I'm sure.

![image](https://cloud.githubusercontent.com/assets/5250117/9561389/b9086d06-4e6d-11e5-9379-3667ceeab15b.png)

**Comment by GrayHatter** [comment]
I'm thinking it's a font issue... if you still have this issue open it here https://github.com/GrayHatter/uTox/issues and reference this issue, should be easy to test
