### ISSUE TITLE
Tray Icon missing on KDE 5

### ISSUE THREAD

**Issue by Ineluki** [notsecure/uTox#1104]
Running Kubuntu 15.04, where "XEmbed-based systemtray [are] not supported anymore"
Since my uTox was set to start in the tray, I now have no way of accessing it.

**Comment by tsudoko** [comment]
Try `utox --set=show-window`.

**Comment by Ineluki** [comment]
Good workaround for the moment, thanks!

**Comment by danbelov** [comment]
I am using Debian 8 Jessie with KDE4 desktop environment, 
and the workaround doesn't work for me.
I'd like to help solving this problem, but i have no idea where to start.
Is it a utox or KDE bug?

**Comment by GrayHatter** [comment]
It's not really a bug, KDE decided to break support for that feature. You're likely on an out dated version if that start flag doesn't work for you

**Comment by ace13** [comment]
KDE are apparently working on a fake X window host that can emulate the systray while retranslating it to appindicators, but if uTox wants to support Wayland in the future then it might be good idea to work on making a tray icon using appindicator.

**Comment by GrayHatter** [comment]
duplacated and maybe solved at https://github.com/GrayHatter/uTox/

**Comment by ananace** [comment]
Hard to say if it's solved or not now though, KDE have released their SNI systray emulator, so the tray icon will show on KDE 5 either way.

**Comment by GrayHatter** [comment]
either way systray is going to be killed, so we should support their new tray as well.
