### ISSUE TITLE
Bug in settings tab headers

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#1106]
In Settings tab headers are intersect each other.

![Screen](http://puu.sh/ja8KT/5322bc92a6.png)

v.0.3.2, Win 7, x64.

**Comment by GrayHatter** [comment]
where'd you get your version?

**Comment by GrayHatter** [comment]
What language is selected?

**Comment by cebe** [comment]
looks like russian

**Comment by redmanmale** [comment]
@GrayHatter 
via autoupdate by tox_runner.

Language is russian, yes.

**Comment by GrayHatter** [comment]
@irungentoo is the runner using the newest master, because this doesn't
exist in develop... And develop didn't change any UI from master

**Comment by redmanmale** [comment]
@GrayHatter 
I downloaded pre-release runner (from [here](https://github.com/notsecure/utox-update/releases/)) and after uTox client update bug is gone because there's no Russian localization at all.

Also dropdown list with languages is cut by strip menu:
![screen] (https://puu.sh/jjfTa/192da03691.png)

**Comment by GrayHatter** [comment]
I'm aware of this particular bug, the language is still there, it's just hidden. If you increase the vertical size it'll show back up....

**Comment by redmanmale** [comment]
Bug appears in Russian and Italian localizations.
![Italian](https://puu.sh/jjY2T/02a4361897.png)
![Russian](https://puu.sh/jjY4b/678fcd6c60.png)

In some languages header text length is more than max width of header.

**Comment by GrayHatter** [comment]
Can and of you build from source? And confirm this is on master?

**Comment by redmanmale** [comment]
Unfortunately on my windows machine I couldn't build it all.
I'll try cross-compile it on linux.

**Comment by redmanmale** [comment]
Another lack in interface settings tab (russian):
![Russian](https://puu.sh/kfu3V/87eb81bb2b.png)

English:
![English](https://puu.sh/kfu6l/14fac0f340.png)

**Comment by GrayHatter** [comment]
Where'd you get your uTox version?

**Comment by redmanmale** [comment]
From [official site](http://utox.org/).

**Comment by GrayHatter** [comment]
fixed in develop
