### ISSUE TITLE
Any updates to uTox binaries?

### ISSUE THREAD

**Issue by Serverkill** [notsecure/uTox#1107]
What has happened, seems like uTox development has stopped !?

It is my favourite client, would be bad to lose it...

**Comment by cebe** [comment]
It has not stopped, most of the work is just on other branches which would break if merged into master right now. https://github.com/notsecure/uTox/tree/develop

**Comment by GrayHatter** [comment]
thanks @cebe

**Comment by Serverkill** [comment]
OK, so there is still hope, thanks for replying.

BTW, best wishes to people participating in this project, secure and open source im/voice chat program is very necessary in today's world! I would gladly help if I only knew more about programming...

**Comment by GrayHatter** [comment]
@Serverkill there's plenty of things you can do even if you know nothing about programming. You could update the pictures on the Github README.md, you could improve the linux man page, you could write better documentation, you could create a changelog file, you could read through the issues, and see if anything is already fixed, comment on something you think is important, or propose a suggestion for another way of solving an already open issue.

**Comment by fcore117** [comment]
One way to contribute is i think for non programmers is to mass promote Tox and uTox and there is more chances that more C developers will arrive. I myself do everything in my power to get more people know Tox.

My personal way is to hunt for news related of security, online encryption, NSA wiretapping, Snowden or anything that has potential to catch more hands to Tox.

Tip: Always warn that Tox is still in heavy development so people can know what to except currently if you post somewhere.

**Comment by GrayHatter** [comment]
if you do that, make sure you're targeting advanced users, an influx of support requests will just leave a bad taste about tox hindering our ablity to attract users who already think we're broken

**Comment by GrayHatter** [comment]
old repo https://github.com/GrayHatter/uTox/issues
