### ISSUE TITLE
Conversation logs are not encrypted ! Why ?

### ISSUE THREAD

**Issue by johnny8** [notsecure/uTox#1112]
All the utox conversations are stored in txt files in appdata/roaming/tox without encryption, Why why why ?? !!  Other people can easily come to my computer and read them !
![capture tox p3](https://cloud.githubusercontent.com/assets/13690553/9130383/d6e463ee-3d14-11e5-938f-c7f931569a61.PNG)

**Comment by cebe** [comment]
well, can't they also come to your comuter and run uTox to see them?

**Comment by linux-modder** [comment]
@OP, there should be an option in advanced  for that  ( there is  in  qtox
 at least)


Sent from my email....

Corey W Sheldon

  "Have no way as way, no limitation as limitation. One must never
underestimate the power of boredom...from which creativity and laziness are
borne, which can spark great works of chaos and genius."

Find Me  on any of the sites  I teach /frequent:
https://gist.github.com/linux-modder/ac5dc6fa211315c633c9
---------------------------------------------------------------------------------------------------
Tox:
corey84@toxme.se
9357BC6A5944A08AFC7D1EFFD61F6A73B9EABF8B2FB84ACF1DAC9A1A4D0A4705FFCCD0E5499B
PGP: 718BF597
<http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597> FP: 2930
99EB 083D D332 0752 88C4 E958 C5D6 718B F597
---------------------------------------------------------------------------------------------------

**Comment by GrayHatter** [comment]
uTox doesn't support file encryption at this point. Windows however does support encrypting user files if you're really that concerned. 

Also dup of #532

**Comment by johnny8** [comment]
Thanks for every reply !
but they actually no need to come to my computer, they just need to hack into my friends' , steal the log files silently, trace who is the leader, and go to cuff him. It is a matter of live or death.
At this moment I can only tell every members to shut down the log function.

**Comment by johnny8** [comment]
One more bug: when I am reading in my friend's box, if I wrongly press the DEL button, my friend will be delete at once, and need to add him again. That need to repair, thanks !

**Comment by johnny8** [comment]
Can you guys see this when the case is closed ? !

**Comment by GrayHatter** [comment]
Even if utox implements save fire encryption. (Pretty much guaranteed)
it'll be optional. So if you contact chooses not to, same problem. Also, if
they're able to hack into his computer they can keylog his password and
same result.
