### ISSUE TITLE
system tray icon is messed up

### ISSUE THREAD

**Issue by stormchaser3000** [notsecure/uTox#1113]
this might be a duplicate. but on MATE. i see this in the system tray for utox: 

<img src=http://u.cubeupload.com/stormchaser3000/Screenshot1.png> (the white line)

**Comment by Jeeppler** [comment]
which linux distro + MATE version do you use?

**Comment by ciechomke** [comment]
Also affects me on Arch Linux + MATE

**Comment by stormchaser3000** [comment]
i as well am on arch linux. but i am using xfce4 for the moment

**Comment by Jeeppler** [comment]
it does not affect Archlinux + gnome-shell!

**Comment by ElLamparto** [comment]
On Debian Jessie + xfce there is no systray icon at all.

**Comment by akhilman** [comment]
#208 is same 
Also having this problem on Debian with MATE

**Comment by GrayHatter** [comment]
@stormchaser3000 @Jeeppler @ciechomke @ElLamparto @akhilman can you test https://github.com/GrayHatter/utox/tree/lintray_bg and fill issues at  https://github.com/GrayHatter/utox/issues

**Comment by vasisualiy** [comment]
please, reopen. SDE (fork of LXDE), waterline (fork of lxpanel) tray icon shows as white square.

**Comment by akhilman** [comment]
i3wm's panel also shows flat square.

**Comment by GrayHatter** [comment]
@vasisualiy @akhilman have you tried the lintray_bg branch?

also No, not going to reopen this. please see https://github.com/GrayHatter/utox/issues
