### ISSUE TITLE
[Usability Feature]  See yourself during video call

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1115]
Starting a video call with another person opens a new window, with the other person in it. This is the basic video call functionality and it works fine, but it is hard to except what about you and how the other person sees you?

The problem about just seeing the other person is: that you don't have any feedback how you look for the other person?
- You don't know if you sit proper and visible for the other person
- You don't know how the light is
- You don't know what the other person actually see about you (e. g. to much of your cleavage)
- You don't know what the other person can see about in your background

This leads to an insecure feeling during video calls.

Skype solves this problem by showing yourself in a separated window (in this case the iPad) at the bottom. 
![skype_interface](https://cloud.githubusercontent.com/assets/2007739/9289980/507de96a-4381-11e5-816b-aa0eb2875a09.jpg)

I would like to see a similar solution. E. g. the solution which I have drawn here:

![see_yourself](https://cloud.githubusercontent.com/assets/2007739/9289932/632e8968-437f-11e5-9c4e-b347cc5b6a54.png)

**Comment by tsudoko** [comment]
You can see yourself by clicking the video icon in the audio/video section in the settings.

**Comment by Jeeppler** [comment]
@tsudoko yes this is a really nice feature and really helpful to test your web cam device and much better implemented than in Skype, but this does not solve the problem of don't having feedback about yourself during the video call!

**Comment by tsudoko** [comment]
Why? You can leave the window open during a video call.

**Comment by Jeeppler** [comment]
@tsudoko this is not user friendly at all? And if I close the preview window, I can not reopen it again during a video call.

**Comment by nachfuellbar** [comment]
@Jeeppler +1
This issue is over a year old
https://github.com/notsecure/uTox/issues/180
