### ISSUE TITLE
What is the NEW download location for uTox ?

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#1116]
Hello,

after quite a long period, I wanted to update my tox client, in order to see what's new and perhaps enjoy some new functionality. I went to the standard location, where I am downloading it from:
jenkins.libtoxcore.so
But the site doesn't open !!!!!!!!!!!!!!!!!!!!!!!!
Kindly advise where the new download locations is...
Thanks a lot in advance!

**Comment by tsudoko** [comment]
http://utox.org/download

**Comment by darkman088** [comment]
Nope, this isn't the real deal... For example, where is uTox for Win x64 there ? Where are the .rpm files... jenkins.libtoxcore.so was FAR better, it had all the platforms...

**Comment by tsudoko** [comment]
The link redirects to the version for your platform based on your browser's user agent.
The new jenkins is at https://build.tox.chat, the new binaries page is at https://wiki.tox.chat/binaries.

**Comment by darkman088** [comment]
For Windows there is utox_runner.zip containing utox_runner.exe. I may have a look at it. But I didn't find even a single .rpm file on the URLs you are citing above...

**Comment by darkman088** [comment]
Thanks a lot, for Windows it should be OK, but no matter how hard I tried, I still wasn't able to find .rpm files (only .deb). Thanks for pointing me the .rpm files...

**Comment by darkman088** [comment]
I would really appreciate it, if someone could provide the right answer!

Thanks!

**Comment by stal888** [comment]
RPM files don't exist currently. There is a statically-linked uTox here https://build.tox.chat/job/uTox_build_linux_x86_64_release/ and the Debian dependencies are `libX11-6, libxext6, libxrender1, libfontconfig1, libfreetype6, libdbus-1-3, libv4l-0, libopenal1`. You could try installing the equivalents for your distro and see if it works...

**Comment by darkman088** [comment]
HOW COME that RPM files don't exist ??? Sorry, but you gotta be kidding !! And today is not the 1st of April !! You couldn't have possibly stopped making rpm files !!
All my experience with software is, that things are ONLY going worse, never better!! Until now, I had the impression, that uTox is almost the only exception! Please don't spoil this impression...

P.S.: Please at least supply the latest rpm available, as I haven't been checking it for quite a while...

**Comment by linux-modder** [comment]
Since the port from the    no longer used tox.im domain not everything has been moved / rebuilt if you so upset and skilled help out by compiling one for the community to help the devs rather than merely bitch.

**Comment by stal888** [comment]
Don't be rude

**Comment by GrayHatter** [comment]
um... it's trivial to compile.... install the dependencies with your choice of package manager. then type `make && make install`

Otherwise, RTFM and build your own package... If you use a real distro there might even be pre-made install ready for you... https://aur.archlinux.org/packages/utox-git/

**Comment by darkman088** [comment]
@GrayHatter - I think you are getting me wrong. It's not about if it's easy or hard to compile it. It's about that BEFORE there were RPM files on Jenkin's website, and now there are NOT !!
it is that something quite important, that was available before, is gone now. It is that users were relying on something and now they are left alone !!!

**Comment by quantumpacket** [comment]
@darkman088 How come you're the only one complaining about the RPM files no longer being provided? Everyone else who thought they were important to them are probably just doing the most logical thing and compiling it themselves, it's not hard at all to do. So my suggestion is to first compile, if you have issues doing so then ask for help. Griping about this with exclamation points!!! and LOUD WORDS will not get the files uploaded. Things like this happen all the time, that is why the source is there for you.

**Comment by GrayHatter** [comment]
Unfortunately, they kinda will.

I'm working on getting a package repo for Debian, Redhat, arch any anything
else that's easy...

**Comment by darkman088** [comment]
Does this mean, that there will be .rpm files soon again ? You gave me HUGE hope with your last post!
Thanks!

**Comment by darkman088** [comment]
@quantumpacket - I have overseen your post and I just became aware about it.
Now, let me ask you a question: what do we all want to achieve here ? Provide a PLATFORM for secure and private communication. The more people use this platform, the better it will be for the platform and the better it will be for the people! We want EVERYBODY - from our 5-6 year old children, to our grandparents to use it! Now go to my father and explain him first what is it to compile a program and what how to do it - I guarantee you to spend 5-6 tough hours and furthermore - he will ask you tomorrow or in a week about 80% of the procedure, as he doesn't recall it anymore.
Then come to people like me - who are THAT busy, that they do not have enough time to sleep and explain them, that they need to not only invest hours and days into first RESEARCHING which is the best program for the above mentioned secure and private communication, but they need to go beyond that and care about compiling a program!
And once again, we all here want Tox to become the habit of most of the population, not only for freaks like us!
I don't want to be rude in any means, but I do not agree !!
If you have a fraction of the will to establish this platform, you will provide 32-bit and 64-bit versions for Windows, Mac, Linux (source code, static binaries, rpm, .deb, etc. etc.), Solaris, Android, iPhone AND Symbian !!! Then people will have no excuse for not using Tox!
This is EXACTLY what the famous agencies are counting on - most of the people will say - why to waste time, why to compile it, it's too difficult and too cumbersome! Let's just use Skype!
And with this approach you are giving bullets to exactly those agencies, interested in mass data gathering and eavesdropping on whole communities/cities/countries/continents/mmm... planets).
I hope you are getting my point now...

**Comment by quantumpacket** [comment]
@darkman088 If the end-users are as IT illiterate as you make them out to be, then most likely they will not even know how to verify the package let alone any source for evidence of tampering. Users should not blindly trust any downloaded packages compiled for them without verifying either the checksum and/or signature, which should come from a trusted key. This is why uTox is signed either at the source level on here, or by package distributors when they make a package *(hopefully they verified the source before doing so, and hopefully they can be trusted)*.

Telling people they will achieve this magical safe and secure messaging system if they install a program without actually verifying the integrity of the compiled program that they downloaded gives the false impression of security as those files could have been tampered with either on the server or in transit. It would be great if this was available for everyone, but we have to be realistic to benefit from this program's security the users themselves need to follow some security practices when downloading and installing, which unfortunately even most IT folk don't even bother to do.

**Comment by darkman088** [comment]
I like your post! I can't agree more with you! Even though I am IT folk as well, I wasn't aware of many of the points you are describing until very recently, also because I am far from software development (otherwise I would be helping you, guys, with the coding!! And I see that you obviously agree with most of what I said. I can only add: let's hope that YOU are right and that end-users are not IT illieterate... But I can only speak about people from my surrounding, people who don't work in IT - the picture is very very grave... Even when I speak to friends of mine, IT people, working lots of overtimes on serious projects - I am advertising for Tox and I am shocked by their attitude !! Well, I don't care that it's not encrypted. Well, I don't discuss any secrets with my contacts on the xyz app. Well, I am not sharing any bank data or other confidential information... They just don't get it how complex the whole thing is !! This is why I am so much with you, guys, and even if may sometimes sound weird, this is only because I have quite some experience with IT and I can look at it from both perspectives - of an advanced user and of a professional and I am trying to help and to push you in the right direction, so that you will be really successful !! Cheers :-)

**Comment by linux-modder** [comment]
As Someone who personally deals with those (of all ages) with mental handicaps and  literacy levels tech and non tech,  It  boils down to the  method of  explanation and  make a  connection that  holds  (even for those with memory disorders).  I would  even go as far in your case @darkman088  as to  compile for your loved one and  work with someone if not thyself to  draft up or  help the team draft a  'community'  How to or  a  Do's and Don'ts much like the  tor-project has done.  And  take baby steps. 
e.g. Take a  common interest and  give a  30k foot  view of the process and 'field' and  as the end-user whomever they be  is comfortable with lowering into the weeds.  Yes it is  a  time commitment but its also something you have to consider if you want an 'informed'  client /  end-user.

**Comment by darkman088** [comment]
A few posts ago I kindly asked if it would be possible to at least obtain the latest RPM file which was made...

**Comment by linux-modder** [comment]
@darkman088:  they are  being worked on. patience  or  help with getting your hands dirty  current  builds for  ALL linux (as a tarball with  ready  binary) are  here:  

https://build.tox.chat/view/Clients/job/qTox_build_linux_x86_release/
https://build.tox.chat/view/Clients/job/qTox_build_linux_x86_64_release/

**Comment by Jeeppler** [comment]
@linux-modder 

https://build.tox.chat/view/Clients/job/qTox_build_linux_x86_64_release/
gives a HTTP 404 error

and your sources are not from uTox

**Comment by Jeeppler** [comment]
@GrayHatter can you also create a package for Chocolatey [Windows](https://chocolatey.org/)?

**Comment by darkman088** [comment]
People, please don't get me wrong - what I really meant was - until some point in time, there were RPM files. I kindly asked for the last one available.
If I managed to move the mountain with this thread and you decided to start providing RPM files again, then I will wait of course, I have no problems currently, I am just interesting in eventually implemented new functionality. Many thanks to all of you for the quick reactions!

**Comment by stal888** [comment]
RPMs will be back as soon as we figure out how to make them

**Comment by stal888** [comment]
@darkman088 https://build.tox.chat/view/packages/job/uTox-rpm_pkg_linux_debian-8_x86-64_nightly_release/2/

It would be helpful if you try installing that and tell me what's wrong

**Comment by GrayHatter** [comment]
@jeppler yes, it's on my todo list
