### ISSUE TITLE
[Usability Enhancement] Simple emoticon support

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1117]
A simple emoticon support, would result in a easier way to express human emotions in the text chat.

The basic emotions are shown in the image below:
![tango_icon](https://cloud.githubusercontent.com/assets/2007739/9290155/6f4a8b9e-4388-11e5-8ffb-67b40165c38f.png)
The above icons are from the [Tango project](http://tango.freedesktop.org/Tango_Icon_Library) and open source. They are available in different file formats (most important: svg).

Because uTox has a really simple user interface, the icons don't have be in 3-D Style it could also look more simplistic like the two examples below:
![simple_icon_filled](https://cloud.githubusercontent.com/assets/2007739/9290120/868067bc-4387-11e5-97ff-d375199d2fa1.png)
![simple_icon](https://cloud.githubusercontent.com/assets/2007739/9290121/86837786-4387-11e5-9162-0ddcd76764b1.png)

**Comment by tsudoko** [comment]
Try using emoji for now.

**Comment by Jeeppler** [comment]
@tsudoko you are right, this is a duplicate of #349 

but how can I use emoji in uTox?

**Comment by stal888** [comment]
If your OS lets you type emoji then uTox will probably support it.

**Comment by Jeeppler** [comment]
How can I type emoji's? What kind of combination do I have to use?

**Comment by Jeeppler** [comment]
I was able to use emoji's in gedit with this tutorial: http://www.johndcook.com/blog/2008/08/18/entering-unicode-characters-in-linux/

But how can I enter emoji's in uTox?
