### ISSUE TITLE
[Feature] Mute/unmute voice

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1118]
It would be a nice feature to be able to mute and unmute the voice during a video call.
The mute/unmute, button should be in the video call window.

**Comment by nachfuellbar** [comment]
This issue is already one year old (ok, 6 days to go xD)
https://github.com/notsecure/uTox/issues/287
Maybe this shouldn't be "High priority" if one year is not enough to resolve

**Comment by Jeeppler** [comment]
@nachfuellbar you are right it is a duplicate of #287
