### ISSUE TITLE
[Usability Enhancement] Resize window - keep the ratio of the video

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1119]
If the user resize the window, the ratio of the video changes according to the width and hight of the window, but does not keep the ratio. 

Small example:
The webcam of my communication partner has the resolution of 4:3. On the beginning the video call window will have the resolution of 4:3, but if I want to maximize the window and my screen has a 16:9 ratio the video call pictures will be skewed.

**Comment by tsudoko** [comment]
This should be optional.

**Comment by Jeeppler** [comment]
@tsudoko it should be you are right, but would be a nice enhancement!

**Comment by nachfuellbar** [comment]
https://github.com/notsecure/uTox/issues/171

One more one year old issue ;)
Maybe add your comments to the original issue
