### ISSUE TITLE
Allow any image format for user avatar

### ISSUE THREAD

**Issue by scrobbleme** [notsecure/uTox#1122]
I'm only allowed to use PNGs as user avatar. Why do not allow JPG... as well?

---------------------

Windows, v 0.3.2

**Comment by LittleVulpix** [comment]
Avatars should simply let you put in _any_ image format, allow you to crop (if necessary) and select what you want, to preview the output.

Internally, it's fine if tox then converts the avatar (after cropping etc) to png. But users shouldn't have to worry about filesize/formats/etc... from usability standpoint. Ever tried explaining file formats to your grandparents? At best, they'll rename the .jpeg image to .png and think it's good now :D

**Comment by GrayHatter** [comment]
uTox needs a micro sized efficient and super light weight library to convert jpg to and from bmp. If you can find an opensource library I'll roll it in.

**Comment by tsudoko** [comment]
https://github.com/nothings/stb/blob/master/stb_image.h ?

**Comment by GrayHatter** [comment]
done
