### ISSUE TITLE
uTox crashes upon pasting into the text box from clipboard when text was copied to the clipboard using xsel

### ISSUE THREAD

**Issue by ConnorDY** [notsecure/uTox#1123]
This happens when right clicking and selecting paste and when using ctrl+v.
This only occurs when the string was copied to the clipboard using xsel.

If a string is copied to the primary selection (with xsel or xclip) then pasted (using middle click), no crash occurs.
If a string is copied to the clipboard using xclip (echo blah | xclip -sel c) then pasted, no crash occurs.
If a string is copied to the primary selection or clipboard using chromium then pasted, no crash occurs.

**Steps to Recreate**
1) Run the command:
```echo blah | xsel -b -i```
2) Attempt to paste into a text box using either ctrl+v or right click->paste
3) Witness crash

**Terminal Output**
```
The program 'utox' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 34151 error_code 5 request_code 17 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by ConnorDY** [comment]
After further research I've updated the description of this issue. I hope the developer will notice it soon so this can be fixed.

**Comment by GrayHatter** [comment]
you're description is amazing, I'm looking into it now.

**Comment by GrayHatter** [comment]
@ConnorDY fixed in https://github.com/grayhatter/utox 9838581379a2b297ccb33b592afa6efeace42e9f
