### ISSUE TITLE
Option - automatically minimize the uTox window during screen sharing

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1124]
Offer an option which allows to automatically minimize the uTox window during screen sharing, to be able to see all other windows or the desktop.

**Comment by cebe** [comment]
duplicate of #715

**Comment by tsudoko** [comment]
Screen sharing != screenshot

**Comment by GrayHatter** [comment]
Either this is a dup, or closing as wontfix. We might offer the option to minimize for a screenshot, but not for screen sharing during a video call.
