### ISSUE TITLE
uTox multichat - improvement recommendations

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#1125]
Dear fellow uTox developers,

I finally had enough time, in order to explore the multichat abilities of uTox.
While on the one side, I am very glad, that this option has been implemented, as it is quite useful and it has been omitted in many other competitor products, on the other side, I would like to make a few comments and recommendations for the future of this function:
1) When a new message has been received in a multichat window, there is absolutely no notification about it. Hence, it's impossible for one to realize that he has got a message, until he intentionally checks if there is something new in the multichat.
2) The concept of adding people is not easy to handle - and again, on the one side, while just dragging users to the multichat contact is easy and intuitive, on the other side, in case of long contact lists, it's somewhere between cumbersome and annoying. Due to the fact, that single contacts are taking quite some screen estate, it is easy to get to a state when one has a scroller in the contacts. Creating a new multichat, puts the multichat window at the bottom of the contacts. Now go ahead and drag a few users from the top of your contact list there... Not an easy task !!
Let's accomplish this the other way around! Let's move the multichat contact upwards in the contact list. While dragging it is fine, dropping it, doesn't insert it between contacts, but it swaps it with the contact it has been dropped onto !! This forces that contact to move from the top of the contact list to its bottom !! Moving that contact again up, forces the next contact to go down. And soon the users finds himself into a loop of fixing the contacts and bringing them to their original location !!!
My constructive proposal: When opening a multichat, a new window containing all the contacts could appear, where with checkboxes, one can select which contacts shall be added to the multichat... This dialog could then be accessible in the right-click context menu of the multichat contact.

Thanks a lot for considering this !!

**Comment by Jeeppler** [comment]
uTox has a search field for users. If you use the search field can you improve the current situation?

**Comment by darkman088** [comment]
Hi Jeeppler and thanks for your reply! I will try this and write the result of my test here! But my other finding, that there is no reaction from uTox, when somebody writes something in a multichat definitely needs some action on developer site, unfortunately, Kindly let me know your opinion on that!

**Comment by Jeeppler** [comment]
@darkman088 you are right this behaviour should be improved. It is nice that you come up  with an idea on how to improve the situation based on a deep analysis. This is a nice work from your side.

The only problem is that uTox has 198 open issues and the developers have to prioritize the issues. If you are not a developer who can fix this issue right now, than you have to wait till the developers will have a look on your issue.

**Comment by darkman088** [comment]
Hi Jeppler,

I agree with you on the first point. Searching among the contacts shows the desired items including the multichat, so this is a very viable solution! I would like to thank you for that! But as you already admit, the second point would have to be improved.
Nope, unfortunately I am not a developer, otherwise I would have been helping with developing this magnificent piece of software LONG time ago. I am just a software expert, a professional, a power user, a man who knows what it's necessary in order to work optimally.
This is why I am doing deep analysis of the Tox software (qTox, uTox and Antox) and trying to give you ideas and motivate you to bring this very nice program(s) to a higher state of perfection :-) Thank you!

**Comment by GrayHatter** [comment]
old repo... please open https://github.com/GrayHatter/uTox/issues
