### ISSUE TITLE
[Documentation] No, description in the wiki

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1127]
There is no description of uTox in the tox-chat-wiki: https://wiki.tox.chat/clients/utox are they any special features which are different from qTox (https://wiki.tox.chat/clients/qtox)?

**Comment by nachfuellbar** [comment]
No special features
uTox is bascially less ressource hungry than other clients

**Comment by Jeeppler** [comment]
Is there any specific reason why uTox is less ressource hungry?

**Comment by stal888** [comment]
It's the str8c

**Comment by Jeeppler** [comment]
What ?????????

**Comment by aviau** [comment]
L337sp34k:
> It's the str8c

English:
uTox is written in C.

**Comment by cmotc** [comment]
I've created a page on the wiki for uTox. https://wiki.tox.chat/clients/utox.

**Comment by Jeeppler** [comment]
@cmotc nice work :+1:
