### ISSUE TITLE
Language settings don't save after changing

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#1129]
How to reproduce:
* open Tox;
* change language to another;
* close Tox;
* open again: language will be the same before changing.

This happens only with language, other settings save correctly.

Win 7 x64, Win 8.1 x64. v. 640.3.2.

**Comment by danbelov** [comment]
Bug successfully reproduced on Debian 8 x64. Thank you for reporting!
I've reviewed util.c , where all config work is being made.
It seems, that language settings weren't being saved at all.
I wrote a small fix for that, and will test and make pull request this week

**Comment by GrayHatter** [comment]
please open this issue at https://github.com/GrayHatter/uTox/issues
