### ISSUE TITLE
[Feature request] Meta-contacts (unite several contacs)

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#1131]
For example, when one person is using Tox at work and at home, and he doesn't want to copy-past app files, he has two Tox IDs.

And it will be very handy to group all his contact to one _meta_-contact.

Is it possible?

**Comment by ace13** [comment]
There have been talks about multi-device Tox accounts, I don't think anything has come from them so far though.

**Comment by SkyzohKeyx** [comment]
This as been debated for long time in qTox issues, this seems to be a bad idea. :x

**Comment by GrayHatter** [comment]
this isn't a terrible idea, just not something I want to touch without proper core support.

if you want to argue for its importance https://github.com/GrayHatter/uTox/issues
