### ISSUE TITLE
[question] Changing displayed name of friends

### ISSUE THREAD

**Issue by metroidchild** [notsecure/uTox#1137]
Just downloaded uTox from utox.org this morning and created an account. Got  friend to do the same, when we tried to add eachother all we could see was each others toxid's, any ideas of why this happens/how to fix this. In example images/videos friends are clearly labeled as "Cynthia", "Bob" or whatever, not the generated 76 char or so long string. It's really annoying to have to add your friends to a group chat just to keep some form of organization instead of just guessing.

edit: I can't change the names of groupchats either, their default names (Groupchat #0...) is set in stone.

**Comment by metroidchild** [comment]
I now know what the issue was, it was that the version that supported changing names was the alpha, and nowhere did any text say these features was not present on the default download on the uTox website. I had to go to other options when choosing what download I wanted. This SHOULD be clearly visible somewhere as it has a major flaw in causing confusion, but that's for the person who is in control of the website.

**Comment by GrayHatter** [comment]
I have no idea what the issue was, if you could provide some images I could try and fix this problem... I'd rather not have other users have this problem too!

**Comment by metroidchild** [comment]
Basically users show up as their tox id without anything else on the default installer. And on the alpha (accessed from "other alternatives" on download page) I get full functionality, I can't really explain it any other way. I also don't have tabs in the settings on the regular download, which alpha has.

**Comment by GrayHatter** [comment]
uTox sets the default name to uTox user, and once your friend connects, their name will change from their ToxID to their name, (or default name.) 

You and your friend must be online at the sametime... If you're getting messages from a friend and their name is their ToxID, I'd very much like to see that bug...

**Comment by metroidchild** [comment]
I'll open up uTox again, I switched to qTox for my main driver though, usernames + passwords = yummy. I'll post again in a little bit

**Comment by metroidchild** [comment]
Ok there's something much worse going on here, we can see each other online, but we can't write to each other. We can only see what we tried to send.

**Comment by metroidchild** [comment]
I think the issue is that the laptop I was using (school one) is a tiny bit to anal about internet connections, wouldn't want us using secure connections you know. But for some reason it works on alpha and qTox. So I really can't help you more than that, probably just school bloatware causing issues.
