### ISSUE TITLE
[Feature request] Remote Control or Remote Assistant.

### ISSUE THREAD

**Issue by sphinx-wang** [notsecure/uTox#1138]
We need this feature to help others online.

**Comment by cebe** [comment]
Could you explain a bit what this feature should look like or do?

**Comment by LittleVulpix** [comment]
I'm guessing teamviewer-esque functionality.

**Comment by SkyzohKey** [comment]
I personally never needed this. This feature would makes uTox even more bloated than currently...

**Comment by cmotc** [comment]
I'm against this being a part of uTox, but Iike the idea of remotely controlling another computer over Tox. Back when ratox still worked, you could do the "SSH over Tox for the practical paranoid" and control a remote machine via SSH. Something like that would be more appropriate for this kind of task. The biggest advantage is just using the Tox ID's for addressing each machine. ratox never worked on Windows though, so you'd have to create something to work with there.

**Comment by GrayHatter** [comment]
@cmotc there's a ToxVPN client somewhere, maybe that will serve you well?

otherwise, I probably will implement this feature at some point. but it won't be any time soon... And I'm open to changing my mind if there's a consensus

**Comment by sphinx-wang** [comment]
@GrayHatter  Thanks. It's a good message to me.

**Comment by dcapeletti** [comment]
This is an implementation that ALL users of GNU / Linux appreciate. It will raise your reputation. Thank you very much for considering this possibility.

**Comment by GrayHatter** [comment]
this would be very hard to do correctly... but I'm not opposed to it.

open it https://github.com/GrayHatter/uTox/issues if you still really want this
