### ISSUE TITLE
  // , "Delete" key deletes all history and contact.

### ISSUE THREAD

**Issue by v6** [notsecure/uTox#1139]
// , This is likely a low-priority issue, but a friend of mine noticed that when she pressed the "delete" key while my chat log was open and the text entry area wasn't selected, it deleted my entire history and contact information. 

Steps to repeat this bug: 

1. Begin a chat session with a contact. 
2. Select some of that contact's chat history, or simply do anything with the mouse that makes it so that the input area does not "have the cursor". 
3. Press the "del" or "Delete" key.
4. Watch, in dismay, as their entire history and contact information goes away.

**Comment by v6** [comment]
// , 

Here's the log: 

    SelectionRequest
    Writing tox_save to: /home/nb/.config/tox/tox_save.tox.tmp
    Saved data
    CHMOD: success

**Comment by GrayHatter** [comment]
@v6 thanks for opening this issue. It's fixed in both master here and on my new repo!
