### ISSUE TITLE
utox doesn't inform the user if sent messages have been acknowledged.

### ISSUE THREAD

**Issue by TrakTxx** [notsecure/uTox#1140]
It is possible to send a text message to a user that appears online but actually isn't. From the point of view of the sender, the message was correctly sent, but the recipient never received it. 

If user B goes offline, but still appears online to user A, user A can send a message to B and the utox GUI of the sender will look as if the message was correctly sent although B didn't receive it. 

So, the GUI needs to inform the sender whether the messages have been acknowledged by the recipient, or not.

**Comment by GrayHatter** [comment]
https://github.com/grayhatter/uTox/issues/

**Comment by TrakTxx** [comment]
Keep sent messages in a queue. If after xx seconds a message hasn't been acknowledged, inform the user?

**Comment by SkyzohKey** [comment]
[**@TrakTxx**](https://github.com/TrakTxx) commented on [15 Oct 2015, 07:33 GMT+2](https://github.com/notsecure/uTox/issues/1140#issuecomment-148286216 "2015-10-15T05:33:29Z - Replied by Github Comment Enhancer"):
> Keep sent messages in a queue. If after xx seconds a message hasn't been acknowledged, inform the user?

Toxcore have a friend_read_receipt callback. Would use it.

**Comment by GrayHatter** [comment]
old repo, and debatable issue
