### ISSUE TITLE
uTox dependency issues on Debian/Ubuntu systems

### ISSUE THREAD

**Issue by baco** [notsecure/uTox#1142]
The package lists generated in https://pkg.tox.chat/debian/dists/nightly/release/binary-amd64/ and https://pkg.tox.chat/debian/dists/nightly/release/binary-i386/ claim that uTox depends on ``libX11-6`` but such package doesn't exists on Debian, nor Ubuntu, because package names only use lower case letters in names; hence ``libx11-6`` would be the correct dependency.

Although inside the package the dependency is correct, ``apt`` complains of unmet dependencies because it reads the the lists in ``/var/lib/apt/lists`` instead of package ``control`` file.

    $ sudo apt install utox
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    utox is already the newest version (0.3.2-fcf826a-26).
    You might want to run 'apt-get -f install' to correct these:
    The following packages have unmet dependencies:
     utox : Depends: libX11-6 but it is not installable
    E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

It happens the same trying to install **any** other package. So uTox repository is breaking the normal use of the installation tool system wide.

**Comment by GrayHatter** [comment]
@stal888 @zer0-one @optimumtact

**Comment by optimumtact** [comment]
Thanks for reporting this, I've fixed this in our upstream jenkins, although it will usually take about 24hours to clear to the package repo.

**Comment by stal888** [comment]
sorry

**Comment by GrayHatter** [comment]
fixed, thanks guais!
