### ISSUE TITLE
error when trying to open utox_runner.exe

### ISSUE THREAD

**Issue by andezgrip** [notsecure/uTox#1144]
"Error fetching version data. Please check your internet connection.

Exiting now..."

internet connection is fine

![2015-10-28_20-44-26](https://cloud.githubusercontent.com/assets/9698335/10807320/b92a86ea-7db4-11e5-8f12-714004d71562.png)

**Comment by GrayHatter** [comment]
@irungentoo

**Comment by GrayHatter** [comment]
can you try again? 

If it still happens, I'm going to need some more information. It's working for me

**Comment by andezgrip** [comment]
yep, it works now. thx
