### ISSUE TITLE
uTox causing Window Audio Device Graph Isolation(audiodg.exe) cpu usage 4% on windows 8.1

### ISSUE THREAD

**Issue by agilob** [notsecure/uTox#1145]
https://www.reddit.com/r/projecttox/comments/3qumiv/utox_causing_window_audio_device_graph/

**Comment by GrayHatter** [comment]
please open https://github.com/GrayHatter/uTox/issues

**Comment by agilob** [comment]
Sorry, I stopped using *tox and this issue was not my problem but found on reddit, I don't use windows so can't tell anything more about it.
