### ISSUE TITLE
utox_window_{width,height} aren't initialized properly

### ISSUE THREAD

**Issue by flussence** [notsecure/uTox#1146]
I have Openbox configured to open uTox on a fixed workspace, maximized and with no titlebars. uTox seems to be relying on the WM adding its titlebar just after creating the window to trigger a resize event: it's creating a window with the previously saved width/height correctly, but ends up using the hardcoded values at xlib/main.c:1243 for drawing the contents, so the bottom and right of the UI gets truncated until I manually resize or move it.

**Comment by GrayHatter** [comment]
can I have an image of the problem? Send it to https://github.com/GrayHatter/uTox maybe?

**Comment by ghost** [comment]
Never mind, everything seems to work now the ebuild's using your repo.
