### ISSUE TITLE
Tox using a constant 2-5KB/s, ultimately using 5-13GB a month on background alone.

### ISSUE THREAD

**Issue by Snorflake** [notsecure/uTox#1147]
[after noticing the usage in resource manager](http://www.snorflake.com/u/PyUa.png)

i did a few calculations to see how much data was being used. 
x(KB/s)\*60\*60\*24\*30
it only used to use two (a few weeks ago) but now it uses 5.
so lets calculate that shall we?
5\*60\*60\*24\*30
that's 12,960,000KB. or 12.96GB a month.
Considering it only recently switched to 5, [here's a screencap of my past 30 days usage](http://www.snorflake.com/u/vW6e.png)

clearly unacceptable.

**Comment by irungentoo** [comment]
When did you first notice that usage increased?

**Comment by Snorflake** [comment]
about twenty minutes ago is when I confirmed how much it was using. my
friend recommended I post an issue. 2kb/s has been there for ATLEAST a
month

**Comment by GrayHatter** [comment]
core issue, please open this at https://github.com/irungentoo/toxcore/issues if it's still happening
