### ISSUE TITLE
libtoxav new api broke utox

### ISSUE THREAD

**Issue by sylware** [notsecure/uTox#1148]
It seems that the new libtoxav API broke utox

**Comment by LittleVulpix** [comment]
- OS ?
- utox version ? ( if not latest please update. )
- broke "how" ?

**Comment by LapFox** [comment]
Latest code is at https://github.com/GrayHatter/uTox have a go with that

**Comment by sylware** [comment]
On Fri, Nov 06, 2015 at 05:26:00AM -0800, Dan wrote:
> Latest code is at https://github.com/GrayHatter/uTox have a go with that

Yep. Fixed with this code. Thx.
