### ISSUE TITLE
New uTox UI seems buggy (or just ugly)

### ISSUE THREAD

**Issue by SkyzohKey** [notsecure/uTox#1149]
**Default theme:**
![](http://i.imgur.com/fikFPxu.png)

**Light theme:**
![](http://i.imgur.com/KHujf0A.png)

**Dark theme:**
![](http://i.imgur.com/hVhxiu5.png)

**Zenburn theme:**
![](http://i.imgur.com/XkohB5W.png)

**Hight Contrast theme:**
![](http://i.imgur.com/3fItFpv.png)

**Comment by LittleVulpix** [comment]
Wow I really like the dark theme. The rest of the themes are kinda meh but I wouldn't say ugly. Care to show what you'd change? (p.s. I found the "THIS IS REALLY UGLY !" line in each picture increasingly more hilarious :D )

**Comment by SkyzohKey** [comment]
The enter-a-message input and the side buttons have too many height. The file transfer "item" in the chat form is too wide (making it ugly). Also the search bar is hidden and you now have to click a button to make a search, which make it boring to use :x

**Comment by GrayHatter** [comment]
Yeah, I'm going to change the layout on the left, I can't find a way I like, so I'm just going to strip out everything...

**Comment by SkyzohKey** [comment]
@GrayHatter The old UI was better IMHO. Maybe having the dark theme as the default one would be nice ;)

**Comment by ElLamparto** [comment]
@GrayHatter, IMHO the four buttons on the left should go back to the bottom, otherwise the form is out of balance. The dark theme is the best, it should be the default, and.... µTox should keep the theme setting after restart.

Otherwise it is a big improvement!

Again, a small video preview button on the main form would be useful. Going every time to settings is awkward.

**Comment by DanTheBritish** [comment]
That paperclip is way too big. It should also be right aligned to the partition.

The font for the text (names, chat, etc) is too bold in my opinion and could be toned down a stroke or two.

**Comment by GrayHatter** [comment]
new UI that seems better, otherwise wrong repo
