### ISSUE TITLE
uTox no longer gives the receiver message notifications (Win7)

### ISSUE THREAD

**Issue by DexterMcKinnery** [notsecure/uTox#1150]
Since the update recently, it seems that my uTox is no longer giving me notifications when somebody has sent me a message, file or screenshot/image. It used to flash on the taskbar and give me a pop-up notification in the bottom corner. Now I get no notifications at all.

I'm using Windows 7 if it helps.

**Comment by GrayHatter** [comment]
I'm going to need some more information. I can't duplicate this

**Comment by DexterMcKinnery** [comment]
What more info would you like, GrayHatter?

**Comment by GrayHatter** [comment]
what version are you on?

can you screen record your desktop during a message coming in without the notification?

can you try an older version and see if that still works?

is there still a tray icon?

does it do anything else?

could you start it from the command line so that I can see the debug output?

**Comment by DexterMcKinnery** [comment]
It's version 0.4.2.

I can't screen record, but I can livestream it to you... I can do that right now if you need. I can send myself messages from my laptop to demonstrate.

I'll see if I can try an older version in a bit!

There is indeed still a tray icon!

I don't think it does anything else weird... I can just never tell when somebody's messaged me! I can still see when people are online etc.

I've opened it from the command line, but I don't get any debug output from it... it just opens the program.

**Comment by DexterMcKinnery** [comment]
Another problem that is unrelated, but I figure needs mentioning is; I just found is that the typing notification now goes underneath your typing box.
![image30](https://cloud.githubusercontent.com/assets/15704583/11021634/5ff3ea46-8640-11e5-9229-61bc955fee6c.png)

**Comment by GrayHatter** [comment]
@DexterMcKinnery come find me on IRC so I can watch your system while I send you messages... I have no idea why it's not working as I'm getting them with windows 10.

**Comment by GrayHatter** [comment]
stale, if not, https://github.com/GrayHatter/uTox/issues
