### ISSUE TITLE
Can't build utox on archlinux

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#1151]
Using the arch repo with the makepkgs provided, https://github.com/Tox/arch-repo-tox

[sorunome@sorunome-desktop utox-git]$ makepkg -Cfis
==> Making package: utox-git r1815.7db443f-1 (Sun Nov  8 01:01:19 CET 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating utox-git git repo...
Fetching origin
==> Validating source files with md5sums...
    utox-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of uTox git repo...
Cloning into 'utox-git'...
done.
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
  CC    tooltip.o
In file included from tooltip.c:1:0:
main.h:417:1: error: unknown type name ‘ToxAv’
 ToxAv* global_av;
 ^
tooltip.c: In function ‘tooltip_thread’:
tooltip.c:151:18: warning: unused variable ‘b’ [-Wunused-variable]
         TOOLTIP *b = &tooltip;
                  ^
Makefile:112: recipe for target 'tooltip.o' failed
make: *** [tooltip.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by GrayHatter** [comment]
it's fixed now... also https://github.com/GrayHatter/uTox

**Comment by Jeeppler** [comment]
@GrayHatter is it updated in the aur packages for uTox too?

**Comment by GrayHatter** [comment]
@Jeeppler I don't have control of them, so maybe? I did test the utox-git from the aur, and it compiled for me.

**Comment by Jeeppler** [comment]
@GrayHatter now it works for me too :-)
