### ISSUE TITLE
CONGRATULATIONS, IT IS SO MUCH BETTER !!!

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#1152]
Dear fellow uTox developers !!!!!
I have just tried the new version 0.4.2 of uTox and it is SO much better !!
The alias function is finally here and multichats are working soooo much better!!!
THANK YOU SO MUCH !!! What an outstanding job have you done !!!!!
Keep that excellent work going !!!

**Comment by GrayHatter** [comment]
thanks mate!

**Comment by ElLamparto** [comment]
Looks great (especially the dark theme). µTox got a new life!
Hopefully this version will be in the Debian repo soon (yesterday, 8th Nov. there was no update yet).

**Comment by GrayHatter** [comment]
@stal888

**Comment by stal888** [comment]
@GrayHatter I'm seeing 0.4.2-9ef7855-29 in Packages

**Comment by optimumtact** [comment]
We had an issue with duplicate packages making the index not update. Should be resolved now.
