### ISSUE TITLE
No uTox updates for Debian 32bit

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#1155]
Via [deb https://pkg.tox.chat/debian/ nightly release], I get updates of toxic and qtox, but no longer µTox. Still using 0.3.2 version :-(.

**Comment by GrayHatter** [comment]
@stal888

**Comment by stal888** [comment]
@Zer0-One

**Comment by Zer0-One** [comment]
@optimumtact

**Comment by optimumtact** [comment]
we switched to a pull based method of pulling packages and it doesn't look like it was correctly plugged into the build chain.

i've run it manually and then updated the packages @ElLamparto are you seeing the newer 32 bit version of utox now?

**Comment by ElLamparto** [comment]
I'll check it tonight.

**Comment by ElLamparto** [comment]
Still no update available. Got new versions of qtox and toxic, but no utox.

**Comment by GrayHatter** [comment]
https://pkg.tox.chat/debian/pool/release/u/utox/

are you sure you're using the correct repo?

**Comment by ElLamparto** [comment]
No, I use [deb https://pkg.tox.chat/debian/ nightly release]

So for µTox it wil be:
[deb https://pkg.tox.chat/debian/pool/release/u/utox/ nightly release].

Is that right ?

**Comment by optimumtact** [comment]
Can you post the output of 

```
apt-cache show utox 
```

This is what I get
oranges@jumphost:~$ apt-cache show utox
Package: utox
Version: 0.4.2-9ef7855-46
License: GPLv3+
Vendor: Project Tox
Architecture: amd64
Maintainer: Project Tox support@tox.chat
Installed-Size: 2844
Depends: libx11-6, libxext6, libxrender1, libfontconfig1, libfreetype6, libdbus-1-3, libv4l-0, libopenal1
Homepage: https://utox.org
Priority: extra
Section: default
Filename: pool/release/u/utox/utox_0.4.2-9ef7855-46_amd64.deb
Size: 1073768
SHA256: de542f1c987fdf060806e5a227498808d444a6e30dc87efce20918be8c661c36
SHA1: c3c3de77cd89754951ad2deb5e866d8958ba92b1
MD5sum: 9bf09a3d31e375b6f4e213da2081e856
Description: The future.
Description-md5: 830c63299904f625a13386614aabd84e

Also, these instructions should be all thats needed to setup our repo

```
 https://wiki.tox.chat/binaries#gnulinux
```

**Comment by ElLamparto** [comment]
~$ apt-cache show utox
Package: utox
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 2357
Maintainer: support@tox.im
Architecture: i386
Version: 1.0-934
Description: no description given
Description-md5: c0af8b65ef8df63b3bfb124d96da1778
License: GPLv3+
Vendor: Tox Foundation
Homepage: https://tox.im

Again, I receive qtox and toxic updates, but no utox updates.
Repo setup like described in https://wiki.tox.chat/binaries#gnulinux.

Could you post the contents of your sources list?

In my case:
File: /etc/apt/sources.list.d/toxrepo.list
Contents:
deb https://pkg.tox.chat/debian/ nightly release

**Comment by nachfuellbar** [comment]
@ElLamparto I would uninstall and reinstall utox because apt-get doesn't support downgrade (only version number would downgrade on your installation) with "apt-get upgrade" 

you either use
apt-get remove utox && apt-get install utox

or you use
apt-get install utox=0.4.2-9ef7855-38

**Comment by optimumtact** [comment]
@GrayHatter you may want to consider a significant version bump to fix that.

@EILamparto It looks like you still have the utox version from the tox.im repo and as @nachfuellbar mentioned the version is higher than the new tox.chat repo. Uninstalling and reinstalling should fix it - be aware that this might delete your data file, so you may want to back it up.

**Comment by optimumtact** [comment]
@GrayHatter you may want to consider a big version bump to sidestep this issue.

**Comment by ElLamparto** [comment]
I did it differently.
I manually downloaded the deb file and upgraded utox. Now 'apt-cache show utox' shows the correct version, so I suppose aptitude should work from now on.

Thank you all.

**Comment by optimumtact** [comment]
Thanks for raising this issue as well, I had no idea the old tox.im repo packages had such high versions. Something for us to keep in mind.

**Comment by GrayHatter** [comment]
thanks @optimumtact
