### ISSUE TITLE
Regression: video kills audio again

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#1158]
Audio alone works fine. After switching on video, audio stops (or just some cracks are produced). The video itself is ok.

Reverting to the old version on both sides (0.3.9 if I remember well) fixes the problem.

Debian Jessie 32bit connects to Win7 64 bit.

**Comment by GrayHatter** [comment]
can you duplicate that with any other friends, or with an echo bot?

also => https://github.com/grayhatter/uTox/issues/

**Comment by ElLamparto** [comment]
@GrayHatter: I don't need to. I manage my friend's system via TeamViewer myself ==> everything was done correctly. We have tried a few times. We had a decent Internet connection.

**\* The old uTox version works without an issue.***

IMHO the issue should stay open (unless it is a duplicate).

**Comment by cebe** [comment]
@ElLamparto please open the issue at https://github.com/grayhatter/uTox/issues/ , because: https://github.com/notsecure/uTox#this-repository-is-no-longer-maintained

**Comment by GrayHatter** [comment]
@ElLamparto I was wondering if it was a linux issue, or a windows issue, so if you tried it with linux <=> linux, I'd know more where to look

**Comment by ElLamparto** [comment]
@GrayHatter, I understand.
I have two Debian machines at home, but on the LAN everythig works correcly. 

I have exactly the same issue with qTox. I tried Win7 32bit to Debian 32bit.
Could it be a toxcore problem? Should I open a ticket for toxcore?

One more thing. Sometimes the audio works with video on, but only one way. And the audio quality is good!  Could it be a problem of audio session initialization when the available bandwidth is limited ?

µTox had the same problem about a year ago, but then it was fixed.

**Comment by ElLamparto** [comment]
@GrayHatter, sorry for still being here... ;-)
When an audio is on and the user requests a video: is the audio session reinitialized?

While chatting, qTox has a nice feature to notify user on ACK reception.
I just had a video call with someone via qTox and the audio was one way only.
She did not hear me, so she sent some text messages. She said that it took up to 30s to get an ACK (normally it takes 1s or less).

Maybe while initializing an audio session, the timeout or the number of retries should be increased?
I do not know if it is managed in µTox or in the toxcore... Just an idea..

**Comment by GrayHatter** [comment]
> When an audio is on and the user requests a video: is the audio session reinitialized?

 not in uTox, don't know about toxcore you'd have to ask @mannol

as for the other question, I'd have to ask irungentoo

**Comment by mannol** [comment]
There is no reinitializing of any kind. I'd say it's an error with qTox.
