### ISSUE TITLE
Panel icon is a white square (LinuxMint)

### ISSUE THREAD

**Issue by Aranad** [notsecure/uTox#1159]
This problem has persisted for many versions now, I've attached a screenshot.
![utox_panel_icon](https://cloud.githubusercontent.com/assets/1755922/11225272/6e58858e-8d60-11e5-891a-b61e2fcb6bd1.png)

**Comment by cebe** [comment]
which desktop environment is that? Gnome, MATE, KDE?

**Comment by Aranad** [comment]
Cinnamon

**Comment by GrayHatter** [comment]
See this repo and PR for this fix https://github.com/GrayHatter/uTox/pull/14
