### ISSUE TITLE
guide fo utox compilation on Tails

### ISSUE THREAD

**Issue by ghost** [notsecure/uTox#1160]
Hi every one.

I have written an article on utox compilation on Tails distribution.  I could not find email if of maintainer however i am sharing here link for uTox compilation.

http://linoxide.com/security/install-utox-client-tails/

Please include it in uTox ReadMe/Install file.

**Comment by GrayHatter** [comment]
@naviduett you're at the wrong repo mate https://github.com/grayhatter/utox
