### ISSUE TITLE
Profile password doesn't work

### ISSUE THREAD

**Issue by erejnion** [notsecure/uTox#1162]
Today for some reason I can't unlock my profile anymore. Password is correct, and language input is correct, and caps lock isn't on, and so on. I didn't have this issue yesterday

Using 0.5.1 under Win7 Professional 64bit, up-to-date with patches.

**Comment by GrayHatter** [comment]
if you run utox.exe from a command window you can get some debugging output. but unless it displays an error of some kind. There's not much I can do.

**Comment by erejnion** [comment]
That was one of the first things I tried, to no avail. However.
Decided to brute-force "my password+random letters tacked on in the end", after jokingly saying that yesterday I may have typed something in the options without realizing I am typing there.
It worked. 

Can you put the password in a separate tab in the options, or at least not in the main one, as part of idiot-proofing it? I doubt I will be the only retard to do something like this.

**Comment by GrayHatter** [comment]
yeah, you're on the wrong repo that's already been suggested there, and I'm planning to fix that once I have the time
