### ISSUE TITLE
Regresions. screenshots 0.5.0

### ISSUE THREAD

**Issue by ghost** [notsecure/uTox#1164]
Regressions. screen shots 0.5.0

Hi. First off thanks for creating this wonderful tool.

The screen shot tool is poorly thought out for users like me that tend to run applications maximized. Having to un-maximize utox move it's window to some other part of the screen while still needing to select the snap icon is not great. Also not being able to change to and snap another desktop.

The option of a 10 second delay  would be a great improvement

**Comment by GrayHatter** [comment]
this is a dup from this repo, but it's on my list. open https://github.com/GrayHatter/uTox/issues to make sure I don't forget about it?
