### ISSUE TITLE
Offline message

### ISSUE THREAD

**Issue by dcapeletti** [notsecure/uTox#1169]
It would be interesting to be able to send a message to a friend when you are offline.

**Comment by SkyzohKey** [comment]
It would use faux-offline message. Like qTox do.

**Comment by GrayHatter** [comment]
dup, wrong repo

**Comment by SkyzohKey** [comment]
@GrayHatter Are you stalking me ? x)
I see you closing all the issue i commented first e.e

**Comment by GrayHatter** [comment]
I'm closing the issues that looked interesting, or needed updates... just means you make good choices in issues too
