### ISSUE TITLE
Multichats

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#1170]
Hello,

I was curious what's new and how development of the product is going...
So, I went and downloaded the last version. I am very very surprised now,
as I am unable to find the button to start a multichat.
Please kindly explain me how to create a multichat. I can't be that this
feature has been discontinued, can it ?

Thank you!

**Comment by SkyzohKey** [comment]
You have to right click on your friendlist and click "**Create Groupchat**", then drag' n'drop your friends into the group. :)

**Comment by darkman088** [comment]
Hello,

I think I have been trying the right click, but I will have a look again. Many thanks for your prompt answer!

**Comment by darkman088** [comment]
OK, you should have said to click in an empty space... I have been trying to click on one of the contacts that I want to have the multichat with. Thanks a lot, I am closing this.

**Comment by darkman088** [comment]
Sorry, but I have to reopen this, in order to ask the same question once more.
I have just downloaded verion 0.8.0 and again I have to clue how to start a multichat...
Right clicking, left clicking everywhere - no such option, please kindly enlighten me again ;-)
Thanks a lot !!

**Comment by GrayHatter** [comment]
https://github.com/GrayHatter/uTox

**Comment by darkman088** [comment]
OK I have posted the question there, thank you!
