### ISSUE TITLE
Trouble with multichats

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#1171]
Hello,
I have a question, this is probably going to be something specific and not (yet) faced by many people.
So, I am creating a multichat with 2 other contacts. All is good, until somebody disappears for a few
seconds, probably due to bad internet connection. When he comes back online, he is out of the
multichat and there seems to be no way to add him again. When I try to "drop" him to the multichat,
just nothing happens. So, I would need to terminate the current multichat, create a new one and
drop all the participants again into the new multichat - this is quite difficult and time-consuming.
Could you please kindly look into that and try to solve it somehow ? Please...

Many thanks in advance!!

**Comment by SkyzohKey** [comment]
New groupchats will resolve that.

**Comment by darkman088** [comment]
Thanks for the answer. What is the current planned date of their implementation ? Just to know when to check for a new version... Thank you!

**Comment by GrayHatter** [comment]
wrong repo
