### ISSUE TITLE
Feedback from another cross-platform test...

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#1173]
Dear Tox community,

today I have performed a new cross-platform test of uTox, between Windows 7 and Fedora 20.
We have tested the latest version (0.6.1) on both systems.
I will start with, unfortunately, the only positive point: I was hearing my counterpart very well !!
The sound quality has improved a LOT, since the last test I have performed.
Now the bad and buggy points:
1) When my counterpart called me, I immediately click on the button to take the call, but either nothing happens (the ringtone is still ringing, no call is being open), or the call is open, but I still hear the ringtone as well !!
2) Only I was hearing my counterpart (Windows 7), my microphone didn't work, no matter what I tried). In the PulseAudio volume control app, I can of course see the bar moving when I speak, though I wasn't heard on the other side. 
3) Video calls were not working at all on neither side. The camera preview button in the options was working flawlessly on my side. The audio preview button was producing very loud noise.

I hope this helps for the further development of uTox and I hope to get some feedback on this report. Thank you very much!

**Comment by GrayHatter** [comment]
wrong repo mate

**Comment by darkman088** [comment]
Please kindly explain what do you mean by that and what should I do, in order to take corrective action to your comment. Thank you!

**Comment by cebe** [comment]
@darkman088 please report this at https://github.com/Grayhatter/uTox/issues instead. Development is going on in the new repo.

**Comment by darkman088** [comment]
Thank you, cebe, I did it!
