### ISSUE TITLE
Please provide a ZIP file for simple distribution, and not a downloader itself.

### ISSUE THREAD

**Issue by xcatbayx** [notsecure/uTox#1174]
Your website, utox.org, offers only "downloader"(utox_runner.exe) and not a software itself.
IIRC, I could download utox-win32.zip or utox-win64.zip directly(I forgot a source URL).
(inside of zip is 1 utox.exe)

I don't like Downloaders, and it also doesn't support proxy.
Please let the user to choose which to download 32 or 64.

**Comment by cebe** [comment]
This repository is no longer maintained, please report to https://github.com/GrayHatter/utox instead

**Comment by xcatbayx** [comment]
@cebe but utox.org website has a link to @notsecure 's github.

Where's a proof that @GrayHatter is the owner of utox.org?

**Comment by xcatbayx** [comment]
This is REALLY comfusing... utox.org and tox.chat... what!?

**Comment by cebe** [comment]
@xcatbayx there are the following links on utox.org if you scroll down:

> Project Links
> GitHub: toxcore,
> uTox (Old),
> uTox (Current) 

"uTox (Current)" points to https://github.com/GrayHatter/utox

**Comment by GrayHatter** [comment]
thanks @cebe

**Comment by cebe** [comment]
> This is REALLY comfusing... utox.org and tox.chat... what!?

https://tox.chat/ is about tox, as the tox network in general, http://utox.org/ is one of the tox clients.
