### ISSUE TITLE
Update Code top section

### ISSUE THREAD

**Issue by xcatbayx** [notsecure/uTox#1175]
> Code
> Lightweight Tox client http://utox.org

> README.md
> This repository is no longer maintained!
> Please report issues or create pull requests here: https://github.com/GrayHatter/utox

You could copy README.md's big announcement to "Code" top section.

**Comment by GrayHatter** [comment]
Do what now?

**Comment by cebe** [comment]
Guess the suggestion is to replace repository description and homepage URL, so one does not have to scroll to the readme to see that this repo is not maintained anymore.

**Comment by GrayHatter** [comment]
Oh, I can't do that only @notsecure can, and he's RIP
