### ISSUE TITLE
uTox problems Pinyin input method Characters candidate frame orientation bias

### ISSUE THREAD

**Issue by uname2p** [notsecure/uTox#1177]
Full text in English through Google Translator to translate Chinese into English, described inaccuracies vexed.
Operating System: Windows 10
Pinyin input software: Microsoft Pinyin input software

In China, most people chat through Pinyin input software: Implementing Character entry (such as Microsoft Pinyin input method Google Pinyin, etc.), other minorities using other means five-stroke input method.

In early 2014 times using uTox found the presence of Chinese characters Pinyin input method candidate frame offset positioning problems, but because I can not express clear English, so there is no feedback. 0.9.1 version recently seen in all aspects have been greatly improved, so hopefully author properly consider the issue of Chinese input method.

Under normal circumstances, after the phonetic alphabet input Chinese characters, Chinese characters should be the candidate frame at the cursor are decentralized and lists all matching characters to choose from.

Currently different Pinyin input method uTox under both the candidate frame location offset to varying degrees, some Chinese characters Pinyin input method candidate box appears in the upper left corner of the screen, and some appear in the lower left corner, and so on.

Finally thanks to the developer's dedication uTox

**Comment by GrayHatter** [comment]
@uname2p I'm having a little trouble understanding you. 

Could you add a picture?

Also, this is the old repo, you should be using https://github.com/GrayHatter/uTox
