### ISSUE TITLE
v 0.9.4 Cant log in with disabled IPv6 and UDP

### ISSUE THREAD

**Issue by piddubnyi** [notsecure/uTox#1178]
After updating to v 0.9.4 I cant log in anymore. The client is closing immediately after password input.

Side question - what is default configuration file location under Windows so I can try to reset config or save profile for other client.

**Comment by GrayHatter** [comment]
https://github.com/GrayHatter/uTox/issues

you'll need to move/rename/delete the history files in you tox/ directory

**Comment by piddubnyi** [comment]
@GrayHatter But what is the default location for this files?
I'm using "portable" version, so I put it to something like C:\Privat\ipiddubnyi\tox\uTox
The only files there are tox_log.txt, uTox.exe, version, uninstall.bat, utox_runner.exe

**Comment by stal888** [comment]
The default data folder on windows appears to be `%APPDATA%\Tox`.

**Comment by piddubnyi** [comment]
@stal888 Big thanks, after removing the files it worked.
