### ISSUE TITLE
Sign with a valid developer identity

### ISSUE THREAD

**Issue by MartinDelille** [notsecure/uTox#1180]
The application isn't signed with a valid apple developer account, therefore doesn't run on OSX with protection enabled. I have a valid developper id. Could we use it to sign the application?

**Comment by GrayHatter** [comment]
wrong repo

**Comment by MartinDelille** [comment]
Do you accept donation via this plateform? http://liberapay.com

**Comment by GrayHatter** [comment]
@MartinDelille uTox currently doesn't have anything setup to accept donations, but if you're interested in donating to get us a cert I could set something up...

Also this is the repo you should be using https://github.com/GrayHatter/uTox

**Comment by MartinDelille** [comment]
In fact I have an Apple developer account so I could sign it myself. If you want easy donation setup, go for http://liberapay.com it is meant for that (no commission from the service, just CB fee).

**Comment by GrayHatter** [comment]
Sorry, my focus has been on toxcore the past few days. Still waiting on my
OS X dev to get back to me
