### ISSUE TITLE
WIN 8.1: Set utox to use custom DPI (90%) and get a huge window now mentiont "BUG. PLEASE REPORT".

### ISSUE THREAD

**Issue by elaurensx** [notsecure/uTox#1181]
Hey,

This is what I'm getting in the Settings/User Interface pane. Changed my DPI to 90% right before this crash happened. Can't change DPI any longer and i've got a huge window/text right now.

![capture](https://cloud.githubusercontent.com/assets/21011591/17648395/13e166c8-6246-11e6-833c-e8509d993697.PNG)

Thx for fixing :)

**Comment by GrayHatter** [comment]
this is the wrong repo https://github.com/GrayHatter/uTox
