### ISSUE TITLE
I have deleted password for my profile... now the avatar of my friends it's no more present

### ISSUE THREAD

**Issue by DjDiabolik** [notsecure/uTox#1184]
Previously i have login to my profile........ from option i have choosed to remove password from this profile and i have test if now autologini works.

I have closed Qtox and re-open it and yes... now autologin it's works but on friends list the avatar/profile picture it's not more showed... it's normal ? This appears only when you a protect profiles ?

**Comment by cebe** [comment]
> I have closed Qtox

if you are using qTox report the issue here: https://github.com/qTox/qTox/issues
if you are using uTox report the issue here: https://github.com/uTox/uTox/issues

**Comment by DjDiabolik** [comment]
O my good.... sorry :)
