### ISSUE TITLE
Is this utox icon?

### ISSUE THREAD

**Issue by zero-master** [notsecure/uTox#1189]
![](http://i.imgur.com/P8dUfXB.png)

utox version 0.16.1 alpha

Linux z97 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux

**Comment by cebe** [comment]
very likely, but you'd want to report this to https://github.com/uTox/uTox/issues instead. Also specify which desktop environment / window manager you are using.
