### ISSUE TITLE
video features

### ISSUE THREAD

**Issue by jf99** [notsecure/uTox#165]
When making a video call, one should have the option to receive both audio and video but only send audio. Such one-way transfer is especially useful when using the desktop sharing function.

Also, in audio calls there are often situations where one says "let me show you how to do this". Therefore it would be nice, if you could just add a (desktop) video stream (without cancelling the call and then start a new video call).

Finally, it would be nice if you could block the incoming video when you don't want to see it.

**Comment by GrayHatter** [comment]
half done, stale, optionally move existing issue to new repo
