### ISSUE TITLE
README screenshots broken link

### ISSUE THREAD

**Issue by ProfOak** [notsecure/uTox#167]
The two screenshots link to these 2 urls:
* [Win8](https://camo.githubusercontent.com/c8c4016b5e3f44bedfbdcb554a38d4b03828cd26/68747470733a2f2f7261772e6769746875622e636f6d2f6e6f747365637572652f75546f782f6d61737465722f696d616765732f75546f782d77696e33322e706e67) 
* [lubuntu](https://camo.githubusercontent.com/db6f5defea1088114eb4cfbe138906e6517e052d/68747470733a2f2f7261772e6769746875622e636f6d2f6e6f747365637572652f75546f782f6d61737465722f696d616765732f75546f782d786c69622e706e67)

They are both Not Found

**Comment by kriswema** [comment]
Close, maybe? @irungentoo :haircut:
