### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#169]

**Comment by mrbiber** [comment]
A [bounty for tray support under Ubuntu / Unity](https://www.bountysource.com/issues/7675742-support-ubuntu-unity-app-indicators-for-minimizing-to-tray)

**Comment by Serverkill** [comment]
Thanks for good news, good job ;) Hope too see same for autoaccept files!

**Comment by GrayHatter** [comment]
@Serverkill can you open an issue for that please?

**Comment by calimeroteknik** [comment]
Under X11, no icon at all appears in the systray. Is that normal?
(Xorg 1.16.3 on Linux 3.18.5)

**Comment by GrayHatter** [comment]
@calimeroteknik uTox currently doesn't have any tray icon support for linux. It's on the todo list... eventually, promise.

**Comment by gott3rfunk3n83** [comment]
Its fine now just switched to qtox.

**Comment by calimeroteknik** [comment]
@GrayHatter After a tiny search, I see there is [a FreeDesktop standard for X11](http://standards.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html) and [reference](http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html), so that's all good for Linux, *BSD, and others systems using X11.
I'm trying to understand these…

**Comment by GrayHatter** [comment]
@calimeroteknik if you can find me example code in C/C++ that includes right click options I can get this working in X for ~unix

**Comment by shalnoff** [comment]
Tray Icon doesn't appear and doesn't work in Mate (classic Gnome fork) as well as in LXDE. 
Standard window icon doesnt show as well. 
Please fix it. It's really annoying issue that makes uTox realy uncomfortable to use.

**Comment by fcore117** [comment]
do Linux should have this feature yet? i have not seen it on my Ubuntu gnome-flashback?

**Comment by calimeroteknik** [comment]
@shalnoff don't be grumpy like that; this isn't a bug, it's that the feature is not implemented yet.
If you feel like helping with it or paying somebody to do it, I'd also be delighted.

**Comment by GrayHatter** [comment]
I'm close to releasing some code for linux system tray. But before I do I wanted to find out what anyone thinks are the needs to haves and the nice to have features for the linux tray?

**Comment by dimgel** [comment]
It's good for me as it is now. Except for non-contrast incoming notification animation but I think you didn't mean graphical design in your question.

**Comment by GrayHatter** [comment]
@dimgel I meant anything... But what do you mean good as it is now, right now uTox doesn't have a system tray icon

**Comment by dimgel** [comment]
Damn sorry, I have to take some time for sleeping. I though I'm answering to qTox issue, not uTox.

**Comment by calimeroteknik** [comment]
@GrayHatter the usual nice-to-have things for a messenger client in the tray, I guess are:
- on left click: minimize/restore
- on right click: pop-up menu with status switcher, Quit, (and Mute maybe?)

**Comment by thedanish** [comment]
@GrayHatter 
Thank you so much! I signed up just to respond to you.
Needs:
Tray icon
Close to tray, either by closing the window or option on tray icon menu

Nices:
Online/Offline/Away icons for the tray
Message notification, like making the icon flash

I am currently using version 0.18-589. I noticed in the settings there are "close to tray" and "start in tray" but they don't appear to do anything. Is the feature fully implemented already? I am using tint2.

**Comment by tsudoko** [comment]
@thedanish they're implemented for win32
@GrayHatter could tray-related settings be hidden on xlib builds for now?

**Comment by GrayHatter** [comment]
@tsudoko wrap them in an #ifdef and I'll merge the PR, but I'm working on
the tray now, so it shouldnt matter soon™

**Comment by thedanish** [comment]
@GrayHatter  I noticed something in the update today. I can minimise to tray! Thank you. Sorry to say, but I cannot see an icon. Is there a specific icon set you are using? pic related, http://a.pomf.se/qvubur.png

**Comment by irungentoo** [comment]
@thedanish

There's no icon yet.

**Comment by zetok** [comment]
Closing, since minimizing to tray ~works.

**Comment by shalnoff** [comment]
Thin (1px) vertical white line instead of icon appears in tray.  Still no window icon! (v1.0-768)

**Comment by calimeroteknik** [comment]
Cool!
There's a problem directly related to 'minimize to tray' though:
When using window decorations, the window position is lowered by the title bar's height each time I cycle minimize/maximize.

**Comment by shalnoff** [comment]
Confirm to calimeroteknik's window issue (above) as well.

**Comment by dimgel** [comment]
I confirm calimeroteknik's issue too.

**Comment by shalnoff** [comment]
Deactivation of Compiz doesn't helps to make tray icon pops up. Just the same 1px thin vertical line instead.

**Comment by irungentoo** [comment]
Window position issues when unminimizing should be fixed in latest master.

**Comment by calimeroteknik** [comment]
I confirm that it's fixed. Thanks very much!

**Comment by shalnoff** [comment]
By clicking "icon" in tray the window starting to go up instead. (Mate + Compiz. ver 1.0-781)
The "icon" in tray still represented by 1px white vertical line. 
Complete removing and reinstallation doesn't helps.

**Comment by thedanish** [comment]
Well I just wanted to say, fully functional here. http://a.pomf.se/dyfvro.png
Everything works as expected, close to tray, start in tray and clicking on the tray icons to open and close the window. I will just note, it didn't work straight away but I had to delete the home config folder, copied out tox_save and put it back after. Tint2 btw.

**Comment by shalnoff** [comment]
> Everything works as expected...
unfortunately in my case it doesn't. I've removed everything and completey reistall the application. Everything stay the same. Thin 1px vertical line in the tray instead of icon (even no white box, as on your screenshot, just line) :(

**Comment by calimeroteknik** [comment]
@shalnoff there. is. no. icon. image. It's a blank square in your tray and it works.

**Comment by shalnoff** [comment]
@calimeroteknik, unfortunately in my case it doesn't (see above)

**Comment by shalnoff** [comment]
1.0-795 (Compiz + MATE) Still thin 1px vertical line in tray instead of icon (no white box showed above as well). 

Probably the nature of problem in the neccessity to have a direct declaration of width somewhere or have a dummy PNG in icon directory that wasnt created? I was looking in code but can't find anything relevant at first glance.
