### ISSUE TITLE
Xbox 360 Kinect with libfreenect uses IR camera instead of RGB camera.

### ISSUE THREAD

**Issue by aus4000** [notsecure/uTox#182]
This is why the raw IR won't work:
![](http://i.imgur.com/ZYpF6Fe.png)
It's kinda funny looking :P

My system is Arch Linux x86_64 with a fresh git compile of both Tox and µTox.

**Comment by GrayHatter** [comment]
@aus4000 I'm going to close this, please reopen if you still have any issues, or questions!
