### ISSUE TITLE
No voice on low speed connection

### ISSUE THREAD

**Issue by dmiko** [notsecure/uTox#188]
I can see other man via Skype if I have low speed connection. I hear him not always (dropped packets I guess), but I can talk with him.

In uTox with the same man I can not hear anything (he too). No, I have heard 1 word during 2 min try.

Encryption may not cause this problems (sizeof(encryptedValue) == sizeof(value)), so the problem is somewhere in network library / Tox core / UI wrapper.

**Comment by GrayHatter** [comment]
closed as stale, reopen or tag me if you can make this happen on demand.
