### ISSUE TITLE
Give contacts an alias

### ISSUE THREAD

**Issue by CowInAPie** [notsecure/uTox#190]
There was a discussion on the ability to change names at will, with the only constant being the ID code for a user here irungentoo/toxcore#756.

I was wondering if it would be possible to implement an alias function into uTox with it's own save, since toxcore is leaving it up to the clients. I was looking at possibilities for implementing this, but I thought I'd open discussion on it as well.

**Comment by darkman088** [comment]
@GrayHatter - thank you for all the effort to reference all the discussions about this topic. But unfortunately all of the referenced topics have been closed, and the current one contains nothing but the references to those closed topics. Here I am afraid, that I'm seeing a deadlock - closed topics pointing to each other. And as there are no other posts here, I am afraid that this topic is stalled and nobody is thinking about it. Can you please kindly let me know a status or prove my conclusions wrong ? Many thanks!

**Comment by GrayHatter** [comment]
@darkman088 sorry deleted that branch which closed the PR by mistake. This hasn't stalled, just put on the back burner until everyone recovers from the new major core api break/update

**Comment by darkman088** [comment]
OK, thanks for the info! I am (in)patiently waiting :-)

**Comment by darkman088** [comment]
Hello irungentoo, I see that you have closed the thread - may please kindly ask you about the status of this thread ?

**Comment by GrayHatter** [comment]
type `/alias new_alias_here` into your friends chat window

**Comment by darkman088** [comment]
So, it has been implemented ? COOL !! But I hope you realize, that together with the --portable option, such features become kinda hidden eastereggs if there is nothing on the menus, so perhaps it would be more intuitive if this option would be visible.
Sorry if I sound too annoying, but I think that this is in the interest of the mass user. Thank you!!

**Comment by GrayHatter** [comment]
@darkman088 @tsudoko already has that fixed, if you can compile the develop
branch, you'll get a dropdown for your contacts with an entry to change the
alias.

**Comment by darkman088** [comment]
Thanks, but that's the thing - I'd really like to get features and use them, not to care about compiling and stuff like that... There are many other topics for which I am not finding enough time, or not finding time at all! Thanks for your understanding!
