### ISSUE TITLE
Control over inputs.

### ISSUE THREAD

**Issue by CoenraadS** [notsecure/uTox#195]
Hello, uTox is shaping up nicely, but still lacking some features of other popular message programs such as Mumble.

In a chat there needs to be an option to disable:
voice input. (In chat send: [user] muted)
audio output (also disable voice input) (In chat send: [user] muted and deafened)
Mute specific users

And also push to talk #147

**Comment by GrayHatter** [comment]
Closed as stale, please reopen if you need to.
