### ISSUE TITLE
Fails to start on Debian Wheezy armhf, X window error

### ISSUE THREAD

**Issue by vandys** [notsecure/uTox#204]
Build from top of git for toxcore, then built top of git for uTox.  Startup fails, utox output follows.
I'll try some different display types when I can, and attach any additional data.  Thanks.
BTW, I did try to break on gdk_x_error(), but that symbol was never touched, so if
somebody wants me to break somewhere else & get a backtrace, just let me know.

a20$ ./utox --sync
File not found (utox_save)
Read 15815 bytes (tox_save)
Tox ID: C4F73154D75CE8B74E4F8CE94B638EF643421029E6C386B837B1487B11B4541A3ED26D849759
have GTK
frame size: 960
desktop: 1024 768
Connected to DHT: 1
Input Device List:
ALSA Default
sunxi-CODEC, sunxi PCM (CARD=sunxicodec,DEV=0)
Output Device List:
ALSA Default
sunxi-CODEC, sunxi PCM (CARD=sunxicodec,DEV=0)
sunxi-sndhdmi,  (CARD=sunxisndhdmi,DEV=0)
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-ExtraLight.ttf 0 30 -7
The program 'utox' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 227 error_code 8 request_code 148 minor_code 4)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
AL lib: ReleaseALC: 1 device not closed

**Comment by GrayHatter** [comment]
stale, open on new repo if this is still broken
