### ISSUE TITLE
Feature request: Linux system tray icon & menu.

### ISSUE THREAD

**Issue by roboman2444** [notsecure/uTox#208]
Being able to minimize uTox to the system tray would be very nice. Right clicking on the tray icon could bring up a small menu with options for recent chats.
Basically like Skype, Xchat, or Hipchat.

**Comment by GrayHatter** [comment]
dup of #169

**Comment by calimeroteknik** [comment]
The 'minimize to tray' part is implemented in #169 but that doesn't make this feature request complete.
It would be super-awesome to have:
- On a right-click on the tray, pop-up menu with a status switcher, Quit, (and Mute?)
- An icon that shows the status: the usual; disconnected from DHT red empty ❍, connected and not visible red full 🔴 or half-full, busy orange, connected green full `🔴`; or when there are new unread messages a phylactery 💬`💬`

**Comment by roboman2444** [comment]
Has minimize to tray been fully implemented? nothing changes and there is no tray icon in LXDE lxpanel. I've tried setting the options menu items but that does not help.

**Comment by irungentoo** [comment]
The functionality is implemented, it doesn't draw an actual icon yet though so most people see it as a black/blank square.

**Comment by roboman2444** [comment]
This appears to be fixed in the latest utox nightly. Now shows up as a white square on lxpanel.
It would still be nice to have a little right-click menu for it, but this is a good step.

**Comment by shalnoff** [comment]
ver 1.0-795 (Compiz + MATE) Completely reinstalled. 
Still thin 1px vertical line in tray instead of icon (no white square mentioned above as well).
Probably the nature of problem in the neccessity to have a direct declaration of width somewhere or have a dummy PNG in icon directory that wasnt created? 

Sorry for doubling the issue. I just deside that would be better to let to know in the current milestone tread.

**Comment by shalnoff** [comment]
Still doesn't work. (ver. 1.0-832)
Everything was unistalled and ~/.cofig/tox/ wiped before reinstallation
![this thin vertical white line is an icon](http://shalnoff.com/pics/tmp/tox_line.png)

**Comment by GrayHatter** [comment]
@shalnoff can you checkout #1007 and tell me what the tray get's resized to? There should be a debug line in the console

**Comment by shalnoff** [comment]
@GrayHatter 
trying with the last binary (1.0-842) from repo... unfortuately I see there no "Tray resized" message in terminal. I see "expose" message when window shows on click but nothing else (other irreleveant messages are there).

**Comment by perfect7gentleman** [comment]
XCFE - no icon
KDE4 - light grey icon

**Comment by roboman2444** [comment]
LXDE/lxpanel - All white icon.

**Comment by tachyonimpact** [comment]
I use i3wm and cannot use uTox as it won't produce a system tray icon still.

**Comment by GrayHatter** [comment]
@tachyonimpact I'm also using i3 and I do get a icon, it's just a white background. But it does appear, does your tray not show ANY icon, or is there a white square there?

**Comment by tachyonimpact** [comment]
@GrayHatter There's nothing at all in the tray for me. My uTox (Alpha) reports its version as "0.2.o". Even with the options "Close to Tray" and "Start in Tray" enabled, uTox on i3wm starts as a window and the process dies when the window is closed.

**Comment by GrayHatter** [comment]
you're over 500 commits behind. Where'd you get your version of µTox?

**Comment by tachyonimpact** [comment]
Oh wow, I feel silly. This version was included in the Voidlinux repo; someone should update that over there.

**Comment by shalnoff** [comment]
icon still doesn't work :( habitual tiny vertical stripe instead. 
taking packages form https://repo.tox.im/ nightly main

**Comment by GrayHatter** [comment]
@shalnoff what WM and tray?

**Comment by shalnoff** [comment]
> what WM and tray?

MATE Desktop Environment 1.4.0 + Compiz 0.9.7.8
I was trying to switch Compiz off. Without any success.

**Comment by akhilman** [comment]
MATE on Debian 8, Have 1 pixel vertical bar instead of tray icon.

**Comment by GrayHatter** [comment]
small update https://github.com/GrayHatter/utox/tree/lintray_bg

**Comment by GrayHatter** [comment]
Icon has been added, next up, a context menu. if you're still following this open this here  https://github.com/GrayHatter/uTox/issues
