### ISSUE TITLE
Denial of Service (DoS) receiving text

### ISSUE THREAD

**Issue by stqism** [notsecure/uTox#219]
Sending a user using uTox messages at a high rate of speed (do-able by a human still) causes uTox to freeze and CPU usage to skyrocket.

As a rate of speed humans can send packets a modern AMD PC shot up from 1% CPU usage to 25%, with a script the PC is rendered useless.

Attempted to reproduce this with a couple other clients and was unable, so it isn't a core issue.

**Comment by GrayHatter** [comment]
closed as stale, if I'm mistake, reopen this or tag me with detailed steps to reproduce
