### ISSUE TITLE
Support for VAD and noise cancellation

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#227]
Doing it in similar way to Toxic's would be nice

**Comment by XVilka** [comment]
looks like echo cancelling is implemented already by @irungentoo https://github.com/irungentoo/filter_audio/commit/5254f2d8002d8fae09f795410e43cebf17c4b126

**Comment by GrayHatter** [comment]
fixed

**Comment by zetok** [comment]
>fixed

Does µTox have VAD now?

**Comment by GrayHatter** [comment]
Closed as not a uTox problem. But it should be fixed in filter_audio soon too...

maybe?

**Comment by tsudoko** [comment]
Does VAD have anything to do with audio filtering?

**Comment by GrayHatter** [comment]
yeah, IIRC damo said he's trying to add voice detection to echo cancellation, and with that he's going to try to reject everything if the user isn't talking. Makes echo canceling easier and more accurate. But I'm not a sound guy so you'll have to ask him.
