### ISSUE TITLE
'drag & drop' file to µTox to send it doesn't work ( regression )

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#230]

**Comment by GrayHatter** [comment]
@zetok close this??

**Comment by zetok** [comment]
why?

**Comment by GrayHatter** [comment]
Because maybe it works now?

**Comment by zetok** [comment]
>maybe

What do you mean?

**Comment by GrayHatter** [comment]
@zetok does drag and drop still not work?

**Comment by zetok** [comment]
Yes, it still "didn't" work ~3 days ago, did something change in that matter?

**Comment by GrayHatter** [comment]
nope, I was just hoping it would automagicly fix itself. 

DND did work for you before right? If so, can you use git bisect and tell me what commit caused the breakage? (perhaps after backing up your savefiles!)

**Comment by GrayHatter** [comment]
stale issue, if you're still seeing this problem please reopen here https://github.com/GrayHatter/uTox/issues
