### ISSUE TITLE
Inconsistent behavior of the dropdown menu and the context menu

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#233]
Basically, the context menus require two clicks, the dropdown menus require one.
It would be more intuitive if you could just click once to get the list and either click on an item of the list or outside it to make it disappear.
However, keeping the current behaviour as an alternative option would also be beneficial for users who may prefer it that way. It's possible to do it without having to add any additional options in the settings, like in OS X or GTK+ applications.

**Comment by GrayHatter** [comment]
the way dropdowns are handled is because of how android tracks mouse movement...

either way they need some work

**Comment by GrayHatter** [comment]
@tsudoko I'll get to it when I can, but can you open this on my repo, I'd actually like to fix this
