### ISSUE TITLE
AV Break

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#248]
Remove a friend while having a video call (and audio call).

If you do that then it will confuse the whole programm.
- The next call after readding the friend will only be single side (only one gets video)
-  only one gets the call started info (the other one only sees the ringing message)
- and only one is able to cancel the call. (buttons are faulty)

**Comment by GrayHatter** [comment]
@towlie can you still make this happen?

**Comment by towlie** [comment]
It's still broken. When readding the friend you cannot call him anymore but he can call you.
So the one who deleted someone while calling is unable to do calls until you restart utox.

**Comment by towlie** [comment]
Same thing happens when doing this on qtox. @tux3

**Comment by towlie** [comment]
https://github.com/irungentoo/toxcore/commit/6f5d1a3b8e15a3d6feae2eec6a3cf28bdd53bce0
