### ISSUE TITLE
Ringtone ???

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#269]
Hello,

I have tried uTox, but unfortunately I am very very disappointed of its usability...
When the other party tries to call me, there is NOTHING !!! No ringtone, no big
blinking of the screen. Even if I have selected another contact, there is absolutely
no way to find out, that someone is trying to call me !!

Please kindly fix this issue, this is the main hiccup, if solved, I think the program
will become usable.

**Comment by Rhoarin** [comment]
No sounds on Ubuntu for incoming calls/messages (no tray icon as well).

Any fix?

**Comment by darkman088** [comment]
I am suffering the same, both under Win 7 and PC Linux. But one of my contacts confirmed, that he is hearing ringtones on his Win 7. We are using the same version.
Something's not right here... Please help us!
