### ISSUE TITLE
[Feature Requests] Add possibility to copy ToxID of users in my contact list

### ISSUE THREAD

**Issue by Nokta-strigo** [notsecure/uTox#303]
For example, if I have 2 friends in my contact list and I want to send ToxID of one of them to the other, so they can add each other to their contact lists.
This question was mentioned in https://github.com/notsecure/uTox/issues/282, but the discussion there have messed up.
By the way, is there any todo list on uTox?

**Comment by calimeroteknik** [comment]
Excuse me, but qTox does allow to copy the ToxID of a friend in order to give it to another friend.
It's the same feature we'd need here.
For now, I close µTox and open qTox to copy a friend's ID and send it to another friend.
