### ISSUE TITLE
An issue with upgrading from the AUR

### ISSUE THREAD

**Issue by GGMethos** [notsecure/uTox#304]
Cloning into bare repository '/tmp/yaourt-tmp-root/aur-utox-git/utox'...
remote: Counting objects: 2761, done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 2761 (delta 130), reused 109 (delta 47)
Receiving objects: 100% (2761/2761), 1.55 MiB | 682.00 KiB/s, done.
Resolving deltas: 100% (1858/1858), done.
Checking connectivity... done.
==> Validating source files with sha256sums...
    utox ... Skipped
==> Extracting sources...
  -> Creating working copy of uTox git repo...
Cloning into 'utox'...
done.
==> Starting pkgver()...
==> Updated version: utox-git 20140824-1
==> Starting build()...
==> Building...
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/AL  -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include  -g -pthread -std=gnu99 -o friend.o -c friend.c
In file included from friend.c:1:0:
main.h:143:1: error: unknown type name ‘Tox_Options’
 Tox_Options options;
 ^
Makefile:61: recipe for target 'friend.o' failed
make: *** [friend.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build utox-git.

**Comment by GrayHatter** [comment]
@GGMethos can you AUR utox-git now?

**Comment by GrayHatter** [comment]
closed as stale, reopen or tag me if you can make this happen on demand.
