### ISSUE TITLE
Segmentation fault on exit on OS X 10.9.4 (13E28), no list of audio output options

### ISSUE THREAD

**Issue by Nokta-strigo** [notsecure/uTox#309]
Terminal output:
`MacBook-Air-Apple:~ apple$ utox`
`Read 16 bytes (utox_save)`
`new tox object ipv6: 1 no_udp: 0 proxy: 0  0`
`Read 37088 bytes (tox_save)`
`Tox ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
`frame size: 960`
`desktop: 1440 878`
`Loaded font /Library/Fonts/Verdana.ttf 0 32 -6`
`Loaded font /Library/Fonts/Verdana Bold.ttf 0 32 -6`
`Input Device List:`
`Built-in Microphone`
`Loaded font /Library/Fonts/Verdana Bold.ttf 0 32 -6`
`Loaded font /Library/Fonts/Verdana.ttf 0 32 -6`
`Loaded font /Library/Fonts/Verdana.ttf 0 32 -6`
`Loaded font /Library/Fonts/Verdana.ttf 0 32 -6`
`expose`
`expose`
`Connected to DHT: 1`
`Friend Online/Offline (0): 1`
`Friend Name (0): AAAAA`
`Friend Status Message (0):  `
`Friend Userstatus (0): 0`
Then I press red cross, window closes and in terminal I get:
`Segmentation fault: 11`
It doesn't affect any functionality, since it happens on exit.
Installed uTox using Homebrew from [tox/tox](https://github.com/Tox/homebrew-tox) repository. Before installing uTox I had to install [XQuartz](xquartz.macosforge.org/landing/) (ver 2.7.7 2014-08-18)
Also there's no options shown when choosing audio output, but actually audio works fine (I can hear sound from build-in speakers). Video camera doesn't work, as it's written in https://github.com/notsecure/uTox/pull/128

**Comment by GrayHatter** [comment]
@Nokta-strigo is the latest version still segfaulting on exit?

**Comment by Nokta-strigo** [comment]
Tried to install it with homebrew, got an error:
> Cloning git://github.com/notsecure/uTox Updating
/Library/Caches/Homebrew/utox--git
==> Checking out branch master
 ==> clang -o /usr/local/Cellar/utox/HEAD/bin/utox -ltoxcore -ltoxav -ltoxdns -lr 
^
 util.c:647:13: error: no member named 'proxy_type' in 'Tox_Options' 
options.proxy_type = !!save->proxyenable;
 ~~~~~~~ ^
 5 errors generated.  

>READ THIS: http://git.io/brew-troubleshooting
 If reporting this issue please do so at (not Homebrew/homebrew): 
https://github.com/tox/homebrew-tox/issues'

**Comment by tsudoko** [comment]
Looks like outdated core

**Comment by Nokta-strigo** [comment]
@tsudoko thanks, that helped :-)
@GrayHatter Yes, it does. Now after pressing the cross I get:
>Saved data 
CHMOD: success 
Writing uTox Save :: 
Saved data
 CHMOD: success 
Segmentation fault: 11 
logout

**Comment by GrayHatter** [comment]
replaced with cocoa, thanks @stal888 

@Nokta-strigo if you still have any issues tag me and @stal888

**Comment by Nokta-strigo** [comment]
Sorry for not answering for a long time. I'll test it as soon as I get to Mac.
