### ISSUE TITLE
Massive lag in chat.

### ISSUE THREAD

**Issue by JasonBiggums** [notsecure/uTox#321]
version:win64-0.1.4.exe
os: windows 7 64-bit

When the chat receives a bunch of text, the client starts lagging, to the point where I can barely type messages out. Perhaps there should be an option to clear old chat messages from the buffer, like after 20-50 messages?

Video of the lag
a.pomf.se/navzzh.webm

**Comment by GrayHatter** [comment]
also #814

**Comment by GrayHatter** [comment]
stale, if still an issue, open on new repo
