### ISSUE TITLE
Video call display issue

### ISSUE THREAD

**Issue by JasonBiggums** [notsecure/uTox#323]
version:win64-0.1.4
os: windows 7 64-bit

The video call seems to shift between semi-decent quality and then quickly degrading back into the unreadable mosaic pattern

Image:
![](http://a.pomf.se/drhuft.png)

**Comment by GrayHatter** [comment]
@JasonBiggums seems like network lag. But either way: are you still having this issue?

**Comment by Diadlo** [comment]
My friend have the same bug on windows 7
![utox-inline](https://cloud.githubusercontent.com/assets/6306608/12309879/1d51c1ac-ba5e-11e5-935d-fe436f4a471d.png)

**Comment by GrayHatter** [comment]
you're on the wrong repo https://github.com/GrayHatter/uTox
