### ISSUE TITLE
Create ~/.config/tox directory if there's no one and show message on config file save error

### ISSUE THREAD

**Issue by Nokta-strigo** [notsecure/uTox#328]
Run into such problem on OS X: if there is no ~/.config directory, uTox neither creates it nor shows error message, just closes without saving config files; and the next time it loads old config files from current directory.

**Comment by GrayHatter** [comment]
@Nokta-strigo are you still having this issue?

**Comment by Nokta-strigo** [comment]
Yes, all the same.
BTW, 0.2.n - is the right version, isn't it?

**Comment by GrayHatter** [comment]
@Nokta-strigo yeah, that's the newest as of now, I'll see if I can fix this.

**Comment by GrayHatter** [comment]
@stal888 can I close this?

**Comment by stal888** [comment]
@GrayHatter yes
