### ISSUE TITLE
Buggy logging

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#337]
sent text to µTox:
```
ping
```
what was shown in log with UTF-8 encoding:
![2014-08-31 utox logging](https://cloud.githubusercontent.com/assets/3148759/4101609/91927408-30f8-11e4-987a-b873a1adf88a.png)

**Comment by zetok** [comment]
@GrayHatter why is this closed?

**Comment by GrayHatter** [comment]
Because I'm going to encrypt that data as soon as uTox gets encrypted profile support.

at that point it'll get a new extension. Either way it was closed for wontfix
