### ISSUE TITLE
Bug with drag and drop feature (Linux)

### ISSUE THREAD

**Issue by Jessexd** [notsecure/uTox#342]
![screenshot from 2014-08-31 16 16 11](https://cloud.githubusercontent.com/assets/8608136/4103253/c267a1fc-3152-11e4-8616-5e06233db2e1.png)
When I drag and drop files, the icon is left top-most on the screen without anyway of getting rid of it.

**Comment by kriswema** [comment]
It's been 4½ months and OP hasn't shown any activity since. I guess this can be closed.

**Comment by GrayHatter** [comment]
@irungentoo close?
