### ISSUE TITLE
Suggestion: Disable all notifications when Busy

### ISSUE THREAD

**Issue by reyaz006** [notsecure/uTox#343]
Tray notifications are quite annoying when I'm busy.

**Comment by GrayHatter** [comment]
@reyaz006 how would you like to mark yourself as busy?

**Comment by tsudoko** [comment]
@GrayHatter 
There's a red status icon for this. You have to click your status icon two times to enable it.

**Comment by GrayHatter** [comment]
fixed in grayhatter/utox
