### ISSUE TITLE
Bug: Empty tray icon under Windows XP

### ISSUE THREAD

**Issue by reyaz006** [notsecure/uTox#345]
Happened for me and 2 friends under XP. There is just an empty space instead of uTox icon.

Also, at least one friend of mine will NOT be happy if you fix this. He likes that as is.

I think it'll help to make it customizable with an .ico file. E.g. user simply drops a 'tray.ico' file near the executable, and uTox is using that as a tray icon.

**Comment by kriswema** [comment]
@reyaz006 Icon should show now? So it's fixed? Can be closed? @irungentoo
