### ISSUE TITLE
[Feature Request] Smilies

### ISSUE THREAD

**Issue by Fleshgrinder** [notsecure/uTox#349]
I searched the issues but couldn't find one for this more than necessary feature for any instant messenger. I'm sure this is low priority, but it's simply essential. Would be nice to have animated ones like in Skype and not some ugly static ones as found in most IMs today and in the past.

If I missed the original issue during my search simply close this with reference to the original issue.

**Comment by Ravenlord** [comment]
+1 for smilies

**Comment by Nsheppard01** [comment]
I like making text based emoticons, and hate it when they get turned into ugly gifs. Emoji are okay, but turning arbitrary text strings into pictures is dumb.

**Comment by GrayHatter** [comment]
@Nsheppard01 I agree with you on that one, text emoji > * I'll be sure to keep it that way

**Comment by GrayHatter** [comment]
dup, already open on new repo
