### ISSUE TITLE
uTox - Tox IDs missing after computer crashes

### ISSUE THREAD

**Issue by StorytellerKaji** [notsecure/uTox#355]
My 2 friends using uTox both had a similar problem today where their computer crashed (blue screen) and then when it rebooted, their tox saves/ID's were gone. They're using Windows 7 and Windows 8. This is the first time it's happened. Figured I'd let you know since this could be a rather annoying bug for people who don't or haven't been keeping backups of their Tox ID files. I don't have any details of what the blue screen errors were since they didn't take note, not expecting their Tox saves to be gone.

**Comment by GrayHatter** [comment]
this should be fixed now, tag me if I'm wrong
