### ISSUE TITLE
Problems with 0 byte inline images and crash if you want to save/view own inline image.

### ISSUE THREAD

**Issue by Fleshgrinder** [notsecure/uTox#358]
If we create inline images with the screenshot function nothing is actually there, the created PNG file simply has 0 bytes. I also wanted to “download” and open the file on my own machine, the program crashed.

Windows 7 x64

**Comment by GrayHatter** [comment]
@Fleshgrinder @lovetox can you still duplicate this issue?

**Comment by GrayHatter** [comment]
Stale, and duplicated else where
