### ISSUE TITLE
[features request] Add a possibility to rename a user

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#362]
Dear fellow tox and uTox developers,

thanks a lot for creating this wonderful and SECURE program! I would kindly ask you to implement one function, that is very important!
It will be very convenient to be able to rename users. For example, if I have a contact, who is my colleague from university, and he has set some gamer freak nickname for his game partners, I would like to see his real name in the contacts, instead of a nick, connected to a game that I don't know and I have never played!
Renaming contacts is a basic feature of ALL instant messaging software I know and it is hard to believe, that tox is not supporting it.

Many many thanks for your effort!

**Comment by GrayHatter** [comment]
dup of #190 coming eventually
