### ISSUE TITLE
Possible way to DoS µTox silently

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#366]
There's a possible way of DoS-ing µTox users.

Reproducible: Always

Steps to reproduce:
1. Start file transfer from client A to client B.
2. Client A pauses file transfer.
3. Client B goes offline and comes back online. (as in, is turned off and on by user)
4. Client A resumes file transfer.
5. Client B goes silently offline (no user notification, contacts in client's B window still seem to be online, client A correctly shows that client B has gone offline.

What happens:
Client B is DoS-ed, and user does not know about it in any way, since except for being unable to make video/audio calls and dropped network usage there are no other indicators of real problem.

What should happen:
Client B should work just fine, without going silently offline.

**Comment by GrayHatter** [comment]
This should be fixed in the newest API tag me if you can still make this happen...
