### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by NewEraCracker** [notsecure/uTox#370]
Hello,
I am running uTox on Windows and wondering if there is any way to disable the usage of AppData\Local as setting location and using own folder as the place where the settings are saved.

I tried copying the utox_save and tox_save to own dir but this still results in files being saved at AppData\Local.

Any ideas?

**Comment by muchweb** [comment]
+1 for storing files in the same directory by default (and adding an option to specify a path).

**Comment by mohamedkomalo** [comment]
@irungentoo 
like @darkman088 why utox can't be portable by default ? it would be nice if the download is just a zip file, the person can extract it anywhere he likes, and all the data are saved inside the folder.
if a person wants to update

**Comment by GrayHatter** [comment]
closed as fixed tag me if I missed something

**Comment by darkman088** [comment]
@GrayHatter - what exactly is the fix. I didn't see a consensus on some of the suggested solution. The --portable option is not a transparent solution, as it is not obvious from the interface. Thank you!

**Comment by fcore117** [comment]
At least it can be made portable somehow and i use it absolutely every day.
