### ISSUE TITLE
Ugly font rendering on linux

### ISSUE THREAD

**Issue by gez** [notsecure/uTox#377]
All the fonts in uTox for linux are rendered using a color subpixel rendering that looks quite bad on most screens (specially if the resolution is not very high).
That makes it look quite bad compared to the rest of the applications running on the same desktop or even uTox for windows.

Here's an example comparing uTox and Venom on the same Gnome desktop.
![utox-venom](https://cloud.githubusercontent.com/assets/441573/4176244/804040c6-35f9-11e4-81dc-d5bec4e7d92a.png)

**Comment by GrayHatter** [comment]
@gez is it still ugly?

**Comment by GrayHatter** [comment]
fixed according to my sources...
