### ISSUE TITLE
Groupchat: Need groupchats to survive closure of the client

### ISSUE THREAD

**Issue by marknoble** [notsecure/uTox#380]
Given a user joins a groupchat
When a user closes the client and opens it again
Then the user is still part of the groupchat

Note: It could be that the groupchat ceases to exist when all members are offline, but it'd be nice if the illusion of persistence were preserved by having it dynamically reconvene when more than one participant of a chat returns to online status.

**Comment by GrayHatter** [comment]
closed, the new groupchat API will close this
