### ISSUE TITLE
[Windows] uTox resets after restart

### ISSUE THREAD

**Issue by Kitu14** [notsecure/uTox#381]
uTox gets totally reset when I restart my PC : my username is replaced with "uTox user" and I lose all my friends that I have to add once again.

I'm running uTox on Windows 7 64-bits and I think I'm using the latest version of the program (since there is a new updater and it doesn't detect a newer version to download when I launch it).

**Comment by GrayHatter** [comment]
@Kitu14 are you still having this problem or any like it?

**Comment by Kitu14** [comment]
No problem anymore !

**Comment by GrayHatter** [comment]
@Kitu14 could you click that close button? Unless @irungentoo gets to it first?
