### ISSUE TITLE
Groupchat activity isn't shown on the list

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#388]
There should be a dot indicating if there are new messages. According to the mockup it should look like the one used for online contacts.

**Comment by Nsheppard01** [comment]
It would also be nice to be able to see if people in a groupchat are typing.

**Comment by GrayHatter** [comment]
I don't think toxcore supports that... Anyone know?

**Comment by Zanthas** [comment]
Over a year later and this is still an issue. Anyway we can get this fixed?

**Comment by Nsheppard01** [comment]
This is kind of annoying, I keep missing messages in groupchats because of it.

**Comment by GrayHatter** [comment]
I'll fix this one #1088 gets merged in

**Comment by aaannndddyyy** [comment]
#1088 has been merged some time ago .....

**Comment by GrayHatter** [comment]
@aaannndddyyy sorry to do this to you, but now it's gonna get pushed off for the new pending group chat API change that's coming down...

**Comment by aaannndddyyy** [comment]
@GrayHatter Oh, that is exciting!

**Comment by GrayHatter** [comment]
fixed in grayhatter/utox

**Comment by tsudoko** [comment]
Which branch?

**Comment by GrayHatter** [comment]
sorry, forgot to push, https://github.com/GrayHatter/uTox/tree/new_develop (temp branch until friday)
