### ISSUE TITLE
Export Tox ID

### ISSUE THREAD

**Issue by mokasin** [notsecure/uTox#396]
Is there a possibility to export the whole Identity (private + public key)?

Or at least, where is it saved on linux?

**Comment by xenohunter** [comment]
Sorry for necromancy, but I have the same question about Windows: which tox_save file is the right one? There are three of them: in ~/AppData/Local, in ~/AppData/Roaming, and the last one in the directory where utox_runner.exe is placed.

**Comment by GrayHatter** [comment]
@xenohunter should be AppData/Roaming/ check the last write time to be sure!

**Comment by xenohunter** [comment]
@GrayHatter thanks! Everything works now.
