### ISSUE TITLE
emoticons

### ISSUE THREAD

**Issue by cylgom** [notsecure/uTox#398]
This needs emoticons, so I made some. [Details here](http://cylgom.net/projects_details.php?id=11). They're licensed under WTFPL, if you don't want to credit me, I'm OK. In case you were wondering, it's true that I was inspired by skype emoticons, but I am the author of every single pixel in these things. 
This client is awesome,  keep it up !

**Comment by cylgom** [comment]
Hi, I just released a flat version of these. Download it [here](http://www.mediafire.com/download/89u793awkcwcwo4/toxic_clones_v2_flat.zip), and see [here](http://cylgom.net/projects_details.php?id=11) for details & preview.

**Comment by GrayHatter** [comment]
any chance you'll host these on GH?

**Comment by ElLamparto** [comment]
Nice work! Is there any possibility to make them less Skype-like? May be change colors (into µTox UI colors?)??

**Comment by fcore117** [comment]
Modern gray style? Would be easier to look and less Skype like, just a sample http://thumb7.shutterstock.com/display_pic_with_logo/756580/226695271/stock-vector-flat-simple-icons-modern-icons-for-mobile-interface-226695271.jpg

**Comment by cylgom** [comment]
@GrayHatter good idea, [here's the repo](https://github.com/cylgom/toxic-clones).
@ElLamparto Almost every smiley's head uses the same layer, so you can easily change the colors :)

**Comment by GrayHatter** [comment]
open and replaced by https://github.com/GrayHatter/uTox/issues/194
