### ISSUE TITLE
Clear Chat History

### ISSUE THREAD

**Issue by hyph3n** [notsecure/uTox#404]
We've been using the uTox for Windows client in the office lately so the team can keep in touch easily.  It would be great if you could right click in the chat window and have a "Clear history" option that would securely remove all previous messages from a given user. Currently, the right click options include "Copy" and "Copy (no names)".

**Comment by tsudoko** [comment]
Isn't that fixed now?

**Comment by GrayHatter** [comment]
you can right click on the friend in the friends list to remove history
