### ISSUE TITLE
[Windows] Lines are cleared by letters

### ISSUE THREAD

**Issue by Arkderce** [notsecure/uTox#415]
uTox has issue with polish letters "ą" and "ż". If you write some line like "Cześć" and you will add "ą" on end of it, like "Cześć ą" all words are cleared and you need to rewrite sentence, on other side, "ż" is clearing just one char before it.

**Comment by GrayHatter** [comment]
@Arkderce does this still exist?

**Comment by Arkderce** [comment]
Yes, it does. Reporting now from Win8.1 (last time I wrote here using win7).

**Comment by GrayHatter** [comment]
@Arkderce how do you enter the letters "ą" and "ż"?

**Comment by Arkderce** [comment]
By pressing right alt + a (z) on polish programmer keyboard.

**Comment by GrayHatter** [comment]
I think this is fixed, if not please reopen here https://github.com/GrayHatter/uTox/issues

I think I know what the issue is if it's still happening, reference this thread so I know that I changed the masking for keys a while back, when looking in to PgUp/Dn user switch
