### ISSUE TITLE
uTox not detected as a communications app on Windows

### ISSUE THREAD

**Issue by stqism** [notsecure/uTox#418]
Please use the audio session API in Windows for ToxAV, otherwise features like automatically adjusting the sound of other sources during calls does not work. 

![Image provided by the person complaining about this](https://cloud.githubusercontent.com/assets/2031258/4313830/069b51d4-3ed2-11e4-9c59-f1a2f06801cb.jpg)

Details on said audio session API:
http://msdn.microsoft.com/en-us/library/windows/desktop/dd371455(v=vs.85).aspx

**Comment by GrayHatter** [comment]
works for me
