### ISSUE TITLE
Idea - Keep screen awake during (voice) call

### ISSUE THREAD

**Issue by MasX** [notsecure/uTox#431]
It would be nice if the screen would not be allowed to go to the screensaver when one is making a voice call.

You guys are doing an awesome job with both uTox and Toxcore, keep it up!

**Comment by GrayHatter** [comment]
@MasX what OS?

**Comment by MasX** [comment]
@GrayHatter The latest linux mint debian edition. I don't know if the problem still exists, as I haven't used tox for a while on that OS.

**Comment by GrayHatter** [comment]
@MasX can you close this then, and reopen it if you have that issue again?
