### ISSUE TITLE
Copying chat message copies the sender name

### ISSUE THREAD

**Issue by mlmarenchino** [notsecure/uTox#445]
When I select a message when chatting when someone and copy it, even though the senders name is not selected, it is copied by default.  I had this problem when copying my friend's id.

After finding this, I realized that the right-click menu shows another possibility, "Copy (no names)". I think that this option should be the default one when using Ctrl+C shortcut.

**Comment by GrayHatter** [comment]
@mlmarenchino still an issue?

**Comment by GrayHatter** [comment]
Done any replaced by newer issue
