### ISSUE TITLE
Desktop sharing/chat window bug

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#447]
If you send a picture with size 1x1 pixel (Copy & Paste or by desktop sharing) then it will break the timestemp.  (Windows, did not test linux)

![desktopsharing](https://cloud.githubusercontent.com/assets/6986141/4365369/54ef6c7a-42ac-11e4-8fc6-4253ae83010c.jpg)

**Comment by towlie** [comment]
Easy way to reproduce: Click desktop sharing button and click 1x1 pixel to share.

**Comment by Doom032** [comment]
Tested on Linux, problem exists there too. The thing seems to be that when you send an image it puts in 2 timestamps, one at the top of the image and one at the bottom. Of course, if the image is tiny, they'll partially overlap. Best would be if only one timestamp was added for the image, I think.

**Comment by GrayHatter** [comment]
without looking, it's probably a timestamp for the message, and another for the image.

**Comment by GrayHatter** [comment]
fixed in https://github.com/grayhatter/utox
