### ISSUE TITLE
skype killed the im star

### ISSUE THREAD

**Issue by foo-bar-baz** [notsecure/uTox#450]
utox from updater for win7.
first run was fine but once i started skype the next run of utox was without sound output. comparing output sound device for utox and skype they use the same dev on the machine.

**Comment by GrayHatter** [comment]
@foo-bar-baz are you still having this issue?

if so can you describe the steps to reproduce it?

**Comment by foo-bar-baz** [comment]
On Feb 27  14:06 -0800, GrayHatter wrote:
> @foo-bar-baz are you still having this issue?

no, it seems to be fixed. although sound is still choppy; as if buffer gets
flushed (a second of no sound) and then sound comes back on again.

maybe we close this and open a new one for choppy sound?

**Comment by GrayHatter** [comment]
yeah, please and thankyou
