### ISSUE TITLE
Desktop Sharing Crash

### ISSUE THREAD

**Issue by karai17** [notsecure/uTox#451]
When I try to save a desktop share that I made, Tox crashes. If I try to save one that someone sent me, it works.

Windows 7 x86_64

**Comment by GrayHatter** [comment]
@karai17 can you still create this issue?

If so can you provide some steps to reproduce it?

**Comment by karai17** [comment]
This seems to work now in that it does save and does not crash, but there is a new issue where it does not open the file when you click "click to open". If you cancel sending a file, it also shows two tile stamps over top of each other.

![](http://puu.sh/gfteM/edb56304a5.png)

**Comment by GrayHatter** [comment]
closed as stale, if you can still make it happen open a new issue and tag me?
