### ISSUE TITLE
uTox unable to find my webcam

### ISSUE THREAD

**Issue by karai17** [notsecure/uTox#454]
I am using a PSEye webcam with a custom Windows driver. Both Skype and Hangouts are able to pick it up just fine, uTox seems unable to find it.

**Comment by agilob** [comment]
It's a windows-only issue.

**Comment by GrayHatter** [comment]
@karai17 are you still unable to use your PSEye?

**Comment by karai17** [comment]
Yeah, it's still not being recognized.

**Comment by GrayHatter** [comment]
`ls /dev/vid*`?

**Comment by karai17** [comment]
Windows.

**Comment by Draako** [comment]
@GrayHatter: Nowadays you need pay for Windows drivers that used to be free (in case you want to look into them, I can provide them to you).

**Comment by karai17** [comment]
I am using the following driver:

https://codelaboratories.com/products/eye/driver/

**Comment by GrayHatter** [comment]
stale, open on new repo if you still care about this issue
