### ISSUE TITLE
Sharing desktop as video has really bad encoding

### ISSUE THREAD

**Issue by karai17** [notsecure/uTox#455]
I tried the "share desktop" option in my video output settings, as did my chat partner, and both of of our desktop streams looked like very corrupt video encodes. Lots of macroblocks and junk, basically unusable. That being said, it did "work", so that's definitely a start.

**Comment by GrayHatter** [comment]
@karai17 can you still create this issue?

If so can you provide a picture of what you mean?

**Comment by karai17** [comment]
![](http://puu.sh/gfsCb/677e524413.png)

![](http://puu.sh/gfsD6/24895b2931.png)

![](http://puu.sh/gfsGL/5f4f7e88fe.png)

**Comment by GrayHatter** [comment]
@irungentoo is this just bad core encoding, or is utox chokeing on the webcam?

**Comment by irungentoo** [comment]
that's core most likely.

**Comment by GrayHatter** [comment]
@karai17 did you notice any kind of audio distortion, or network lag?

Also, can you try the newest uTox on both sides and see if it's still a problem? (Make sure you're on a new api version too)

**Comment by karai17** [comment]
Audio was fine, higher bitrate than Skype so it sounded quite nice. No notable lag. I can give it a try later.

**Comment by GrayHatter** [comment]
closed as stale
