### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [notsecure/uTox#458]
I suggest to reuse a higher level build system than [your current make file](https://github.com/notsecure/uTox/blob/fdb7435ad90957ebd608744b78a963b0caecc92e/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by GrayHatter** [comment]
closed as stale, please reopen or tag me if you're willing to add a PR to this
