### ISSUE TITLE
uTox doesn't support avatars

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#510]
Avatars are already in the core and uTox supports displaying PNGs, so it shouldn't be hard to implement.

**Comment by Doom032** [comment]
I've been working on this for a while, out of wanting avatars myself too. My local version now has all avatar features working(setting avatar with file chooser, unsetting avatar, drawing avatar in UI, getting avatars from friends, saving avatars on disk, etc.) but I'm getting crashes and bugs on the windows build, so I'll be fixing those and then I'll send a pull request

**Comment by Aranad** [comment]
Awesome thanks! looking forward to seeing it :-)
