### ISSUE TITLE
Bug: random file name when sending a file with äöüÄÖÜß in its name

### ISSUE THREAD

**Issue by jf99** [notsecure/uTox#517]
1. Give a file a name containing äöüÄÖÜß.
2. Send this file to a friend via uTox.
3. Your friend won't see the correct file name.

**Comment by GrayHatter** [comment]
for anyone looking to fix this, there's a number of problems with transaltion of windows native and UTF-7/8

required reading https://msdn.microsoft.com/en-us/library/windows/desktop/dd374081%28v=vs.85%29.aspx
