### ISSUE TITLE
Push-to-talk

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#526]
*(reposting because the original reporter's account(s) got locked)*

**Comment by Vioner** [comment]
Could anyone implement this feature please? Maybe at least a shortcut for mute/unmute? Tox is the best possible voice chat software IMO - it uses just 3-4 MB of my RAM when I play with 4 friends using groupchat. It's way better then Skype and TeamSpeak (in both cases, the resource usage, and in 2nd case the sound quality). It lacks just the push-to-talk feature.

**Comment by Th0masR0ss** [comment]
Well, uTox still doesn't have a mute button, so until #287 is done, this pretty much can't be done.

**Comment by GrayHatter** [comment]
done
