### ISSUE TITLE
Textbox issues

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#527]
*(reposting because the original reporter's account(s) got locked)*
 1. [x] ctrl+v doesn't work to its full extent. There is always place for 1 more character, but ctrl+v doesn't do anything. http://a.pomf.se/kdfyme.webm *(can't reproduce)*
 2. [ ] Scrollbar gets so small you can't see or select it. http://a.pomf.se/bqbtan.webm
 3. [ ] The | in the textbox doesn't blink
 4. [x] http://a.pomf.se/knrspu.webm *(can't reproduce)*

**Comment by GrayHatter** [comment]
because of the way uTox redraws the screen, I don't think we want to make the text cursor bink, and I'm going to need more information about the small scroll bar...
