### ISSUE TITLE
Message splitting and gluing for a seamless experience, as if there wasn't any message length limit

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#529]
*(reposting because the original reporter's account(s) got locked)*

**Comment by GrayHatter** [comment]
Closed for lack of information, please reopen if you can describe this a little better

**Comment by tsudoko** [comment]
When you type a long enough message, it gets split, what the person meant is that uTox should be able to make those split messages look like a single one. I don't know if it's even possible to do right now, though; is there even a way to determine whether a received message was split?

**Comment by GrayHatter** [comment]
I understand the reason for this, but I don't really think it's crucial enough to warrant fixing...
