### ISSUE TITLE
Inconsistency when pasting text

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#534]
*(reposting because the original reporter's account(s) got locked)*
If you ctrl+v, the text cursor (caret) is put on the end of the pasted string.
If you middle click, the pasted string is highlighted.
I believe middle clicking should behave as ctrl+v currently does (paste and put the caret on the end of the string, without highlighting it)

**Comment by GrayHatter** [comment]
@tsudoko can you provide a video of the problem and reopen if you still care about this?

**Comment by tsudoko** [comment]
Well, I don't have a working mouse right now, so I can't even reproduce this. If someone cares, they should respond here.

**Comment by GrayHatter** [comment]
if you do care make sure you tag me too!
