### ISSUE TITLE
Custom DPI

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#544]
*(reposting because the original reporter's account(s) got locked)*
Currently we can only choose a DPI between 50% and 250% (and multiples of 50, at that).
Unrestricted DPI choice would be much better
 Also, it would be nice to have a finer tuning (different DPI settings for buttons and text, for example)

**Comment by GrayHatter** [comment]
this would be trivial if someone adds a new dropdown type that can convert itself to an edit type on selection of the custom entry

and would allow for many more options for all of the settings.

**Comment by GrayHatter** [comment]
done
