### ISSUE TITLE
File dialog is opened below uTox window

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/uTox#546]
Gentoo GNU/Linux with KDE 4.12.5. When starting a new file transfer, or choosing a location to save a file, the file dialog is opened below the uTox window.

**Comment by GrayHatter** [comment]
closed as fixed, works for me, if you need to re-open and provide more information

**Comment by TheLastProject** [comment]
It worked the first time, but after resizing the window it will consistently open behind the window each time the file transfer button is clicked.

KDE 4.14.3 by now.

**Comment by GrayHatter** [comment]
what window manager are you using?

**Comment by TheLastProject** [comment]
Kwin.

**Comment by GrayHatter** [comment]
should be fixed, if not open on new repo
