### ISSUE TITLE
uTox automatically accepts group invites without asking

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/uTox#548]
When being invited into a group chat, uTox automatically accepts an invite. It should ask the user if they want to join the groupchat first.

**Comment by Doom032** [comment]
This can be abused by instead of inviting someone to voice chat, inviting them to group chat and then using voice. The user will hear the other's audio suddenly without accepting anything.

**Comment by GrayHatter** [comment]
wontfix until new groupchats
