### ISSUE TITLE
uTox removes friends without confirmation

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/uTox#551]
Because removing friends is a destructive operation that cannot be undone, uTox should confirm that, when right-clicking and choosing "Remove", the user is sure they want to remove said friend.

**Comment by GrayHatter** [comment]
I tend to agree with AlexDaniel on this one, it's a mistake that I suspect a user will only make once...

**Comment by tsudoko** [comment]
Well, I, for one, have removed filebot several times because I mistook it for a groupchat I wanted to unmute. But that might've been just me.

**Comment by AlexDaniel** [comment]
Well, if there is similar functionality that looks like remove button then it is a whole different story.
Maybe by making the Remove button **red** it will eliminate even the slightest chance to misclick it. Having other options in a dropdown requires the confirmation window though.

**Comment by GrayHatter** [comment]
@tsudoko do you want to try @AlexDaniel's suggestion? you wrote the code on color changing...
