### ISSUE TITLE
Call and other event notifications, iteration N.

### ISSUE THREAD

**Issue by intelfx** [notsecure/uTox#552]
This is just another iteration of questions about notifications. This is all Linux-specific, of course.

There is currently code which implements notifications via `org.freedesktop.Notifications` dbus interface. However, at least in KDE this is suboptimal, because reaction to such events cannot be configured and they are always handled by just showing a popup (no sound, etc). Events can be configured when they are sent via `org.kde.KNotify` interface and if the application ships a .desktop file containing descriptions of its events.

So, if we add a .desktop file and implement sending notifications to `org.kde.KNotify` if such interface is present on the bus, uTox <-> KDE usability will substantially improve. I am actually willing to write code, and the only question is: will you (the upstream) accept KDE-specific code? (It will not add any dependencies.)

**Comment by GrayHatter** [comment]
closed as stale
