### ISSUE TITLE
Some sort of indication the day has changed in the chat

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#555]

**Comment by GrayHatter** [comment]
@tsudoko do you want a separator for multiple days? Or a single separator for each day?

eg

```
--- Monday 01
Me: Lorum ispum dolar
You: Sit emmet notar
--- Tuesday 02 ---
--- Wednesday 03 ---
--- Thursday 04---
--- Friday 05 ---
Me: finally responds

or 

--- Monday 01
Me: Lorum ispum dolar
You: Sit emmet notar
--- Friday 05 ---
Me: finally responds
```

**Comment by kriswema** [comment]
I think it would be a bit tidier if only days that actually had activity would show up. It's pretty obvious that there wasn't any message from Tuesday 02 to Thursday 04 when you leave them out.

**Comment by tsudoko** [comment]
I agree with @kriswema

**Comment by Doom032** [comment]
In Steam, it adds a date whenever someone writes a message in a chat where the last message was from the previous day or before. I think that would be best, and not too hard to implement.

**Comment by GrayHatter** [comment]
@Doom032 do you want to take this on?
