### ISSUE TITLE
Broken audio during calls

### ISSUE THREAD

**Issue by shugo589** [notsecure/uTox#559]
Randomly I get broken audio when I attempt to call someone or answer a call from someone. The person can hear me, but I cannot hear them, only loud corrupt audio. It happens from the beginning of the call. I'm running win64-0.1.8. I have had this issue since 1.5 or something like that. I can not isolate the issue. It happens randomly and has occurred trying to tox with people on uTox for mac and uTox for windows. Here is a sample of the corrupt audio I get:
http://vocaroo.com/i/s0xRLlvG60Cg

It sounds like I accidentally recorded my mic picking up the audio from my headset several inches away. It is extremely loud anyway, so you get the picture.

**Comment by GrayHatter** [comment]
closed as stale, @shugo589 please reopen this and/or tag me if you can still make this happen
