### ISSUE TITLE
Suggestion: Offline messaging

### ISSUE THREAD

**Issue by JsfN** [notsecure/uTox#578]
It might be good to have the option for offline messaging to your contacts on Tox. It's happened pretty often to me that in the middle of writing a message my friend goes offline due to bad connection or such and the message I want to send isn't able to send until that contact appears online again.

**Comment by bitcard** [comment]
DHT store extension can support the offline message, it support put/get data limit size 1k, please visit http://libtorrent.org/dht_store.html
