### ISSUE TITLE
Chat messages disappears

### ISSUE THREAD

**Issue by JsfN** [notsecure/uTox#579]
Sometimes when I'm chatting with someone on uTox my messages aren't going through. I can still receive messages from the contact I'm chatting with but mine just disappear into thin air. Usually disappears after restart but the problem appears frequently.
No message or anything saying that the message couldn't be delivered or such, it just disappears.

**Comment by GrayHatter** [comment]
closed as stale, @JsfN reopen and or tag me if you can still make this happen and can provide some more information
