### ISSUE TITLE
Videochatt crashes  

### ISSUE THREAD

**Issue by ViktorFerm** [notsecure/uTox#583]
I have noticed that after useing the videochatt for a period of time it crashes. After some time it started to get on my nerves so i started to write down the timestamps of the crashes. I did this during a session around 2 hours and this is the results. 

09.36 Start 

09.44 Crash

09.45 Start 

09.54 Crash

09.56 Start 

10.18 Crash, Only user two.

10.19 Start 

10.33 Crash, Only user one 

10.37 Start 

10.43 Crash

10.45 Start 

10.53 Crash, Only user one 

10.54 Start 

11.03 Crash, Only user one 

11.04 Start 

11.14 Crash

11.16 Start 

11.23 Crash, Only user one 

11.31 Start 

11.38 Crash, Only user one

**Comment by GrayHatter** [comment]
@ViktorFerm if you can still make it happen re-open this and tag me; 

I also need to know you OS and version, and utox version
