### ISSUE TITLE
uTox displays name changes stupidly

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/uTox#584]
![snapshot42](https://cloud.githubusercontent.com/assets/1885159/4539268/101c2584-4dfb-11e4-84fe-5de52f74b6cb.png)
This way of displaying name changes made it look as if the contact actually sent this as a message. I propose it being displayed with a different colour/style and without the nickname on the left, as if it's a "system message". Say:
![utox_name_idea](https://cloud.githubusercontent.com/assets/1885159/4539290/601bbb8a-4dfb-11e4-990e-49eca35c8ba8.png)
(I'm not asking for this exact colour choice, this is just an example to make my point clearer)

**Comment by GrayHatter** [comment]
blocked by messages.c refactor, move to new repo

**Comment by GrayHatter** [comment]
I think this is fixed, if not please reopen here https://github.com/GrayHatter/uTox/issues
