### ISSUE TITLE
Screenshoot green button in chat uploading "inline.png" file in attach every time it pressed even screenshoot file is 0px, and cannot abort screenshoting.

### ISSUE THREAD

**Issue by Corak667** [notsecure/uTox#596]
Hi there!
Trying uTox. Found some bug (or a feature):
![6042747 1](https://cloud.githubusercontent.com/assets/7928889/4601685/eb890d0e-5110-11e4-8a0c-ba9f33b6e55d.png)
When I pressing some green button in bottom-right it blackouts the screen (some 50% transparency). When I press it again - appearing some attached file "inline.png" - again and again.
Strange. 
Ah. Now I Understood NOW. It's a screenshoot feature. But there is no option to Abort screeshooting, It sends zero file every time even I just press mouse. So request is for aborting the screenshoot by esc key or not sending file if it's 0px.

**Comment by GrayHatter** [comment]
fixed in grayhatter/utox
