### ISSUE TITLE
Screenshot button should be moved

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/uTox#603]
The screenshot button is located in a stupid location, causing new users to often confuse it with a send button.

See censored chat with new user, first message is mine, inline image is other user's first reply.
![utox_button](https://cloud.githubusercontent.com/assets/1885159/4606112/f9365854-520e-11e4-9ca5-fc7d240c010a.png)

**Comment by GrayHatter** [comment]
@TheLastProject there's now a send button, so I'm going to close this.

feel free to re-open it if you can suggest a better place
