### ISSUE TITLE
Mark user as yellow 'away' after configurable amount of time of inactivity

### ISSUE THREAD

**Issue by LapFox** [notsecure/uTox#604]
Defined as mouse movement or keystrokes on the host computer.

**Comment by GrayHatter** [comment]
@tsudoko do you want to take this one on? should be simple enough...

**Comment by GrayHatter** [comment]
@tsudoko in reference to #1026 you said you don't know how to detect if the user is idle?

you can have MotionNotify on xlib/event.c:107 and KeyPress on xlib/event.c:266 both call your update function. then hook into one of the threads in tox.c to check if it's been >5m from the last time an update function was called...

**Comment by GrayHatter** [comment]
this is a good idea, please move to new repo
