### ISSUE TITLE
Make urls in status message clickable.

### ISSUE THREAD

**Issue by jf99** [notsecure/uTox#608]
Currently it's not possible to open URLs by clicking them in your friends status messages.

**Comment by GrayHatter** [comment]
I'm with darkman on this one, so I'm closing as no, you can re-open if you can get someone else to agree with you that you need this feature.

**Comment by kriswema** [comment]
I think it's a feature that shouldn't be left out. If you don't like people who put URLs into their status texts, that's your choice in friends. I personally don't mind, and apparently there are people who enjoy putting URLs into their status texts. I don't see a reason not to implement this.

**Comment by aaannndddyyy** [comment]
Why do you want to restrict the way people can use the program? Why should they have to type it if they could as well copy paste it? Doesn't make sense to me. Not just links, but especially those.

**Comment by darkman088** [comment]
You are  not completely wrong, but there are a few VERY BASIC features like setting a custom ringtone, renaming users and emoticons, just to name a few... Hence I would rather kindly encourage the great developers of uTox to focus on implementing those ones. Afterwards the community would be fully open to your URL suggestions. Thanks for your understanding!

**Comment by aaannndddyyy** [comment]
@darkman088 Nobody said it should be a top priority. But copy pasting is something very basic and essential, and should simply work. Not only for URL's but any kind of text. I agree though that other features are much more important now. However, that doesn't mean utox should never support copy-paste.
