### ISSUE TITLE
Ability to spool chat messages to offline contact

### ISSUE THREAD

**Issue by myroslav** [notsecure/uTox#609]
If contact is offline, uTox does not allow sending messages (pane controls are completely disabled). It would be great to be able to spool messages in tox profile and deliver them as soon as both tox clients are online (sending and receiving party).

This feature would not be necessary if toxcore supported storage of undelivered messages in DHT, but until now this would be responsibility of client.

**Comment by GrayHatter** [comment]
closed as dup
