### ISSUE TITLE
Initialisation webcam under Debian

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#616]
After Debian reboot, uTox video test shows an empty window.
To fix this, I have to:

- quit uTox,
- run vlc v4l2:///dev/video0
- quit vlc,
- restart uTox

At this point, the video test works fine.

**Comment by GrayHatter** [comment]
This is really strange @ElLamparto does is still do this?

**Comment by ElLamparto** [comment]
Last time it appeared about 2 weeks ago (I do not reboot Debian too often).
Please keep the bug open - I shall update it after test.

**Comment by ElLamparto** [comment]
It still does not work, tested on 2 machines with Debian Stable with webcams Philips SPC 1000NC and µTox 0.2.n.
Most likely some camera initialization is missing.

**Comment by GrayHatter** [comment]
stale, please move to new repo if still an issue
