### ISSUE TITLE
Device selection settings lost after quitting uTox

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#617]
Also the combo boxes are behaving strangely. Normally a click should display a dropdown list, which should be visible until a selection is made (or the control looses focus).

In uTox, the left mouse button must be kept depressed until a selection is made, otherwise the list dissapears.

**Comment by GrayHatter** [comment]
per #701 @irungentoo can you make it do it for video too?

**Comment by ElLamparto** [comment]
Device selection settings are saved all right. As for the combo box behaviour, I don't care.
