### ISSUE TITLE
uTox freezes for 15 seconds at audio test

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#618]
Windows7 32bit.
After uTox start, uTox freezes for 15 seconds at audio test. Then the audio test works fine.
It happens only once  (after every Windows reboot).

It only happens when the Audio Output Device is an USB headset.

**Comment by GrayHatter** [comment]
@ElLamparto does it still do this?

**Comment by ElLamparto** [comment]
No, it has been fixed.
