### ISSUE TITLE
uTox is always one action behind

### ISSUE THREAD

**Issue by dcharles525** [notsecure/uTox#619]
When I click on the status icon,its one status behind, when I type its one character behind, this has been going on for months and I had be a previous issue but its seem to have gotten worse.

**Comment by GrayHatter** [comment]
@dcharles525 can you try the newest version and tell me if it still does this?

**Comment by dcharles525** [comment]
@GrayHatter I can't seem to reproduce it anymore, will reopen if there is any issues.
