### ISSUE TITLE
Unstable working version 0.18-171 

### ISSUE THREAD

**Issue by Non77** [notsecure/uTox#622]
Version utox-0.18-171.i386 for Linux periodically freezes, unfortunately.
Previous version uTox 0.18.70 works opposite very stable.

**Comment by GrayHatter** [comment]
@Non77 is uTox still not working on XP?

**Comment by nachfuellbar** [comment]
@GrayHatter even if this wouldn't work on win xp; would you really support an operating system which isn't supported by its producer? (almost one year now)

**Comment by GrayHatter** [comment]
per irungentoo: there's more people on WinXP than Win8, or than every other non windows OS combined.

**Comment by GrayHatter** [comment]
Stale
