### ISSUE TITLE
A new call invite is sent if two people try end the call at the same time.

### ISSUE THREAD

**Issue by bob3434** [notsecure/uTox#625]
This happens when one users tries to press the "end call" button, however the button changes in to the  "start call" button right as they try to click it because because the other user has already ended the call. The result it that the slower user accidentally sends a new call invite.

Perhaps there needs to be a delay between the time a call ends and when the call button becomes active again since uTox uses the same button to end and start a call. Or maybe use a separate buttons for starting and ending calls.

**Comment by GrayHatter** [comment]
@tsudoko this would be a trivial fix, set the button as disabled when the call ends, and then set it as enabled on the next mouse over, or on the next mouse leave.

The code for this already exists in your latest PR

**Comment by GrayHatter** [comment]
I'm going to close this, as it should be much less common with the new ToxAV, but if you still see this please reopen this issue https://github.com/grayhatter/utox
