### ISSUE TITLE
uTox opens the input video device exclusively

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#628]
uTox opens the input video device in a way, that no other applications can access a webcam when uTox is running. It is not correct.

By contrast, the Input Audio Device is accessible at all times, what is correct.

**Comment by ElLamparto** [comment]
@GrayHatter, it occur always when µTox is running, but as I said, I begun liking that bug...

**Comment by tachyonimpact** [comment]
I am also having this issue with uTox 0.3.2. uTox grabs /dev/video0 even though the webcam isn't being used, and then locks it so nothing else can use it.

**Comment by cebe** [comment]
I have submitted a PR that should fix this. Tested on Linux only but should have the same effect on Windows as it only touches the OS independent API.

**Comment by cebe** [comment]
@ElLamparto @seisatsu @akhilman anyone of you want to try out my fix (https://github.com/GrayHatter/uTox/issues/52) and confirm it solves the issue?

**Comment by akhilman** [comment]
@cebe your branch do-not-block-unused-video-device do not hogs video input and closes it after call.
But still hogs audio output and do not closes audio input after remote side ends call.

**Comment by cebe** [comment]
I know, this issue was about video only. I can look into audio as well after video is merged.
