### ISSUE TITLE
Suggestion: Apply to the tails distribution!

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#632]
Hi guys,

I think that tox is so COOL, that it NEEDS to be included in the tails Linux distribution, which is entirely security-oriented. I had it checked out and they have absolutely no application for voice calls. They just have Pidgin for OTR chats. Have you thought about applying for that ?

**Comment by GrayHatter** [comment]
Closed as stale, if you still really want this submit a PR that allows a tails package maintainer to quickly do this
