### ISSUE TITLE
Win7 32bit, no audio unless an USB microphone/speaker used.

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#633]
In the settings I have:

IN: Microphone (Realtek High Definition Audio)
OUT: Speakers (Realtek High Definition Audio)

In uTox, audio does not work in either way (Skype with those settings works fine)

When I connect an USB handset (and change the settings accordingly), uTox audio works.

**Comment by GrayHatter** [comment]
@ElLamparto is this still a problem in the latest version?

**Comment by ElLamparto** [comment]
No, it has been fixed recently.
