### ISSUE TITLE
Waiting to pickup duration

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#634]
Hello,

currently, when initiating a voice call with uTox, the call keeps ringing just for a very short time (maybe around 10 seconds). I would kindly like to ask you, whether it would be possible to increase this time.
As stated here:

https://github.com/irungentoo/toxcore/issues/1130

It is a client issue, hence I am opening a new issue both for uTox and qTox. Many thanks!

**Comment by darkman088** [comment]
No update since 8 MONTHS ????????????????

**Comment by GrayHatter** [comment]
@darkman088 this will be changed once I finish porting utox over to the new toxav api.

**Comment by darkman088** [comment]
OK, but can you please kindly provide some estimation (I don't want any promises or commitments), just a date which you see the most realistic for now, just to have an idea ;-) Many thanks !!

**Comment by GrayHatter** [comment]
no idea, could be tonight, could be friday night, could be next friday night, could be months.

This fix will depend on the new toxav api getting released, which will require more than just utox being ready. So once I fix this if you want to use it before the toxcore api gets pushed you'll have to recompile  toxcore from the new toxav_api branch, and then utox.

**Comment by darkman088** [comment]
Thank you, it's not that urgent, I can wait. Just kindly post an update, when done.
Many thanks in advance and keep up the good work!

**Comment by GrayHatter** [comment]
audio works... mostly

**Comment by GrayHatter** [comment]
fixed
