### ISSUE TITLE
Ending the video drops the call as well

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#636]
Hello,

I have been testing video calls and noticed, that if I try to switch off the video, it drops the call as well. Would it please be possible to be able to just switch the video on and off, while preserving the call itself ? Many thanks!

**Comment by darkman088** [comment]
Hello, what is the status of this one ? I see that more than a month has passed and... nothing...

**Comment by GrayHatter** [comment]
@darkman088 it's on the radar, and will be taken care of ```eventually```.  But no one has jumped into A/V networking code yet. I assume someone will soon, but I don't know who.

**Comment by GrayHatter** [comment]
I think this is fixed, otherwise https://github.com/GrayHatter/uTox/issues

**Comment by darkman088** [comment]
Thanks, I will give it a try with the newest version available :-)
