### ISSUE TITLE
[Request] Add option to send messages with Ctrl+Enter keys

### ISSUE THREAD

**Issue by xDShot** [notsecure/uTox#637]
I usually use this key combination to send messages in other programs like Steam, so it would be more comfortable for me if this would be implemented in uTox.

**Comment by GrayHatter** [comment]
this was just changed that <kbd>ctrl+enter</kbd> is just a new line, and because that's what **most** apps do with it, I think is should be left as it is now, unless you can think of a better argument?

**Comment by v2e** [comment]
In most cases I use "Shift+Enter" for the new line, and "Enter" and/or "Ctrl+Enter" for sending. Isn't it better?
