### ISSUE TITLE
way to easily add friends to groupchat

### ISSUE THREAD

**Issue by aaannndddyyy** [notsecure/uTox#639]
drag and drop is fine and easy and could remain in place but as the list gets longer it means you need to reorganize your friend ordering in order to get the peer down below to the group chat, or pull the group chat up. but both ways are not very convenient.

**Comment by GrayHatter** [comment]
new group chats coming, maybe this will be fixed then

**Comment by aaannndddyyy** [comment]
This is purely a user interface issue. How will a new groupchat implementation in toxcore change that?

**Comment by GrayHatter** [comment]
must have been a touch of ADD when I closed this... not really sure what I was thinking.

**Comment by aaannndddyyy** [comment]
No problem, it can happen. You have a lot of issues to keep track of, and as groupchats were mentioned, closing was a likely action...

**Comment by aaannndddyyy** [comment]
Will bring to the new repo....
