### ISSUE TITLE
Direct connects with ipv6 or ipv4?

### ISSUE THREAD

**Issue by dtaht** [notsecure/uTox#645]
In doing a little testing of utox on linux today, we were puzzled by the behavior in crossing the campus,
where we have two legit inside-the-nat ipv4 addresses on different subnets, and also fully routable ipv6 addresses. In both cases, the traffic ended up exiting the campus network and falling back to ipv4 to do so.

From looking at the code for a bit, it does look like the possibility exists for a non-legit ipv6 address to be advertised, but it wasn't clear how it was acquired. The ideal behavior (from my standpoint) was for it to select a privacy ipv6 address and try p2p communication on that...

**Comment by GrayHatter** [comment]
@dtaht can you offer a bit more infomation on this one? I.e. what you wanted to happen, what really happened, why the way you want is better?

**Comment by GrayHatter** [comment]
Stale, and probably a toxcore issue, you should submit this there
