### ISSUE TITLE
Restoring friend trust after tox_save restore from backup

### ISSUE THREAD

**Issue by myroslav** [notsecure/uTox#647]
After loosing the Tox data save file (see #646) the older data save file restored from backup, but it is lacking some of the friends that were added since that time.

What is correct procedure to restore friends back into the contact list? It look like I have to resend friend requests to all my missing contacts, or they have to remove me from their contact lists and send friend request to me again, since I'm offline for them.

Any other tips are welcome.

**Comment by GrayHatter** [comment]
I can't think of a solution that doesn't end in a security risk, either way losing your tox save should be fixed in master right now
