### ISSUE TITLE
DNS requests leak

### ISSUE THREAD

**Issue by Jookia** [notsecure/uTox#655]
When querying for entries using uTox, it goes through the system's DNS resolver rather than using the proxy. This also means onion services can't be queried, and will be sent to your DNS/ISP.

Also, when querying entries that don't have an '@' symbol, instead of rejecting the malformed input, the contents are sent to uTox servers. This leaks whatever's in the box.

**Comment by GrayHatter** [comment]
@irungentoo this is seems like a real security problem. Is this a toxcore or uTox issue?

**Comment by Jookia** [comment]
It's a fundamental flaw in how Tox DNS works and how proxies can't handle it. So it's best to just turn it off in uTox since that's where the actual DNS requests are performed.

**Comment by GrayHatter** [comment]
fixed in grayhatter/uTox devel branch
