### ISSUE TITLE
Two bugs and one suggestion

### ISSUE THREAD

**Issue by Nordic89** [notsecure/uTox#656]
1. Bug:
When you try to add somebody and copy their tox id into the field, a space is always added at the end, causing the "Invalid Tox ID" Error when pressing "Add".

2. Bug:
The "Audio Input Device" is being changed back to the default value after restarting the program. The setting does not persist.

Suggestion:
My webcam allows me to set the output to H264, but unfortunately that does not work with utox. If I set it to H264 the webcam only displays a green screen. It would be nice if support for H264 could be added.

**Comment by GrayHatter** [comment]
bug 2 is a dup of #617 

@irungentoo thoughts on the suggestion? would that be something trivial or super complicated? There was a request to be able to stream video files elsewhere , that might be a cool feature to add if this is something we can support?

**Comment by GrayHatter** [comment]
@Nordic89 I'm going to close this one because both bugs are done. If you really want h.264 support create a new issue and tag me
