### ISSUE TITLE
Filetransfer issue - filename longer than 64 characters is cut off

### ISSUE THREAD

**Issue by LittleVulpix** [notsecure/uTox#657]
#90 , basically I created a screenshot in MPC-HC and wanted to send it to a friend - and he was telling me that he cannot open it in anything... and by trial and error we found out that names longer than 64 characters are chopped off.

Can we have either

a) longer filename support (like you would have in windows/linux by default)

or

b) warning that the filename length has exceeded the limit? That way we'll at least know why things happened the way they did.

Thanks!

**Comment by GrayHatter** [comment]
@LittleVulpix this should be fixed with the new api, can you test it out and see if this bug still exists?

**Comment by GrayHatter** [comment]
will be fixed with #752

**Comment by GrayHatter** [comment]
should be fixed already
