### ISSUE TITLE
[enhancement] [longterm request] One time pad encryption support

### ISSUE THREAD

**Issue by xor2003** [notsecure/uTox#659]
End to end one time pad encryption support.
For example you generated a DVD with encrypted random one time pad and shared to your friend.
You can chat all life truly secure in terms of cryptography.

**Comment by GrayHatter** [comment]
@xor2003 I'm going to close this one, If you really want this feature reopen this with a discription of your use case (how you expect this should work) and why you need this feature. Otherwise this won't happen until after we hit stable...

Or you welcome to reopen this and submit a PR too
