### ISSUE TITLE
Updating erased the key

### ISSUE THREAD

**Issue by Eiyeron** [notsecure/uTox#660]
Hi,
After having updated uTox on Windows, The tox_save has been wrongly read by the new version and thus got destroyed. Unfortunately ; no backup was saved and the nickname was registered on that gone key. Is there a way to reclaim that said nickname? And is there a way to backup or share keys for mutliple target clients? (Phone and computer)

Thanks in advance.

**Comment by GrayHatter** [comment]
closed as stale
