### ISSUE TITLE
[Request] Add bitrate setting

### ISSUE THREAD

**Issue by v2e** [notsecure/uTox#664]
It would be useful to add a possibility to adjust audio and video bitrate. For example, it is usually sufficient to use <=32kbps for audio call on per-megabyte tariff in order to save money. And still with OPUS or Vorbis 32kbps is a good quality for voice encoding.

**Comment by GrayHatter** [comment]
needs toxcore support @irungentoo correct me if I'm wrong...

**Comment by GrayHatter** [comment]
in talking with irungentoo, this needs toxcore support. I'm going to close this because there's nothing uTox can do for it without core support.

If you really want this open a bug there
