### ISSUE TITLE
Can hear others in Group Call despite not answering

### ISSUE THREAD

**Issue by Xylemon** [notsecure/uTox#666]
Basically if you're invited to a Group Call, you can hear everyone, even if you don't answer or hangup. Only way to to not hear others is to leave the group altogether.

**Comment by GrayHatter** [comment]
@irungentoo I LOVE It'sDuke's mock up, if you can provide the audio code to support muting, It'd be easy for me to write the front end.

**Comment by GrayHatter** [comment]
groups broken for now, please reopen once we get new groupchats
