### ISSUE TITLE
Group chats have stopped working :-(

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#677]
Hello,

With uTox on Windows, 64-bit, I can create a new Groupchat #0. When I drag contacts to it, nothing happens, I still see myself only... :-/ This stopped working recently, before it worked fine, I have been using it several times... Kindly let me know how this could be fixed. Thanks a lot in advance!

**Comment by GrayHatter** [comment]
@darkman088 I'm going to close this, but if you can still make it happen let me know and re-open this
