### ISSUE TITLE
Lost contact list after upgrading utox

### ISSUE THREAD

**Issue by pitchforks** [notsecure/uTox#682]
So there was a WinXP computer with a few months old utox. Today I decide to update it, download the latest daily build from the tox.im wiki (which is now just a standalone exe file, unlike the old one that was an installer, not sure if this is relevant). I run the new utox executable and my contact list is gone. It also shows my name as default "Tox User" instead of my custom name, so I assume I've also lost my tox ID, but I can't prove that because I didn't write down the old one so I've got nothing to compare against.

What I did wrong: didn't back up the old version of utox; didn't back up the tox data files. This is of course the main reason of my data loss, this is what makes any investigation attempts futile. But I must admit that utox never tried to make it easy for me by providing hints. I've got no warnings about the incoming data loss.

What utox did wrong: apparently it overwrote the data files (I can assume that by looking at the tox data files, their modification date, which is recent) without providing any warning or asking the end user if that should be done. I don't know if this is a backwards incompatibility issue, utox didn't tell me anything. Sane software should be able to correctly import data from older versions or halt and notify the user it can't be done for compatibility issues and offer alternatives of data migration.

I understand utox is alpha software and that the blame for data loss falls on me entirely, but utox is not usable in this state as long as it doesn't warn the user about scenarios like the described above.

**Comment by GrayHatter** [comment]
This should be fixed in the newest master, otherwise, yeah it's alpha software and bugs do (did) exist. sorry about your data loss mate, if it's any consolation, uTox shouldn't do it now...
