### ISSUE TITLE
strange notifications

### ISSUE THREAD

**Issue by zwischen** [notsecure/uTox#691]
I'm getting notifications about broken transfers.  This happens even after the file transfer has been cancelled and the the user goes off line.

**Comment by GrayHatter** [comment]
closed as stale, @zwischen reopen or tag me if you can still make this happen

**Comment by tsudoko** [comment]
I've had this happen yesterday, can't reproduce it right now, though. Not sure under which conditions it still happens.

**Comment by GrayHatter** [comment]
@tsudoko if you figure it out, tag me, or open a new very descriptive issue for it

**Comment by tsudoko** [comment]
@GrayHatter it's basically a duplicate of #766, I think

**Comment by GrayHatter** [comment]
that's still open so I'm just going to leave this one closed as superseded by #766
