### ISSUE TITLE
The latest uTox version(s) beginning of December (2-3 Dec) are VERY buggy !!!

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#692]
Hello,

I have decided to try the latest uTox versions. Now I am trying to head a conversation
from a Linux Fedora 20 laptop to a Windows 7 laptop and it is very cumbersome.
On the Linux PC I cannot see the camera picture of my conversation partner, I only see
a white window. On the other side - on the Windows 7 PC, utox.exe is all the time freezing
or quitting with an error message - utox.exe has stopped working.
Please kindly fix this... Thanks in advance!

**Comment by ElLamparto** [comment]
This ticked is heavily out of date. Why not to close it ?

**Comment by GrayHatter** [comment]
it's not even a full month out of date. But I still agree, if @darkman088 doesn't reply in 48h it should be closed.

**Comment by darkman088** [comment]
Hey, come on, sorry, I have been very busy recently and did not even have time for voice calls, not even to mention video...
At least I will try the latest versions currently available...

**Comment by GrayHatter** [comment]
no rush, it's only that utox has more stale bugs than actual, so clearing out some dead ones is on the todo list.

**Comment by darkman088** [comment]
OK, fine, but have been waiting more for new features... I have directed about sooooo many things, that can be improved, but there seems to be nothing happening on my threads... Sad :-/

**Comment by GrayHatter** [comment]
@darkman088 I'm closing this, if you can make this bug happen on demand please create a new issue, tag me, and provide as much information as you can as to how can I make it happen too.
