### ISSUE TITLE
Feedback on uTox usability...

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#693]
Hello,

uTox is a very nice program. I mostly like the compact interface it offers! Contrary to other programs,
that open 1000 additional windows - for the contact list, for each chat, for a voice call, uTox keeps everything pretty much straight forward.
Just I have noticed a few hiccups on voice calls. If those get ironed out, uTox will be unbeaten forever!
1) Hanging up calls - if somebody has been called by mistake, it is not possible to hang up the call.
Suggestion: The button should turn RED, as soon as a call has been intiated, not when the other party picks up, that is too late.
2) There should be an additional red button in order to reject unwanted incoming calls.
3) In case of an incoming call, the green button to pick up, should be focused on the contact, from whom the call is coming. Many times, when I receive a call, instead of picking up that call, I am calling the person I am chatting with, so a big mess occurs. This is the most annoying hiccup among all that I am naming here.
4) When initiating a call, it keeps ringing for just 8-10 seconds. That gives very little time to react, especially bearing in mind point 3) as well. So it almost always results in a missed call! 
Suggestion: this time should be prolonged to at least 60 seconds!

Many thanks!

**Comment by GrayHatter** [comment]
@darkman088 thanks for you feed back, all of these are either duplicates of other open issues, already fixed, or the solution for them is coming from another issue. I'm going to close this one but if you think I've missed anything, you should open a new issue. (One issue for each bug/request)

Thanks!
