### ISSUE TITLE
[REQUEST] Customize the keymap

### ISSUE THREAD

**Issue by AbcAeffchen** [notsecure/uTox#695]
I'm using a keyboard with an US Layout. But I'm german so I need characters like 

> Ä,ä,Ö,ö,Ü,ü,ß

So I'm using EurKey, a layout where a lots of european special characters are available by key combinations. Like [Alt] + [a] for ä and [Alt] + [s] for ß.

But [Alt] + [a] clears the chat field.

I don't know if there are other combinations that results in something I would not expect, but maybe it is possible to get an option to change the keymap.

**Comment by GrayHatter** [comment]
this is a bug that I know exists, and I'll try to track it down eventually, otherwise this is a dup of another issue. If you still see this once #566 is closed please reopen this, or tag me
