### ISSUE TITLE
Friend dupe

### ISSUE THREAD

**Issue by Zeluboba** [notsecure/uTox#697]
Hi,

I asked my friend from my friend list to add me again, and I got his ID in my friend list twice (second one bugged, couldn't send messages), he got warning, that I'm already in his friend list. I deleted second record, but that's annoying.
He added my as zeluboba@toxme.se and as zeluboba@cronfire.ru second time.

**Comment by GrayHatter** [comment]
I've never seen this, can you still make it happen. Groupbot never gave me this issue

**Comment by GrayHatter** [comment]
Stale, and I think a toxcore issue as well
