### ISSUE TITLE
µTox can't send files

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#705]
de0dd97bb5429ca3510554c3d9ffc0620c81f442 introduced regression which makes it impossible to send files.

If file transfer is cancelled when peer goes offline, it is being "resumed" when peer comes back online. Cancelling it again doesn't work, one still can't send more files.

``
Maximum outgoing file sending limit reached.
``

**Comment by GrayHatter** [comment]
@zetok can you try again? I can't seem to duplicate this in windows, I can try linux if needed too. 

If so can you provide a step by step so that I can fix this?

**Comment by GrayHatter** [comment]
This might be related to a toxcore issue, assuming it still exists I'll comeback to this after the new toxcore api is ready.

**Comment by GrayHatter** [comment]
fixed in master tag me if I'm wrong
