### ISSUE TITLE
Minimize when making a screenshot

### ISSUE THREAD

**Issue by gjedeer** [notsecure/uTox#715]
On smaller screens (laptops/netbooks) uTox takes a lot of screen space and the feature of sending screenshots is limited to sending screens of uTox itself because you can't see anything behind uTox.

Say I want to send a screen shot of a web browser - I can't do it because it's covered by the uTox window. It's not a problem on a real computer but on small laptops it makes the screenshot feature almost useless.

An optional setting to minimize main window before taking a screenshot would remedy this problem.

On X11 it could probably be done by adding this to desktopgrab():
    
    XIconifyWindow(display, window, screen);
    XFlush(display);
    //     XGrabPointer(display, ....
    XMapWindow(display, window);
    XFlush(display);

I'm not creating a pull request, though, because I can't build uTox or implement it for Windows.

**Comment by draziw-** [comment]
There is a little problem doing this is that you can't take a screenshot of you tox client, maybe a little timer can solve the problem?

**Comment by GrayHatter** [comment]
Holding ctrl + click would solve the problem of wanting uTox or not wanting uTox.

**Comment by kriswema** [comment]
On Debian / MATE you can click the screenshot button and Alt+Tab to the desired window. Doesn't work on Windows, though.

**Comment by gjedeer** [comment]
Indeed, alt-tab seems to work on my desktop too. So this solves my problem but not necessarily this of Windows users.

**Comment by GrayHatter** [comment]
blocked by GrayHatter/uTox#14 please reopen this issue here https://github.com/GrayHatter/uTox/
