### ISSUE TITLE
Settings button should be on top left corner

### ISSUE THREAD

**Issue by gott3rfunk3n83** [notsecure/uTox#718]
Like most applications in windows and Linux. That way noobs in tox wouldnt accidentally change sensitive settings in utox. Or possibly also an option to password protect the settings that way when other people are using your PC they dont mess up your settings like tcp, udp, ipv6, your user account name etc....

**Comment by GrayHatter** [comment]
Can you give a usage example?

**Comment by gott3rfunk3n83** [comment]
Something like toxy where settings button is not mixed with all the other
buttons bellow. That way you dont accidentally click on it.

It saves you from unwanted/accidental settings changes.

At the top left corner there is a symbol of tox/padlock. Thats where the
settings button should be when clicked it brings you to settings.

**Comment by tsudoko** [comment]
I like where the settings button is right now.

**Comment by gott3rfunk3n83** [comment]
Its just a tiny cosmetic change but it would definitely have a big impact on user experience

**Comment by gott3rfunk3n83** [comment]
Sorry I just checked but toxy has setting button bellow. But you get the idea.

**Comment by muchweb** [comment]
>Like most applications in windows and Linux.

>At the top left corner there is a symbol of tox/padlock. Thats where the settings button should be when clicked it brings you to settings.

@gott3rfunk3n83, Could you please provide an example of this, e. g. a screenshot? Do you mean a [menu bar](http://en.wikipedia.org/wiki/Menu_bar)?

>Or possibly also an option to password protect the settings that way when other people are using your PC they dont mess up your settings

This sounds unreliable. One can probably use a screen lock or a guest user instead.

**Comment by gott3rfunk3n83** [comment]
Yep thats it. like a menu bar at top left.

And you can't screen lock or use guest user when its on usb portable mode.

**Comment by GrayHatter** [comment]
this would be a complete UI rewrite, I'm not gonna touch this one unless someone creates a mockup of how they want it to look.
