### ISSUE TITLE
Support PGP Word List

### ISSUE THREAD

**Issue by GrayHatter** [notsecure/uTox#720]
https://en.wikipedia.org/wiki/PGP_word_list

**Comment by draziw-** [comment]
Can you explain more the way of using that ?
Some use cases of how you see the integration in the client.

**Comment by GrayHatter** [comment]
It'd be a way to read off a friend ID over a lossy voice channel. I'll write a usage scenario soonish, but only one person would have to read off the word list. uTox should show a clickable group of word that will build the ID for you.

**Comment by draziw-** [comment]
This would give us 38 words to transfert.  Use tox dns seems more reliable no ?

**Comment by GrayHatter** [comment]
Probably, this is just a gimmicky idea.
