### ISSUE TITLE
Adding correct git version tags

### ISSUE THREAD

**Issue by muchweb** [notsecure/uTox#737]
This makes it easier to find to specific releases. This will also add respective "Github releases" if somebody is looking to download any particular version.

Here are commits that I've managed to recover from `main.h` version bump history.

```bash
git tag v0.1.9 e69d9a1bb4d3c24ed10d94f75a1cdc87315287fa
git tag v0.1.8a c09022cfb51620f689b41cf08a4fb6578463c7f3
git tag v0.1.8 863f50829d1149d27a4c047ae61e3f0b8633e4aa
git tag v0.1.3 fde99033b41b4ff666602b38f3d42e53dafff460
git tag v0.1.2 a755dcd961c8c9b5307e0dcae7d7e2b3e2ca4fd5
git tag v0.0.9 6fa16748f30d75c69133a5aac2c243a090705116
```

Then, run `git push --tags`.

**Comment by tsudoko** [comment]
It's been reported several times already.
#271 #296 #679

**Comment by muchweb** [comment]
@tsudoko, thanks. Yes, it looks like not all versions were consistently bumped. Here's somewhat a solution from what I have managed to recover.

**Comment by GrayHatter** [comment]
@irungentoo can you tag and push tags so we can close these?

**Comment by muchweb** [comment]
@irungentoo, here are commits for more recent versions (in addition to above):
```bash
git tag v0.2.n deea2e1da92a541a654ff48c9c0681c54af9f579
git tag v0.2.m 43da5eb3cd30b315b48bd339064168eb544b269c
git tag v0.2.l cb7b8d09b08d7043de435f0ef19c1c6f5b47a4dd
git tag v0.2.k ba257667bdb6ea2c5f4d0e070bac7882330883b4
```

**Comment by muchweb** [comment]
@irungentoo, thank you. Not being picky, but could you also add older tags (from my original post), just for the sake of preserving history? ☺

**Comment by tsudoko** [comment]
``22:24:51 <@irungentoo> `michiru, the version numbers in main.h were wrong``
