### ISSUE TITLE
Windows - Screenshot feature broken on multiple monitors

### ISSUE THREAD

**Issue by Impyy** [notsecure/uTox#738]
Let's say you have multiple monitors and you're using Windows.
If you try to take a screenshot, the 'screenshot selection box' will appear on the wrong screen, or it won't appear at all. The screenshot IS taken from the region you selected with your mouse, though. (not where the 'screenshot selection box' happens to be)

I experienced this on Windows 8.1 with two 1080p monitors, if that makes any difference.

**Comment by Agent0929** [comment]
Same problem experienced on a setup with three screens, on Windows 7 Professional SP1.

**Comment by GrayHatter** [comment]
@irungentoo can you assign me so I don't forget about this one?

**Comment by GrayHatter** [comment]
@Impyy if I push a fix, would you be able to test this for me?
