### ISSUE TITLE
uTox only uses tox_save.tmp as backup if the tox_save file is missing or empty

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#743]
Because of that it will create a new ID and deletes tox_save.tmp when the broken tox_save contains a whitespace or some other garbage.

This might be interesting for you @GrayHatter .

**Comment by GrayHatter** [comment]
@towlie was this issue fixed in f26ad0bdf645f3a389bf050cac83239afe78d5f4 or does it still exist in master?

**Comment by draziw-** [comment]
This issue still exist in master, as specified in #744, if tox_save is not empty, we will try to load tox from it, when we don't know if it's valid tox save.

**Comment by towlie** [comment]
Yes, as draziw said. My tests were done with https://github.com/notsecure/uTox/commit/f26ad0bdf645f3a389bf050cac83239afe78d5f4.

**Comment by GrayHatter** [comment]
Ahh, I understand. We really should be choosing the file based on if we
like agree with what tox_load says. So that's should be the next step if
anyone beats me to it.

**Comment by GrayHatter** [comment]
superseded by #745
