### ISSUE TITLE
[Question] uTox possible risk of losing contact list on PC crash

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#744]
Situation:
- PC crashes while doing tox_save so it has a broken/wiped contact list stored in tox_save and a fully working tox_save.tmp
- on restart utox ignores the tox_save.tmp because it thinks the tox_save file is fine (which it is except it's missing contacts)

-> Contacts are lost

I am not sure is this can happen in reality but that's how uTox handles my manually corrupted tox_save file.
What do you think? Can this actually happen?

**Comment by draziw-** [comment]
It don't think this can happen:
When tox is saved, we first save into tox_save.tmp, then, only if the save is successful, tox_save.tmp is renamed to tox_save.

About your manually corrupted tox_save:
```c
        tox_load(tox, data, size);
        free(data);
```
This is what the actual code does, we don't check the return value of tox_load.
```c
/* Load the messenger from data of size length.
 * NOTE: The Tox save format isn't stable yet meaning this function sometimes
 * returns -1 when loading older saves. This however does not mean nothing was
 * loaded from the save.
 *
 *  returns 0 on success
 *  returns -1 on failure
 *  returns +1 on finding encrypted save data
 */
int tox_load(Tox *tox, const uint8_t *data, uint32_t length);
```
So we actually don't even know that we are running a corrupted save.

This is also the reason for #743 your reported.

**Comment by GrayHatter** [comment]
fixed in master
