### ISSUE TITLE
Feature request - Namecoin (or similar) integration

### ISSUE THREAD

**Issue by Aranad** [notsecure/uTox#751]
The tox addresses are pretty unfriendly, it would be awesome if a decentralised system such as namecoin could be used to allow friendly names instead. Namecoin already uses the "id/" namespace for identity/contact information so people could add a "tox" value to their current data which Tox could lookup when people used a name instead of a tox-address.

**Comment by draziw-** [comment]
Hello, this already exists and working in utox, it uses the tox dns system.

uTox actually supports the following tox dns servers:
- utox.org
- toxme.se

Once subscribed, your friend can add you only with your name.

**Comment by Aranad** [comment]
Cool thanks, I've just subscribed myself :-)
