### ISSUE TITLE
File transfer doesn't work when there are special characters inside the path to the file

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#752]
Folder Name example: 【Nichijou opening _ op】 [HD_720p] - 【Hyadain no Kakakata☆Kataomoi - C】
Same counts for filenames.
(Windows)
After selecting the file nothing happens.

**Comment by Doom032** [comment]
I found this too when testing the selecting avatars on Windows. Seems it can't manage Unicode filepaths correctly yet. I believe it works on Linux though.

**Comment by GrayHatter** [comment]
@Doom032 utf8native() needs to strip anything it can't resolve. (no idea how to do this yet, I'll look later unless you beat me too it.) Additionally, we should make sure we're using utf8tonative when asking to save this file.

**Comment by davidmartingonzalez** [comment]
I've tried dragging and dropping a file from Windows 8.1 into uTox. The name was "Sin título.png", but there was a � in place of the í. However, the file transfer worked just fine for me.

**Comment by GrayHatter** [comment]
@towlie can you try this again with my file_resume branch (in PRs)

@Doom032 you too?

**Comment by towlie** [comment]
@GrayHatter It's not fixed on Windows with your current file_resume branch.
And it only compiles with -std=gnu99.

**Comment by GrayHatter** [comment]
Does the transfer not work at all, or is it stalling, or saving bad data?
Or something else?

**Comment by towlie** [comment]
On gui side it does nothing when selecting the file. Here is the console output:

```
FileTransfer:   Starting outgoing file to friend 1. (filename, ?Nichijou opening
 _ op? [HD_720p] - ?Hyadain no Kakakata?Kataomoi - C?.txt)
FileTransfer:   Unable to open file for reading!
Writing tox_save to: C:\Users\\AppData\Roaming\Tox\tox_save.tox.tmp
Failed to rename file. C:\Users\\AppData\Roaming\Tox\tox_save.tox.tmp to C:\
Users\AppData\Roaming\Tox\tox_save.tox deleting and trying again
Saved data
SaveFile:       Writing uTox Save file for File Transfers
```

**Comment by towlie** [comment]
Oh and I didn't test it on Linux.

**Comment by GrayHatter** [comment]
It works on linux, that's what I'm using to send the file to windows

**Comment by GrayHatter** [comment]
the code exists in the auto accept native functions for windows, it's just copy, paste, test, at this point
