### ISSUE TITLE
Utox crashes every time I press the phone or video icon

### ISSUE THREAD

**Issue by Hdram** [notsecure/uTox#753]
I've tried many versions over the past few months but I always have the same problem. Text chat and file transfer work fine but I can't do voice or video without crashing immediately I try.
I using Windows Server 2003 (equivalent of WinXP)

**Comment by irungentoo** [comment]
https://jenkins.libtoxcore.so/job/uTox_win32_debug/lastSuccessfulBuild/artifact/utox/utox_win32_debug.zip

run: debug-blind-print-bt-and-app-output-on-crash.bat then make it crash and post the log it created here.

**Comment by Hdram** [comment]
Trying to do that right now. Running Debug but I have no one to call right now. Is
 there some test system that I ca call ?

**Comment by Hdram** [comment]
Here's the log when I start up, if that's any use:
2015-08-01 03:05:17 file logger starting
03:05:17 built on:  23:01:29 Jan  6 2015 ( 1420585147 )
03:05:17 commit:  57ba0e191b2ca3c28c06b5c51c0859dc4cb5ec82 

03:05:17 IPC: Our global ID is  1629384259164
03:05:17 IPC: Creating the global shared memory and taking ownership
03:05:17 Core: loading Tox from "F:/Documents and Settings/Administrator/AppData/Roaming/tox/D2995B878066.tox"
03:05:17 Audio:  "Trying to open output Bluetooth SCO Audio"
03:05:18 Audio: Opening audio output  "Bluetooth SCO Audio"
03:05:18 Audio:  "Trying to open input Bluetooth SCO Audio"
03:05:18 Audio: Opening audio input  "Bluetooth SCO Audio"
03:05:18 Core starting with IPv6 enabled
03:05:18 VideoSurface: Init
03:05:18 getProcAddress: Unable to resolve 'glGenBuffers'
03:05:18 getProcAddress: Unable to resolve 'glGenBuffersOES'
03:05:18 getProcAddress: Unable to resolve 'glGenBuffersARB'
03:05:18 getProcAddress: Unable to resolve 'glGenBuffersEXT'
03:05:18 getProcAddress: Unable to resolve 'glGenBuffers'
03:05:18 Core failed to start with IPv6, falling back to IPv4. LAN discovery may not work properly.
03:05:18 Core::loadConfiguration: reading from  "F:/Documents and Settings/Administrator/AppData/Roaming/tox/D2995B878066.tox"
03:05:18 Core: Error loading self avatar
03:05:18 getProcAddress: Unable to resolve 'glGenBuffersOES'
03:05:18 getProcAddress: Unable to resolve 'glGenBuffersARB'
03:05:18 getProcAddress: Unable to resolve 'glGenBuffersEXT'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgram'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgramARB'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgramObject'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgramObjectARB'
03:05:18 QOpenGLShaderProgram: could not create shader program
03:05:18 getProcAddress: Unable to resolve 'glCreateShader'
03:05:18 getProcAddress: Unable to resolve 'glCreateShaderARB'
03:05:18 getProcAddress: Unable to resolve 'glCreateShaderObject'
03:05:18 getProcAddress: Unable to resolve 'glCreateShaderObjectARB'
03:05:18 QOpenGLShader: could not create shader
03:05:18 getProcAddress: Unable to resolve 'glCreateProgram'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgramARB'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgramObject'
03:05:18 getProcAddress: Unable to resolve 'glCreateProgramObjectARB'
03:05:18 QOpenGLShaderProgram: could not create shader program
03:05:18 getProcAddress: Unable to resolve 'glCreateShader'
03:05:18 getProcAddress: Unable to resolve 'glCreateShaderARB'
03:05:18 getProcAddress: Unable to resolve 'glCreateShaderObject'
03:05:18 getProcAddress: Unable to resolve 'glCreateShaderObjectARB'
03:05:18 QOpenGLShader: could not create shader
03:05:21 Core: Bootstraping to the DHT ...
03:05:21 "Core: Bootstraping from Nikolai Toryzin, addr 192.254.75.98, port 33445"
03:05:21 "Core: Bootstraping from Nikolai Toryzin, addr 31.7.57.236, port 443"
03:06:23 "Core: Group namelist change 0:0 0"
03:06:23 Widget::onGroupNamelistChanged: Group  0  not found, creating it
03:06:23 "Core: Group namelist change 0:0 2"
03:06:23 Widget::createGroup: Group already exists
03:06:26 "Core: Group namelist change 1:0 0"
03:06:26 Widget::onGroupNamelistChanged: Group  1  not found, creating it
03:06:26 "Core: Group namelist change 1:0 2"
03:06:26 Widget::createGroup: Group already exists
03:06:55 Settings: Saving in  "F:/Documents and Settings/Administrator/AppData/Roaming/tox/qtox.ini"
03:06:55 Core: writing tox_save to  "F:/Documents and Settings/Administrator/AppData/Roaming/tox/D2995B878066.tox"
03:06:55 Audio:  "Closing input"
03:06:55 Audio:  "Closing output"
