### ISSUE TITLE
TAB key doesn't change focus to next control.

### ISSUE THREAD

**Issue by mc-jesus** [notsecure/uTox#754]
Pressing TAB or Shift+Tab doesn't change the current focused item to the next one. This happens on Windows. I tried looking into it and I think the problem could be fixed by giving the controls the WS_TABSTOP  style. I looked through the code and I think this is defined here:
https://github.com/notsecure/uTox/blob/master/win32/main.c#L1177

Here's an useful page I found on this topic 
http://msdn.microsoft.com/en-us/library/ms644995%28v=vs.85%29.aspx#ws_tabstop

**Comment by GrayHatter** [comment]
stale, tab is now used for group nick completion, maybe ctrl+tab could be used to cycle friends...
