### ISSUE TITLE
The tox_bootstrap.h file contains a lot of outdated nodes

### ISSUE THREAD

**Issue by nikwen** [notsecure/uTox#755]
Compare with https://wiki.tox.im/Nodes

**Comment by nikwen** [comment]
Sorry, has already been updated. b30b54083f6f29164522ddd6d121d91376b69e88

**Comment by gjedeer** [comment]
Roughly half of the nodes don't answer to pings any more. 

I've started off with your list of bootstrap nodes and I'm still using the same format in my project, so maybe this will be of some use to uTox: [the updated node list](https://github.com/gjedeer/tuntox/blob/master/tox_bootstrap.h) and [the tool used to generate it](https://github.com/gjedeer/tuntox/blob/master/generate_tox_bootstrap.py).
