### ISSUE TITLE
Setting an avatar is needlessly "complex" for technically non-savvy users

### ISSUE THREAD

**Issue by LittleVulpix** [notsecure/uTox#762]
Related to irungentoo/toxcore#1221 - utox's dry statement that 'the maximum allowed filesize is X' shouldn't bother the user. Users should simply be able to select any image they want and the internal uTox logic should perform the conversion into resolution+size supported by the protocol.

Currently the user has to find the image they like and then use picture editing tool to re-save it in a way that doesn't exceed 16kb.

**Comment by GrayHatter** [comment]
@littlevulpix any chance you've heard of any libre tools/plugins/code to cross convert and resize different image formats have you?

**Comment by Doom032** [comment]
qTox does this. It's one of the things I've been wanting to add after getting avatars in in the first place. I can start working on it after I'm done with avatar transparency #729

@GrayHatter I don't think we need any special stuff. We already have the PNG converter. All we need to do is have a function which can resize a UTOX_NATIVE_IMAGE(really resize it, not just set its scale), and a function which converts a UTOX_NATIVE_IMAGE back to a PNG. The last thing is already being done at some point in the Windows code(though it doesn't copy transparency yet), so it could easily be factored out into a function, and a similar function added to the Xlib code.

**Comment by LittleVulpix** [comment]
Sounds like this is gonna be possible! And nope sorry guys, I dunno any libre tools/plugins/code. I'm not a programmer (used to be! But that was a long time ago, hehe).

**Comment by GrayHatter** [comment]
@Doom032 utox native is just bitmap is it not? Then we'll need to convert jpg and gif to bmp right?

**Comment by Doom032** [comment]
@GrayHatter Oh I was just thinking of resizing. Supporting different file types probably does require some extra libraries, but I think it's less important than automatic scaling. The most important other file format to support would probably be jpeg. gif wouldn't be read well anyway(can't save the animation), and is less used.

**Comment by GrayHatter** [comment]
@Doom032 can we scale the image down to the smallest resolution that will fit the size we're looking for copy it to the pixmap xlib or bitmap on windows and then copy that map back to utox and write that file to disk and use that?

**Comment by tsudoko** [comment]
Wouldn't that mean my avatar would get modified by uTox? I don't want that.

**Comment by GrayHatter** [comment]
utox already makes a copy of your avatar, all this would do is resize it before saving it. Allowing you to select a HUGE avatar, with utox only saving the size it needs.

**Comment by tsudoko** [comment]
Other clients can display avatars with size different than the one uTox uses, though.

**Comment by GrayHatter** [comment]
@grayhatter repo on https://github.com/GrayHatter/uTox/issues

**Comment by GrayHatter** [comment]
all of the functions have a way to select a subsection of an image. we just need to write the handlers inside utox... All the functionality is there, we just need a  UI
