### ISSUE TITLE
Notification bug with filetransfer

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#766]
How to reproduce:
Send a file to a friend and abort it.
Everytime he goes offline you will get a notification that the filetransfer was aborted. (Only for the sender)

Also everytime he goes offline the filteransfer buttons change:
from:
![state1](https://cloud.githubusercontent.com/assets/6986141/5790904/60ea49b8-9eb0-11e4-9751-e0ab04f1d779.jpg)
to
![state2](https://cloud.githubusercontent.com/assets/6986141/5790905/64e238e6-9eb0-11e4-8b7c-dbc30c4ab419.jpg)

**Comment by GrayHatter** [comment]
happens on windows and linux

**Comment by GrayHatter** [comment]
I was working with file transfers last week and didn't see this anymore. @towlie do you still have this problem?

**Comment by tsudoko** [comment]
I've had this happen yesterday, can't reproduce it right now, though. Not sure under which conditions it still happens.

**Comment by GrayHatter** [comment]
@tsudoko keep trying to make it happen, if you can figure out what causes it, I can fix it (maybe)

**Comment by towlie** [comment]
It still happens and is easy to reproduce. Just send a file to someone, cancel the filetransfer and let the contact go offline. Everytime the contact goes offline you will get that notification and that what you see in my first post.

**Comment by GrayHatter** [comment]
Fixed in master
