### ISSUE TITLE
crash when pressing new 'plus' button and typing a letter immediately afterwards

### ISSUE THREAD

**Issue by Doom032** [notsecure/uTox#774]
So a new update added a plus button to send a message in uTox, but when I click it and start typing immediately afterwards I crash on segmentation fault.

Last messages in the debug output don't seem very helpful:
Saved data
CHMOD: success
Sent typing state to friend (6): 1
Sent typing state to friend (6): 0
Segmentation fault

On Xubuntu, and I updated utox just now. Encrypt tried to reproduce it on Ubuntu but wasn't able to.

**Comment by GrayHatter** [comment]
from #utox 
```
<sda> DoomBoom: managed to reproduce your crash, want a backtrace?
<DoomBoom> sure
<sda> it's not long so I'll paste it here
<sda> #0  0x00007ffff4eaad1d in ?? () from /lib64/libc.so.6
<sda> #1  0x0000000000411313 in edit_char (ch=107, control=false, flags=0 '\000') at edit.c:633
<sda> #2  0x00000000004179dc in doevent (event=...) at xlib/event.c:301
<sda> #3  0x0000000000418f10 in main (argc=1, argv=0x7fffffffe168) at xlib/main.c:1038
```

**Comment by GrayHatter** [comment]
happens on win64 as well,
