### ISSUE TITLE
Create tooltip texts for all of the buttons. 

### ISSUE THREAD

**Issue by GrayHatter** [notsecure/uTox#776]
- [ ] Avatar
- [ ] username
- [ ] status message
- [ ] filter friends dropdown
- [ ] Friends list (perhaps their user id?) 
- [x] add friend button
- [x] start new group chat
- [x] swtitch tox user profile 
- [x] change settings

**Comment by GrayHatter** [comment]
@tsudoko

**Comment by tsudoko** [comment]
Wanted to do tooltips for user statuses/names, but I think it'd require more work than just adding one line with tooltip text, not sure if I can manage to do it.

**Comment by GrayHatter** [comment]
@tsudoko somewhere in the source is an example of how to create a tooltip
from generic text. (I think they just used utf8tonative() ) I'm sure you
can grep tooltip to find it, I think it's just commented. But if you need
me too, I'll write a function you can use that will put a utf8 tox string
into a tooltip if you're willing to tooltip the hell out of things?
