### ISSUE TITLE
Tooltips remain when the mouse leaves the window

### ISSUE THREAD

**Issue by GrayHatter** [notsecure/uTox#777]
Tooltips should disappear if the mouse leaves the client window.

**Comment by towlie** [comment]
This reminds me that a context menu doesn't disappear if you click outside of the utox window. 
If this issue shall be fixed then it should fix that context menu issue too.

**Comment by ElLamparto** [comment]
Also when the config button tooltip is displayed, clicking on the button has no effect (Win32).

**Comment by GrayHatter** [comment]
fixed somewhere...
