### ISSUE TITLE
µTox windows don't scroll with finger drag on touch screen devices.

### ISSUE THREAD

**Issue by GrayHatter** [notsecure/uTox#778]
I have no idea where to even start with this one, because mouse dragging shouldn't scroll windows. Any suggestions?

**Comment by tsudoko** [comment]
"Touch mode" option? Long-pressing on text would activate text selection, long-pressing on contacts/avatar would open the context menu.

**Comment by LapFox** [comment]
Perhaps the touch mode would also listen for finger drag on Android and Windows 8. Windows 7 I believe also has some sort of dragging event for those old Windows 7 tablets

**Comment by GrayHatter** [comment]
@LapFox do you have a link to the API, I'll go find it eventually, but I'm lazy...
