### ISSUE TITLE
Send & Screen Sharing Buttons

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#782]
IMHO:
1. The SEND button should have something like a simple arrow (-->) rather than a plus sign (+).
2. The screen sharing button should be moved up and located left to the file transfer button (we would then have four buttons on the upper right corner of the form). After moving the screen sharing button, the empty space could be used for smileys (if they ever arrive ;) or the SEND button could be enlarged vertically to fill up the space.

**Comment by LapFox** [comment]
The send button could have something like the Android send icon, sort of like a paper aeroplane http://i.stack.imgur.com/Jg4vi.png

(link to stackoverflow issue which has link to android icon pack: http://stackoverflow.com/questions/17587842/android-native-send-button-icon I haven't checked anything about the licence of using one of these icons)

**Comment by Doom032** [comment]
We should be working more towards the mock-up: https://github.com/ItsDuke/Tox-UI
I think a speech bubble would be the best send icon. I'm not sure about changing the place of the screenshot button though, I get that it should move, but I think there's some disagreement on where to place it.

**Comment by GrayHatter** [comment]
why do we have it? I'd suggest killing it (or at least hiding it somewhere non-obvious) and instead working on live screen sharing. Like every other video call app supports.

**Comment by ElLamparto** [comment]
@Doom032, Send Screen, Send File, Audio Call, Video Call.... in my opinion it makes sens having them all in one row.. I would keep the icons as simple as possible.

@GrayHatter: it is a unique feature of utox and very useful, please keep it. Live screen sharing is a different function.

**Comment by Doom032** [comment]
@GrayHatter seriously, most people who use µTox currently do so only because of the ease of sending screenshots with the screenshot button and screensharing. This includes myself. It's such a hit that tux3 even agreed it should be implemented in qTox even though he was opposed to it ( tux3/qTox#773 ). It's one of the few features we currently have over qTox.

**Comment by gjedeer** [comment]
Please don't kill the screenshot button, it's an awesome feature.

**Comment by kriswema** [comment]
Wait, don't we have live screen sharing? I can select "Desktop" in my video input options.

**Comment by gjedeer** [comment]
@kriswema I, for instance, used live screen sharing only once - to check if it works. I'm using the screenshot button daily. So yes, there is live screen sharing, but it's not a better alternative to screenshots - it's a different feature.

**Comment by muchweb** [comment]
>The screen sharing button

It looks like when author of the issue is saying 'screen sharing', they really mean a screenshot.

/cc @kriswema @gjedeer

**Comment by kriswema** [comment]
Yes, the original issue was with the screenshots, but @GrayHatter and @ElLamparto were talking about a video screen sharing option. I just wanted to clarify that we already have an option for that, even if hidden in the options. :clipboard:
