### ISSUE TITLE
File Transfer Speed Limit

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#783]
While transferring files, µTox eats up all the bandwidth available what has two negative consequences:

1. Other applications are suffocating,
2. I believe that the µTox "service" traffic is disturbed too, because the contacts flip randomly on and off and so does my online indicator.

Since most of p2p applications has such limit implemented as a configurable option, it would be very useful to have it in µTox too.

**Comment by LittleVulpix** [comment]
Related to irungentoo/toxcore/issues/1220. Not a forced limit, but user-customizable limit (like a slider or something) would be amazing.

**Comment by GrayHatter** [comment]
@irungentoo any plans to support throttling in toxcore, or it this going to be a client optional feature?

**Comment by LittleVulpix** [comment]
This is still present and rather upsetting considering that when you are transferring, you can't really talk to anyone as it keeps disconnecting you (and reconnecting) due to the transfer killing the line.

**Comment by GrayHatter** [comment]
transfers have gotten better, but without QOS from core, this is likely to be VERY hard to do correctly in µTox. you can still open this on the new repo if you'd like
