### ISSUE TITLE
Transfer speed indicator is useless (too jittery)

### ISSUE THREAD

**Issue by LittleVulpix** [notsecure/uTox#785]
The transfer speed indicator on uTox is currently useless. It'll change from 250KiB to 2MiB 4-5 times over the course of one second.

I propose calculating average transfer speed by using something like "data transfered in the last 5 seconds" or something like that. Currently, it's difficult to even see the speed since it twitches around so much.

**Comment by LapFox** [comment]
I agree it should be looked at. Perhaps it should update every 1.5 seconds, and display the average speed captured over that time. Time can also update every 3 seconds using an average of the 2 last user-reported speeds.

**Comment by GrayHatter** [comment]
this should be fixed with the new_api file_transfers

tag me if you still think it's too jittery

**Comment by LittleVulpix** [comment]
@GrayHatter It's a lot better - but it's still pretty jittery. I understand the transfer can be kinda wavy but could we estimate the average speed over longer periods of time, somehow?

**Comment by GrayHatter** [comment]
Planned, no eta. I'm in the process of writing a wrapper for these things
