### ISSUE TITLE
Avatars should look better

### ISSUE THREAD

**Issue by Doom032** [notsecure/uTox#788]
Two things:

 - They should be resized to 40x40 using cubic filtering(maybe this can be stolen from GIMP's source code?) so they look better(and look the same for every OS, currently Windows' built-in filtering looks worse)
 - They should use rounded corners as in the mockup: https://github.com/ItsDuke/Tox-UI

**Comment by Nsheppard01** [comment]
Higher resolutions would also be nice.

**Comment by GrayHatter** [comment]
@Doom032 this one is all yours!

**Comment by Doom032** [comment]
I got stuck on this with the bicubic filtering a while ago. I've been wanting to use some of the GIMP source code to do it(it supports bicubic filtering when resizing), and I've found the functions I need to do it with. It's just that I'm not sure of how to integrate it well for our purposes. I'll look at it again tomorrow.

Bicubic filtering is necessary because of the big improvement in image quality with images resized bicubically over images resized bilinearly. Without it, selecting a larger image and letting µTox resize it will make it look pretty ugly.

I also made a bit of a design on what image functions should exist in µTox, and made a little ASCII chart of it: http://pastebin.com/8hTskEY7
I made that before I got busy with other stuff. It's still my plan on how I'd like images to work. Note that the draw_image function already exists and the comment describes what to change about it.

**Comment by LittleVulpix** [comment]
Is it possible to look into this? I mean, just for comparison: the top picture is utox 0.2.r render of the avatar, the one below is one resized (lanczos3) to the same size (40x40px):

![resize quality comparison](http://i.imgur.com/Hs0TLvV.png)

**Comment by GrayHatter** [comment]
there's a lot of anti-aliasing that goes into making that look pretty... @Doom032 did you play with the built in resize options to see if there's anything that will provide this effect? Or would we need to import another library?

**Comment by Doom032** [comment]
The APIs in use to draw images currently are pretty primitive, the Windows API in particular is from the early '90s. We're using the best options in there to draw the images in a resized way, but yeah there's no fancy resizing algorithms built into those APIs. I was working on trying to get our own bicubic resizing in quite a while ago, but it became way too much work. The other possibility is to use an API like ImageMagick for it, but I haven't had time since then because of personal stuff, and I wasn't completely happy with the idea of adding it as a dependency, because it's relatively large and not too likely to already be installed on people's computer. Other ideas are welcome.

**Comment by LittleVulpix** [comment]
So it's not feasible to implement the bicubic or any other resizing/resampling formula like lanczos? I mean they're (technically) just mathematical functions, aren't they. Are they too much work to put in in a way that works on linux/windows?

**Comment by Doom032** [comment]
Well maybe someone else could look at it, but I didn't really get it. Though you should note that it should also be optimized a bit over the standard mathematical function, if you look at GIMPs implementation of bicubic resizing, it's clearly been well-optimized. I tried to adapt it to our code, but I didn't really get that going well either. GIMP uses too much of its own customized functions and types, making it hard to use a part of its code somewhere else. Maybe someone with more experience could do this better than me.

**Comment by LittleVulpix** [comment]
Something like https://code.google.com/p/imageresampler/ I wish I was any good at programming; I'd probably take a look into this. But alas, I'm a newb.

**Comment by Doom032** [comment]
Hey nice @LittleVulpix, that library actually looks great. Exactly what would fit uTox. We could just put that source code in with uTox' code as well so there isn't even a new dependency. I'll take a look at it if I have time, but I just kind of got home from a big trip so I'm gonna rest for the coming time. If someone else wants to take a look at it they're free to do so.

**Comment by Doom032** [comment]
Of course I didn't check well enough to see that imageresampler is a C++ library, not a C library, so adding it to the µTox source code is out of the question. Also, it lacks a C wrapper, though I could add it. It still looks like a pretty good library apart from that. Though test.cpp did look a bit daunting, took me a while to understand it a bit. I'm not the best programmer myself, I'm still learning. I'll see if I can work with this tomorrow.

**Comment by LittleVulpix** [comment]
@Doom032 Awr, sorry, I didn't realize this was c++. I should have realized, since I used to code in c++ for quite some time.

**Comment by GrayHatter** [comment]
stale, wrong repo... if this is still an issue open it there and I'll get on it
