### ISSUE TITLE
Version 22 Jan / Win32. The contact avatars appear only when a tooltip appear

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#792]
When a tooltip disappears, so do the contacts avatars. My own avatar is not affected by that bug.
When a tooltip reappears, so do the contacts avatars.

**Comment by Doom032** [comment]
Can you give a screenshot? I can't reproduce this here. Also, what OS?

**Comment by ElLamparto** [comment]
@Doom032: Win7 32bit. Screenshot  on Monday (26/01) - I have no Windows here. 
Also since introducing tooltips, uTox crashes randomly.

**Comment by ElLamparto** [comment]
When the avatars disappeare, there is nothing, not event the standard placeholders. Putting the mouse pointer over the config "circle" button makes a tooltip and the avatars reappeare (for a short while). I have a screenshot, but I do not know how to transmit it to you.

**Comment by Doom032** [comment]
>I have a screenshot, but I do not know how to transmit it to you.

You can select them to upload to the Github comments  by clicking the "selecting them" text at the bottom of the comment box.

**Comment by GrayHatter** [comment]
>You can select them to upload to the Github comments by clicking the "selecting them" text at the bottom of the comment box.

Or by just dragging them into the comment box

**Comment by ElLamparto** [comment]
![disappearingavatars](https://cloud.githubusercontent.com/assets/9163437/5915639/6d326a5c-a608-11e4-8ee0-834a03ebf69c.PNG)

Here is the screenshot.

**Comment by GrayHatter** [comment]
can you upload the contents of %AppData%\Tox\avatars somewhere? And then message either @Doom032 or myself where we can get a copy?

If needed I can create webpage that will allow you to do it privately?

**Comment by GrayHatter** [comment]
the filenames are named after your friends so you can rename them if you'd like extra security

**Comment by ElLamparto** [comment]
@GrayHatter: I could try to pump it via IRC (never done it before), or please create a webpage..

**Comment by normalST** [comment]
Same here, but on WinXP 32bit, two screenshots, where one with tooltip, and avatar, and one without both. '%AppData%\Tox\avatars' zip: https://www.dropbox.com/s/k8irw0z5n8mkqco/avatars.zip?dl=0
I renamed our IDs if you don't mind.

![allfine](https://cloud.githubusercontent.com/assets/7449741/5973380/3fac29a0-a870-11e4-900c-2dffe4a2875c.png)

![notfine](https://cloud.githubusercontent.com/assets/7449741/5973381/3fae5608-a870-11e4-9893-07d5f42be9f5.png)

**Comment by GrayHatter** [comment]
@Doom032 will have to take a look at this, but I assume that hdc is getting clobbered somewhere

**Comment by ElLamparto** [comment]
By the way, that bug does not appear on Debian.

**Comment by GrayHatter** [comment]
or windows (unless your fuxing with the hdc)

@Doom032: Actually, that's significant: svg images are drawn more reliably with a misconfigured main_hdc,hdc,hdcMem than avatars are. avatars are a little more sensitive to it. Perhaps the order (and thereby z level) they get drawn is important?

**Comment by Doom032** [comment]
Note that his own avatar stays visible. It's not purely the draw_avatar_image function that fails. I still have no idea what causes this, though, and not much time to check it out. And can't reproduce it locally. This might take a while before it gets fixed.

**Comment by ElLamparto** [comment]
@Doom032 This is a critical bug. It was not easy to get some of my contact off Skype and this bug does not help to keep them here. The last correct uTox version that I have is from 08/01. Maybe comparing sources would help? Maybe disabling tooltips would help (they are not that important anyway)?

**Comment by Doom032** [comment]
I'd be for removing tooltips until they work correctly.

**Comment by GrayHatter** [comment]
@ElLamparto can you take a look at #859 on windows and tell me if this fixes this issue?

**Comment by GrayHatter** [comment]
@ElLamparto this should now be fixed in master, can you give the current master a try?

**Comment by ElLamparto** [comment]
Embarrasing question: how to pull the executable from the master?

**Comment by tsudoko** [comment]
You can't really, you'd have to clone the source repository and compile the client yourself.

**Comment by irungentoo** [comment]
@ElLamparto

https://dist-build.tox.im/utox_win32.zip
https://dist-build.tox.im/utox_win64.zip

**Comment by ElLamparto** [comment]
@tsudoko, @irungentoo, thank you for the exe.
The problem with avatars is solved. Thank you!
