### ISSUE TITLE
Copying chat messages doesn't work when a nick has a NULL character in it

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#793]
Only the part before the NULL character gets copied.

**Comment by GrayHatter** [comment]
Who the f*** puts a NULL in their nick?

**Comment by tsudoko** [comment]
A long time ago strings in toxcore were null-terminated, some people (like [zetok](http://github.com/zetok)) haven't changed their names since then.

**Comment by stqism** [comment]
Also, irungentoo/toxcore doesn't put restrictions on names outside of size limits, meaning you could make your name a single terminal bell if you wanted.
