### ISSUE TITLE
μTox ignores system theme.

### ISSUE THREAD

**Issue by tot-to** [notsecure/uTox#796]
First of all, thanks for developing a useful software.

Here is an issue:
I use white on dark theme for gtk and qgtkstyle to make qt applications use the same theme. But μTox seems to not use any of these toolkits and therefore to ignore the system theme (in some sence it's a bug).
Moreover, I haven't find any theme support in μTox's options. This means that the default white (literaly 0xFFFFFF colour!!!) background is probably hardcoded and cannot be changed by user.

This just burns my eyes and makes it impossible to use μTox to chat, but only for audio/video. Please make it possible to use gtk/qt theme (imho, best solution) or to make a custom user theme.

**Comment by stqism** [comment]
>Please make it possible to use gtk/qt theme

This goes against the ideals uTox was created under.


(Note that uTox was designed to use as few dependencies as possible without toolkits or any of the features they provide, usually opting to spend months reinventing features from scratch over half a dozen lines of Qt)

**Comment by tot-to** [comment]
Hi, my suggestion is not to make any new dependencies, but just about the possibility to optionally follow their themes. In the same way as qgtkstyle doesn't makes qt dependent on gtk, this doesn't makes μTox dependent on gtk/qt, does it? I don't mean to use gtk widgets, just colours.

Anyway, internal theme will work fine. And again, I don't mean full-feautered theme support when one can design any widget. Just the abitily to choose background and text colours will make people like me happy. :)

I believe this must be extreamly easy to do and unlikely to go againts any ideals exept ideal of not providing any options to users and force everyone to defaults.

**Comment by fcore117** [comment]
works and looks very fine on my Ubuntu and runs light so i see no problem here. qTox has massive toolkit support if you need it.

**Comment by tot-to** [comment]
Sorry, I don't quite understand your phrase. If you know the way how to make light text on dark background in μTox's chat, please tell me. Otherwise I can't see your point at all.

**Comment by fcore117** [comment]
Do not know that but perhaps developers can comment is there plans for some integrated theme switer for uTox like dark, neutral and so on??

**Comment by tsudoko** [comment]
For now, even being able to customize colors of individual elements in one source file would be an improvement.

**Comment by muchweb** [comment]
+1 for ability to specify colours.

>uTox was designed to use as few dependencies as possible

Maybe to add an option for loading colours from the [X resources](http://en.wikipedia.org/wiki/X_resources)?

**Comment by tsudoko** [comment]
That's actually a nice idea.

**Comment by fcore117** [comment]
maybe not x resources but own cross platform simple theme switcher like dark mode, gray mode, monochrome mode and so on.

**Comment by tot-to** [comment]
fcore117, I think ideally a cross-platform software should try first to follow the local settings (which is of course platform-specific) and only in case if it can't (or if user wants it specifically) to use it's own theme selection mechanism.

X resources looks the best toolkit-independent and standart way in case of X.org server.

But for now, please just make it possible to change colours. No matter how.

**Comment by fcore117** [comment]
tot-to: mostly i meant color tone switching too, it would be great for night tone so eyes wont burn out.

**Comment by fcore117** [comment]
That i meant exactly, now i can change to dark theme, thanks who developed this.

**Comment by tot-to** [comment]
The dark theme is awesome! Almost exactly what I wanted.
Thanks a lot!

**Comment by GrayHatter** [comment]
closing please open a new issue if you think utox NEEDs to support .Xresources
