### ISSUE TITLE
Emoji from multi-color fonts are distorted

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#802]
I really don't know whether it's freetype's or uTox' fault.
![](http://a.pomf.se/bpncrw.png)
![](http://a.pomf.se/itpvoy.png)
When I first tried to paste an emoji into the text field, uTox hung. Couldn't reproduce it afterwards.
Gentoo, freetype 2.5.3, uTox theCoolkal/uTox@d3d4383, happens on 8904c1a as well

**Comment by Nsheppard01** [comment]
Horrifying.

**Comment by GrayHatter** [comment]
@tsudoko can you make this happen on demand?

**Comment by tsudoko** [comment]
What do you mean? It happens automatically when uTox uses NotoColorEmoji.ttf, might be the case with other fonts as well.

**Comment by GrayHatter** [comment]
@tsudoko this still happening? can you tell me how to make it happen

**Comment by tsdko** [comment]
Yes.
![](https://my.mixtape.moe/rwyjdf.png)
![](https://my.mixtape.moe/oiyyhj.png)

> can you tell me how to make it happen
> 
> It happens automatically when uTox uses NotoColorEmoji.ttf, might be the case with other fonts as well.
