### ISSUE TITLE
I can't see own messages in a group chat

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#803]
Using linux

**Comment by GrayHatter** [comment]
We're gonna need a little more information on this one?

**Comment by Sorunome** [comment]
I'm sorry I don't have any more information, it randomly happened that I couldn't see my own messages in a group chat while sometimes it still worked. It didn't follow any clear pattern and I didn't find out a way to trigger / stop it.

**Comment by Doom032** [comment]
So other people do see them? Usually it seems when you don't see your messages it means they're not reaching anyone.

**Comment by Sorunome** [comment]
Yes, other people can still see them.

**Comment by GrayHatter** [comment]
Can you select them as text?

Are the places where the text should be, and the text just seem invisible?

What OS? What bit? Where did you get the version you're running

**Comment by Sorunome** [comment]
64bit Linux.
And they are simply not there, no extra blank lines or something. I didn't try out if i can copypaste them out, though.

**Comment by GrayHatter** [comment]
@Sorunome did you try to resize the window by chance? Have you made it happen again?

**Comment by Sorunome** [comment]
I did not try that, I'll be sure to try the next time it'll happen (but i don't really use group chat frequently, so that can take some time)

**Comment by GrayHatter** [comment]
@Sorunome if you can get a much information next time it happens that would make this much easier to look into.

Some things to try if it happens:
  select text
  copy paste
  move window then resize (the order is important for how redraws happen)
  switch to a different group and back
  switch to a friend and back
  how many people are in chat
  what happens to new messages vs old
  someone joins or leaves
  network status
  version number (it should be in your title now)

**Comment by GrayHatter** [comment]
@Sorunome I'm going to close this as stale, re-open if you can make it happen on demand, or can provide more information about when it happens.
