### ISSUE TITLE
uTox updater is easily skipped accidentally

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/uTox#807]
1. Start a newly downloaded uTox on Windows
2. Pin to taskbar

From now on, every time uTox is started from the task bar, the updater is skipped because it is another application.

An easy workaround to this would be to add a --no-update flag to utox, which the updater calls after updating. If uTox is started without the --no-update flag, it will quit and run the updater. Of course, this is just a suggestion, but many Windows user pin applications they use often to the task bar, which is not something that should break the updater.

**Comment by GrayHatter** [comment]
@irungentoo do you know what he means? I remember you explaining this to me, but I've already forgotten what you said.

**Comment by tsudoko** [comment]
When running something on Windows >=7, you can pin running applications to the taskbar, making shortcuts for them. Pinning uTox pins only the main executable, that makes the updater completely skipped since uTox doesn't call it from itself.

**Comment by GrayHatter** [comment]
oh right, yeah, that's exactly what he said...

this is something that needs the decision if utox should always be a stand alone exe, or if it should try to install itself to the OS,
