### ISSUE TITLE
Unable to change input device

### ISSUE THREAD

**Issue by agilob** [notsecure/uTox#809]
When user clicks on list of devices, list appears, when user moves cursor list immediately disappears and user is not able to change input device.

happens on Windows.

**Comment by irungentoo** [comment]
Don't release the mouse button.

**Comment by agilob** [comment]
When user releases the mouse button device under cursor is not being selected. Tried that, also we tried changing with arrow keys.

**Comment by nachfuellbar** [comment]
@irungentoo i don't think that's user friendly espacially on notebooks

**Comment by theCoolkal** [comment]
Right-click menus seem to work in a way where you have to release the mouse button and afterwards click the menu item.  The drop-down menus are the opposite and you have to keep the mouse button held and release it over the menu item.  Perhaps it would be a good idea to make this more consistent and maybe support both actions for both drop-down menus and right-click menus.

**Comment by tsudoko** [comment]
@theCoolkal That's what I suggested in #233

**Comment by GrayHatter** [comment]
dup of above, and either way, this is a requirement for android support (currently)
