### ISSUE TITLE
URLs aren't highlighted when they're not separated

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#815]
They're still clickable, though.
![](http://a.pomf.se/nunryg.png)

**Comment by GrayHatter** [comment]
@tsudoko do you think It's better to highlight them, or not turn them into clickable links? I'm leaning towards the latter, for links that are attached to other text before them.

**Comment by tsudoko** [comment]
I think the latter is a better choice.
Related issue: when there's a link and there's some special character directly after it, it's treated as a part of the link.
Example: `(source: https://a.pomf.se.nunryg.png)` ⇒ ![](http://a.pomf.se/cguydz.png)
