### ISSUE TITLE
Tooltips needs to be fixed, they currently interfere with drawing avatars and other hdc conflicts

### ISSUE THREAD

**Issue by GrayHatter** [notsecure/uTox#821]
Please see 
#792 
#777 
#798 
#653 
and commit 
97aae0e2

**Comment by ElLamparto** [comment]
I tried the version of today (09/02) and the avatars still keep dissapearing. Staying with the version of 8 January..

**Comment by GrayHatter** [comment]
should be fixed in #859

**Comment by GrayHatter** [comment]
@ElLamparto can you duplicate the tooltip issues in #859
