### ISSUE TITLE
uTox crashes when I try to video call

### ISSUE THREAD

**Issue by kozross** [notsecure/uTox#825]
When I try to video-call a friend of mine, I get the following messages in the terminal before uTox crashes:

start sending video
start webcam
A/V SelfMediachange (0)
Saved data
4550
705
534
735
1037
1431
711
2403
1076
1288
3213
2270
2272
5297
1520
5281
1283
1558
6441
2242
1567
2813
1446
2128
2284
2024
1735
2394
1752
2377
1889
2064
1931
2081
1958
2027
2096
2177
1791
2172
1659
2319
2193
2428
2059
1923
1962
2037
5582
1993
1979
2128
1900
2237
1790
2147
2251
2032
1789
2135
1799
2199
1912
2100
1792
A/V PeerMediachange (0)
Segmentation fault (core dumped)

**Comment by GrayHatter** [comment]
Can you upgrade to the latest version and try again?

**Comment by GrayHatter** [comment]
@kozross closed as stale, re-open if you can make it happen again!
