### ISSUE TITLE
old problem, saving or opening brings data files

### ISSUE THREAD

**Issue by fcore117** [notsecure/uTox#828]
Please fix that sometimes, not always uTox copies history files or profile .tox when opening or saving files. In same folder where object is saved or opened.

**Comment by GrayHatter** [comment]
@fcore117 are you saying uTox reads from the .config directory, and then tries to save in the 'pwd' of where utox was started?

If so are you sure your file permissions are set correctly for that directory, and that you only have one instance running?

Otherwise I'm going to need a lot more information...

**Comment by fcore117** [comment]
perhaps irungentoo remembers that last year there was issue when utox saved data file when using open or save dialogs with utox? this currently reminds very much that old bug.

**Comment by GrayHatter** [comment]
@fcore117 I still don't understand, could you explain this in a lot more detail?

**Comment by fcore117** [comment]
https://mega.co.nz/#!3ZhgEIDB!T8xYV_Odmnjsj77xpnnjkvbvIAtsYHkad3WvPMB8-7s

this problem is on ubuntu too, sometimes tox copies just a profile .tox in same way or log file.

**Comment by GrayHatter** [comment]
@fcore117 that link isn't really helpful to me... I assume it's a video? I suggest youtube

**Comment by fcore117** [comment]
do not know better way to help anymore, you cannot download this?

**Comment by GrayHatter** [comment]
It crashed by browser twice, if you can't upload it to youtube, maybe you might be able to discribe step by step what utox is doing vs what you expect it to do?

**Comment by fcore117** [comment]
suggest me upload site that works for you or transport way, i do not know to describe better than video

**Comment by fcore117** [comment]
It was issue with official portable command, now it should be fixed.
