### ISSUE TITLE
uTox crashes on any copy/paste operation

### ISSUE THREAD

**Issue by pcbmaster** [notsecure/uTox#829]
The program 'utox' received an X Window System error.
    This probably reflects a bug in the program.
    The error was 'BadAtom (invalid Atom parameter)'.
      (Details: serial 25524 error_code 5 request_code 22 minor_code 0)
      (Note to programmers: normally, X errors are reported asynchronously;
       that is, you will receive the error a while after causing it.
       To debug your program, run it with the --sync command line
       option to change this behavior. You can then get a meaningful
       backtrace from your debugger if you break on the gdk_x_error() function.)
    AL lib: (EE) alc_cleanup: 1 device not closed

I'm using 

    Linux discord 3.18.5-1-ARCH #1 SMP PREEMPT Fri Jan 30 07:31:50 CET 2015 x86_64 GNU/Linux

**Comment by irungentoo** [comment]
Fixed in: https://github.com/notsecure/uTox/commit/8ed46165ee44d945e3dd4d63d4d743ecfc790252
