### ISSUE TITLE
Make uTox obey default programs

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#830]
Make uTox obay default programs set in ~/.config/mimeapps.list

**Comment by tsudoko** [comment]
It just fires up `xdg-open`, what's wrong exactly?

**Comment by Sorunome** [comment]
I set it in my mimeapps to use gwenview on images, but utox starts it with gimp

**Comment by Sorunome** [comment]
Ok this is probably just me messing up so nevermind
