### ISSUE TITLE
notsecure, are you still utox's maintainer?

### ISSUE THREAD

**Issue by SILENCE-GIVES-CONSENT** [notsecure/uTox#836]
You haven't shown any sign of activity since October.
Is everything okay?
Why have you (apparently) abandoned Tox? 
We are worried.

**Comment by SILENCE-GIVES-CONSENT** [comment]
Does it have anything to do with the current situation of the Tox Foundation exposed in the last weeks?
Just post here, even if just to say "hello". We need to know if you are fine.

**Comment by irungentoo** [comment]
What is this?

**Comment by GrayHatter** [comment]
> We are worried.

trolling you mean? 

> Even if it's not the perfect place, it's the least worst place and the most appropriate one.

It is probably the worst place...

> The community is worried,

no we're not

**Comment by SILENCE-GIVES-CONSENT** [comment]
@GrayHatter 
Speak for yourself, but I'm a long time acquaintance of notsecure and find myself worried about his disappearance since October.
I'm even more afraid when I think about the recently revealed unethical situation of the Tox Foundation. Could he have suffered the same as Proplex and other ex-developers?
notsecure, are you okay?

**Comment by GrayHatter** [comment]
> Speak for yourself, but I'm a long time acquaintance of notsecure 

Long time friend with no way of contact? 

> I'm even more afraid when I think about the recently revealed unethical situation of the Tox Foundation. 

[Citation Needed]

**Comment by SILENCE-GIVES-CONSENT** [comment]
> Long time friend with no way of contact? 

Long time acquaintance, not friend. Don't put words on my mouth, please.
 We used to talk through IRC from the beginning of 2013 until October 2014. Since then he's mysteriously disappeared. I thought he was busy with school or something, but since it's been so long without *any* activity (not on Github or IRC), I got worried.
Has he really abandoned Tox? Why won't he give the minimum sign of being okay?

>[Citation Needed] 

Stop trolling, I being afraid needs no "citation". I am afraid about him and I'm saying I'm afraid. What the hell do you mean with [Citation Needed]? Is this an attempt of trolling?

**Comment by LittleVulpix** [comment]
@irungentoo Please make this convo for collaborators only so the trolls cannot comment
@SILENCE-GIVES-CONSENT Go to tox-foundation github for trolling

**Comment by SILENCE-GIVES-CONSENT** [comment]
@LittleVulpix
That's fine, as long as notsecure is still able to comment here.
