### ISSUE TITLE
No show icon in debian/ubuntu lxde (Utox 0.2.m) 

### ISSUE THREAD

**Issue by susobaco** [notsecure/uTox#838]
No minimize, no show icon.

**Comment by GrayHatter** [comment]
What do you mean no minimize/no show?

**Comment by susobaco** [comment]
OK, when you start the application, the icon does not appear in the systray. When the minimize option is ordered, does not appear

**Comment by kriswema** [comment]
That's right, with the new Close to Tray and Start in Tray functions activated, uTox simply won't appear on system trays that aren't supported.

**Comment by shalnoff** [comment]
Yepp. Same thing in Mate (Linux Mint). No window icon, no tray minimising.

**Comment by aceberg** [comment]
Xfce (ubuntu 14.04) no tray icon too

**Comment by GrayHatter** [comment]
uTox currently doesn't support tray in linux. That's currently a windows only feature. 

So is this issue that uTox wont go to tray? Or that when start in tray is enabled, uTox doesn't open any window at all?

If uTox doesn't open at all, can you confirm that uTox is actually still running in the background?

**Comment by aceberg** [comment]
When start in tray is enabled, uTox starts as usual opening it's window, no tray.

When close to tray is enabled, closing uTox window kills it. There is no process utox in background.

**Comment by GrayHatter** [comment]
dup of #208
