### ISSUE TITLE
Settings are reset after restart the app

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#839]
All settings (interface language, logging) are reseted to default after restart app.

**Comment by irungentoo** [comment]
What operating system are you on?

**Comment by redmanmale** [comment]
@irungentoo Win7 x64.

**Comment by GrayHatter** [comment]
this shouldn't happen in the latest version. Can you install the lastest version an report back if you can still make this happen?

**Comment by redmanmale** [comment]
@GrayHatter 
Confirm fix. In latest version (0.2.o) it didn't happen anymore. Thanx.
