### ISSUE TITLE
regression: copying text out of utox is broken

### ISSUE THREAD

**Issue by aaannndddyyy** [notsecure/uTox#840]

**Comment by irungentoo** [comment]
Operating system?

What are you trying to copy?

From where exactly?

**Comment by aaannndddyyy** [comment]
- trisquel gnu/linux. (also happened on non-debian distro)
- text messages or links in groupchat text messages, by highlighting the text, right mouse click, choosing either 'copy' or 'copy (no names)' or ctrl+c
- from the dialogue part of the groupchat (where your and others' messages appear).
It does work in 1:1 though.

**Comment by Doom032** [comment]
I've been having the same issue recently. On Xubuntu and Lubuntu. Only in groupchats. Both in the main groupchat and in groupchats I make.
