### ISSUE TITLE
[request] Chat enhancements.

### ISSUE THREAD

**Issue by Nsheppard01** [notsecure/uTox#841]
It's nice that uTox has /me and >greentext but more features would be nice. Consider supporting markdown, or at least parts of it (headings and inline tables might be a bit much)

As for smilles, I hate it when I try to draw Ascii art smilies, and they get converted into ugly gifs, avoid automatic smilies. Emoji are okay because they have unambiguous synatax, but if I type :) I shouldn't see it turned into something else.

**Comment by tsudoko** [comment]
I don't understand, uTox doesn't convert text emoticons into anything.

**Comment by Nsheppard01** [comment]
It dosn't and it should stay that way. I'm requesting that that particular change never be made.
If people want smilies, they should use Emoji or Ascii art, not a combination of the two.

**Comment by tsudoko** [comment]
I agree.

**Comment by Nsheppard01** [comment]
Another idea, change the behavior of /me statements

Right now all they do is turn the text blue. Wouldn't it be better if it turned the username blue as well, and maybe moved it to the other side of the margin so it looks different from a normal post?
