### ISSUE TITLE
µTox segfaults on hardened Gentoo if compiled with support for filter_audio

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#844]
https://gist.github.com/zetok/66608746e388b9b1a892 ← bt from some time ago

https://gist.github.com/zetok/49d56c198615cb40b46c ← bt && bt full on newest µTox & core
https://gist.github.com/zetok/c501c1bb30272fed6c04 ← build with -fsanitize=address
https://gist.github.com/zetok/d91f59b2ef3d582487f8 ← build without -fsanitize=address

**Comment by DarkLinkXXXX** [comment]
Same here.

**Comment by irungentoo** [comment]
can you build it with: -g to try to get a proper backtrace?

**Comment by zetok** [comment]
I no longer have any problem after using vanilla GCC instead of hardened one:
```bash
gcc-config x86_64-pc-linux-gnu-4.8.3-vanilla
. /etc/profile
emerge libfilteraudio utox

# utox worked
```


When I switched back to hardened GCC and recompiled µTox and filter_audio, segfault was still reproducible.

====
and yes, I have everything compiled with ``-ggdb``

**Comment by emanueLczirai** [comment]
From my tests right now, if libfilteraudio is compiled with hardened it will segfault; but if compiled with vanilla it will work ok. (regardless of utox being compiled with hardened or vanilla) (everything else that they depend upon is compiled with hardened compiled)

**Comment by CM3PTb** [comment]
I installed uTox last night and it did not crash on start up.  This issue seems to be resolved now, as I'm using: 
 [1] x86_64-pc-linux-gnu-4.9.3 *
 [2] x86_64-pc-linux-gnu-4.9.3-hardenednopie
 [3] x86_64-pc-linux-gnu-4.9.3-hardenednopiessp
 [4] x86_64-pc-linux-gnu-4.9.3-hardenednossp
 [5] x86_64-pc-linux-gnu-4.9.3-vanilla

**Comment by zetok** [comment]
Since it works, closing. If still reproducible, should be reported at new upstream, at https://github.com/GrayHatter/uTox .
