### ISSUE TITLE
close to tray setting resets on restart

### ISSUE THREAD

**Issue by P8ntBal1551** [notsecure/uTox#846]

**Comment by P8ntBal1551** [comment]
It doesn't seem to save the setting when i completely close and restart the program

**Comment by GrayHatter** [comment]
Does it close to tray as expected when you reset it from settings?

**Comment by P8ntBal1551** [comment]
Ok, so I re-installed it and now seems to work as it is supposed to, so you can close this. I'm sorry for the vagueness of my previous post, I was on my phone in class and was 70% asleep.

What I meant to say is that - I have it in my start-up folder on windows. When it started up with my system the "Close to tray" and "Start in tray" settings reset back to No.

So thanks for your help and sorry to waste time.
