### ISSUE TITLE
utox Makefile needed -lrt added to LDFLAGS to compile

### ISSUE THREAD

**Issue by dennisnez** [notsecure/uTox#852]
I had to add "-lrt" to the LDFLAGS in my utox Makefile in order to get it to compile. Otherwise, compilation would fail with:

   main.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'

**Comment by kytvi2p** [comment]
FWIW I've only seen this on the Raspberry PI w/ Raspbian
