### ISSUE TITLE
Trouble displaying yuv420 video

### ISSUE THREAD

**Issue by dennisnez** [notsecure/uTox#853]
My utox has trouble displaying YUV420 formatted video, which mplayer tv:// plays as:

Selected driver: v4l2
 name: Video 4 Linux 2 input
 author: Martin Olschewski <olschewski@zpr.uni-koeln.de>
 comment: first try, more to come ;-)
v4l2: your device driver does not support VIDIOC_G_STD ioctl, VIDIOC_G_PARM was used instead.
Selected device: Dummy video device (0x0000)
 Capabilities:  video capture  read/write  streaming
 supported norms:
 inputs: 0 = loopback;
 Current input: 0
 Current format: YUV420
v4l2: ioctl set format failed: Invalid argument
tv.c: norm_from_string(pal): Bogus norm parameter, setting default.
v4l2: ioctl enum norm failed: Inappropriate ioctl for device
Error: Cannot set norm!
Selected input hasn't got a tuner!
v4l2: ioctl set mute failed: Invalid argument
v4l2: ioctl query control failed: Invalid argument
Opening video decoder: [raw] RAW Uncompressed Video
Movie-Aspect is undefined - no prescaling applied.
VO: [xv] 320x240 => 320x240 Planar I420 
Selected video codec: [rawi420] vfm: raw (RAW I420)-

This video (device/stream) is provided by a useful utility called "yuv4mpeg_to_v4l2":

  https://github.com/umlaeute/v4l2loopback/blob/master/examples/yuv4mpeg_to_v4l2.c

It displays it with weird video artifacts (eg. green hue and vertical bars):

![yuvpreview](https://cloud.githubusercontent.com/assets/3186040/6321667/3940290e-bad1-11e4-9281-96bcefebabe7.jpg)

**Comment by dennisnez** [comment]
I changed the pixelformat from V4L2_PIX_FMT_YVU420 to V4L2_PIX_FMT_YUV420 (which is what my yuv4mpeg_to_v4l2 program was outputting) in utox's xlib/v4l.c (line 67), and that got rid of most of the distortion -- now the image is crisp, but the colors (reds and blues) are swapped. (Again, mplayer can play it fine.)

**Comment by dennisnez** [comment]
Here's what it looks like after the YVU to YUV tweak...
![actuallyis](https://cloud.githubusercontent.com/assets/3186040/7447310/dc3942f2-f1c3-11e4-9f90-f6d65935c41e.jpg)
![shouldbe](https://cloud.githubusercontent.com/assets/3186040/7447309/dc338ee8-f1c3-11e4-9359-a17daf32e44d.jpg)

**Comment by irungentoo** [comment]
are you sure this is a bug with uTox and not libv4lconvert?

**Comment by dennisnez** [comment]
Yea, I'm pretty sure the problem is not with libv4lconvert (media-libs/libv4l). Things work fine with Ekiga, which uses libv4l (via ptlib).

**Comment by dennisnez** [comment]
Here's one way to test this bug, using mplayer and the tiny v4l2loopback driver (which comes with the useful yuv4mpeg_to_v4l2 utility):

mkfifo whatever
yuv4mpeg_to_v4l2 < whatever &
mplayer videofile.avi -vo yuv4mpeg:file=whatever

And then test this dummy video device with utox.

**Comment by dennisnez** [comment]
Seems to be fixed with utox 0.3.2 !
