### ISSUE TITLE
ssh x forwarding

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#854]
if i start utox via ssh x forwarding i don't get any text, everything is just blank

**Comment by GrayHatter** [comment]
`echo $display` please

**Comment by Sorunome** [comment]
That gives me a blank line.

Also other X applications work fine

**Comment by tsudoko** [comment]
I think he meant `echo $DISPLAY`.

**Comment by Sorunome** [comment]
[sorunome@sorunome-desktop ~]$ echo $DISPLAY
localhost:10.0

**Comment by GrayHatter** [comment]
I'm going to need as much information as you can supply, I just tested this
and utox runs as expected with Xforwarding

**Comment by Sorunome** [comment]
the ssh server runs archlinux, as window manager awesome, no DE. I use the catalyst drivers.

The ssh client also runs archlinux, there i run XFCE4, though, and also the catalyst drivers.

Any more information needed?

**Comment by GrayHatter** [comment]
login to you server and `cat /etc/ssh/sshd_config`

what ssh command are you using to connect?

What version of utox are you trying to run?

Can I get a screen shot of the missing text?

**Comment by Sorunome** [comment]
sshd config: http://pastebin.com/vQTRDLvC
ssh command: ssh -X <host>
utox version: utox-git-r1185.gb3cd0a0-1   (taskbar says 0.2.n)
Screenshot: https://img.ourl.ca/Screenshot_2015-02-27_14-21-04.png

Also ssh X forwarding works fine with other applications such as hexchat

**Comment by GrayHatter** [comment]
what happens if you use -Y instead of -X

**Comment by Sorunome** [comment]
Oh, that is working, thank you!

**Comment by GrayHatter** [comment]
@Sorunome Don't forget to close this!

**Comment by tsudoko** [comment]
But isn't the issue still there if -X doesn't work properly?

**Comment by Sorunome** [comment]
But -Y allows, according to the man page, trust forwarding.

       -X     Enables X11 forwarding.  This can also be specified on a per-host basis in a configuration file.

              X11 forwarding should be enabled with caution.  Users with the ability to bypass file permissions on the remote host (for the user's X authorization database) can access the local X11  display  through  the  forwarded
              connection.  An attacker may then be able to perform activities such as keystroke monitoring.

              For this reason, X11 forwarding is subjected to X11 SECURITY extension restrictions by default.  Please refer to the ssh -Y option and the ForwardX11Trusted directive in ssh_config(5) for more information.


       -Y     Enables trusted X11 forwarding.  Trusted X11 forwardings are not subjected to the X11 SECURITY extension controls.
