### ISSUE TITLE
Can't drag contacts into group chat

### ISSUE THREAD

**Issue by peacememories** [notsecure/uTox#855]
To invite a contact to a group chat, uTox tells me to drag the contact onto the group chat. If i click to drag the contact, though, the contacts chat gets selected, meaning I can't drag the contact into the group chat window.

uTox 0.2.n

**Comment by kriswema** [comment]
You have to drag it onto the group chat entry on the left.

**Comment by dvapelnik** [comment]
@kriswema I have been dragging the contact to the position of group chat, but the user was not added to the group chat
uTox: v0.2.n
OS: Ubuntu 14.04.2

**Comment by serfian** [comment]
same problem

**Comment by irungentoo** [comment]
click on the friend, then drag the friend on the group chat entry in the friends list.

**Comment by GrayHatter** [comment]
@irungentoo yeah, It's somewhat problematic now, I can duplicate this one...

**Comment by GrayHatter** [comment]
scratch that, It works as it should.

@dvapelnik @serfian there may be some lag as utox tries to connect to that friend before it's shows them or any other friend as added.

Try adding a friend to a new group a little slower, and see if you still have this problem. If so could you make sure you're on the newest version of uTox and make a video of your drag and drop not working?

**Comment by dvapelnik** [comment]
@GrayHatter yeah, I thought about the same and was advised to upgrade the client to my version. after that managed to join a group chat. the problem was the version of the client
