### ISSUE TITLE
Sometime the DPI change to Huge (250%) with starting

### ISSUE THREAD

**Issue by tux3** [notsecure/uTox#856]
As reported by Azlux on #tox.

```
<Azlux> litlle bug on µtox, sometime, i don't kown why, the DPI change to Huge (350%) with starting
<Azlux> and huge is 250% ... rhaa typing error
```

**Comment by GrayHatter** [comment]
@tux3 can you find out if he can repeat it? (OS, version, how he's starting utox)

**Comment by tux3** [comment]
@GrayHatter I haven't seem him again since, so I don't think I'll be able to get more info, sorry.

**Comment by GrayHatter** [comment]
@tux3 close this?

**Comment by tux3** [comment]
Well, that's your call. I just reported someone else's bug.
