### ISSUE TITLE
Setup official PPA

### ISSUE THREAD

**Issue by muchweb** [notsecure/uTox#862]
To create official PPA on a launchpad. `deb` should contain correct `.desktop` entry and an icon.

Ubuntu users are used to convenience and installation should be made easy.

/cc @irungentoo

**Comment by aaannndddyyy** [comment]
https://launchpad.net/~i2p.packages/+archive/ubuntu/i2p has nice packaging

**Comment by GrayHatter** [comment]
I'm going to close this until someone can convince me that uTox should have our own distribution network instead of letting distro maintainers do it live EVERY OTHER app
