### ISSUE TITLE
Setup CI for 'Github releases'

### ISSUE THREAD

**Issue by muchweb** [notsecure/uTox#866]
To set up the build system to upload binaries to 'Github releases' page ([related SO answer for Jenkins](http://stackoverflow.com/a/24618910)).

This will allow users easy access to historical builds.

**Comment by TheLastProject** [comment]
Historical builds are already available on [Jenkins](. See the [linux_amd64 build] as an example.

**Comment by muchweb** [comment]
@TheLastProject, yes, I was aware of that, but some users are used to check releases page first. It makes it a [little more user friendly](https://github.com/atom/atom/releases).

**Comment by GrayHatter** [comment]
Github has said that they don't want to be a source to distribute binaries. Unless someone can correct me, I'd just assume not upload binaries to GH repo, with a possible exception of stables releases.

**Comment by muchweb** [comment]
>Github has said that they don't want to be a source to distribute binaries. Unless someone can correct me, I'd just assume not upload binaries to GH repo, with a possible exception of stables releases. 

'Github releases' is a page, separate from repo, that is meant for binaries. See [one of Github's own projects](https://github.com/atom/atom/releases) for an example.

**Comment by ReAzem** [comment]
> Unless someone can correct me, I'd just assume not upload binaries to GH repo, with a possible exception of stables releases.
It is a common practice to publish binaries for all tags. ([example](https://github.com/syncany/syncany/releases))
