### ISSUE TITLE
Feature request: configurable notifications

### ISSUE THREAD

**Issue by nachfuellbar** [notsecure/uTox#870]
Configurable notifications would be great. For now i only mention notification types for Windows

types of notifications:
- flashing window (on top of systray)
- flashing taskbar icon
-  audio notification

notification trigger:
- chat message
- incoming call
- incoming file transfer
- file transfer complete
- friend request

Each notification trigger should have each type of notification as option

@GrayHatter

**Comment by GrayHatter** [comment]
dup of #624
