### ISSUE TITLE
"inline.png" filename and prompt-less over-writing of files

### ISSUE THREAD

**Issue by codicusmaximus** [notsecure/uTox#878]
A friend sent me multiple pasted images and/or screenshots/screensnips.  They were all named inline.png, I saved them all and just hit enter on the Save As prompt and it did not warn me that I was overwriting previous files.  This was on Windows.  The user should not be expected to provide file names for all of these "inline.png" files and remember what file names are taken and which aren't.  The solution here is probably going to be to make the file something like "Inline - YYMMDD MMSSms.png".

This is the first issue I am going to work on submitting a patch for since it's very easy to fix and I will get to set up a build environment for uTox.  I am not sure where comments like this would normally go, I am new to using GitHub (and public project collaboration in general)

**Comment by GrayHatter** [comment]
@codicusmaximus let me know if you need some help getting a build environment set up!

in the meantime, I was able to solve an issue similar to this so if you need help fixing this or creating a PR let me know!
