### ISSUE TITLE
Idle detection

### ISSUE THREAD

**Issue by codicusmaximus** [notsecure/uTox#880]
The client does not do any form of idle detection on Windows and possibly other environments.  It should have a configurable amount of idle time before it sets you as "orange" or otherwise some kind of idle state.

**Comment by tsudoko** [comment]
Duplicate of #604?

**Comment by codicusmaximus** [comment]
Whoops -- I did do a search for "idle" to see if there was already an issue open but didn't find anythng.  Closing
