### ISSUE TITLE
Unlabeled entries in the options menu

### ISSUE THREAD

**Issue by Encrypt** [notsecure/uTox#881]
Since the last update -- that is to say after the pull request #869 made by @muchweb and @GrayHatter has been merged -- the menu has unlabeled entries after the "Theme" option.

These were the "start in tray" and "close to tray" options if I remember well.

Here is a screenshot, Ubuntu 14.04

![unlabeled_entries](https://cloud.githubusercontent.com/assets/9038199/6526215/99f4fdbe-c40f-11e4-9a65-f4d56839fb72.png)

**Comment by fcore117** [comment]
i wanted to report this too but yes i have same.

**Comment by GrayHatter** [comment]
this is fixed is master
