### ISSUE TITLE
"Friend typing" is now written in black instead of grey

### ISSUE THREAD

**Issue by Encrypt** [notsecure/uTox#882]
Since the last update -- that is to say after the pull request #869 made by @muchweb and @GrayHatter has been merged -- the "friend typing" notification is now black instead of grey.

Here is a screenshot, Ubuntu 14.04

![friend_typing](https://cloud.githubusercontent.com/assets/9038199/6526296/9e73520e-c410-11e4-861c-ec1b62ba72fb.png)

**Comment by tsudoko** [comment]
Happens with edit hints in "search friends" and proxy options fields as well.
