### ISSUE TITLE
uTox segfaults when trying to remove a friend after a failed transfer

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#896]
uTox 57f2fa8
[Backtraces](https://gist.github.com/tsudoko/0a77640085b1c54daf3c)
Reproducible: always
I might test it further later, steps are very specific for now
 1. Add uTox id from Antox 0.15.68
 2. Start sending a large file from Antox to uTox
 3. Wait for the transfer to fail
 4. Close Antox (the id goes offline)
 5. Remove the Antox id

Update: works with any client, just cancel the transfer from it and remove the client from uTox after it goes offline.

**Comment by GrayHatter** [comment]
@tsudoko can you pull my file_resume branch and test this segfault?

**Comment by tsudoko** [comment]
Can't reproduce.
