### ISSUE TITLE
Translation: Duplicate strings

### ISSUE THREAD

**Issue by kriswema** [notsecure/uTox#898]
What's the difference between ``CONTACTS_FILTER_EDIT_HINT`` and ``SEARCHFRIENDS``? They're both translated as "Search friends". ``SEARCHFRIENDS`` doesn't seem to be in use.

**Comment by GrayHatter** [comment]
The former will only be used as the hint text for filtering friends, the latter is general text. 

You're right and I would remove SEARCHFRIENDS, but it would break stuff, and I see no real reason to remove it right now... Unless you can think of a good reason?

**Comment by kriswema** [comment]
I found an inconsistent German translation, that's why I was wondering. Duplicate strings might harbour some confusion in the future.

**Comment by GrayHatter** [comment]
well, that is a good reason...
