### ISSUE TITLE
uTox Android

### ISSUE THREAD

**Issue by nachfuellbar** [notsecure/uTox#905]
Utox doesn't scale on Android (FHD Display); can't use button on right top
![screenshot_2015-03-12-21-17-46](https://cloud.githubusercontent.com/assets/5123484/6627351/ce7a9fb0-c8fd-11e4-9e25-49567321c6d4.png)
can't scroll; IP settings fields after "Language"
![screenshot_2015-03-12-21-18-06](https://cloud.githubusercontent.com/assets/5123484/6627356/d323d860-c8fd-11e4-8ee1-acf9f3f46051.png)
can't close with "back" button; only minimize and close in recent apps

Update 1:uTox on Android uses to much energy
![screenshot_2015-03-13-08-11-09](https://cloud.githubusercontent.com/assets/5123484/6638700/f7e6c5b4-c988-11e4-9cc0-5db33fe6c4c7.png)

Update 2: i just saw you can scroll when you press the scrollbar on the right side; after changing settings you can't scroll anymore till you change to e.g. "Switch profile". Options like "Start in Tray" shouldn't be on android version

**Comment by nachfuellbar** [comment]
uTox on Android uses to much energy
![screenshot_2015-03-13-08-11-09](https://cloud.githubusercontent.com/assets/5123484/6638700/f7e6c5b4-c988-11e4-9cc0-5db33fe6c4c7.png)

**Comment by GrayHatter** [comment]
@nachfuellbar each of these should be it's own issue...

**Comment by GrayHatter** [comment]
Stale, 

And android is still experimental
