### ISSUE TITLE
No notification from group chats.

### ISSUE THREAD

**Issue by Nsheppard01** [notsecure/uTox#907]
There is no notification of new incoming messages from a group chat. This causes me and my friends to miss conversations. Please add them.

**Comment by Encrypt** [comment]
That's a good idea indeed...
Which kind of notification would you like on groupchats?

Would you like the same behaviour as IRC, that is to say you would get a DBus notification when your name is mentionned (that may be difficult to implement though).

Give us more details ;)

**Comment by GrayHatter** [comment]
@Encrypt if you want to work on this look at #624 

closed as dup

**Comment by Nsheppard01** [comment]
Is this really a dup? That topic is about notification sounds. I'd just like there to be some kind of visual indication that people are talking in a group chat like there is for regular chat messages.

**Comment by GrayHatter** [comment]
Ahh, I misunderstood what you were asking... either way this one came first, #388 +1 it to get it more attention!
