### ISSUE TITLE
Theme not saved 

### ISSUE THREAD

**Issue by wups** [notsecure/uTox#908]
The new theme option does not get saved yet in utox_save.

I have also seen that some effort was made to convert an older save version. I think something like this is not required in such an early development state (alpha). It already starts to bloat the souce code.
Would it possibly be worth to find a file format, which is more robust against changes or additions?

**Comment by tsudoko** [comment]
Is there a robust binary format that doesn't require a whole library to use? One of uTox' goals is to have as few dependencies as possible.

**Comment by raisingw** [comment]
Just to confirm that the theme setting does not save on Ubuntu 14.10 (can't get my preferred dark theme to stick), but DOES save on Windows XP, weirdly.

**Comment by GrayHatter** [comment]
@wups if you're willing to submit a PR to change the utox_save code I'm happy to look into it. But @tsudoko is right, uTox's goal is to be as small and light weight as possible.

**Comment by stal888** [comment]
this can be closed, i fixed theme saving for xlib in 3c447f93f8e0ccf31703a9497e545ba37dccd7b6
