### ISSUE TITLE
Suggestion: Move typing notification to friendslist

### ISSUE THREAD

**Issue by wups** [notsecure/uTox#909]
The typing notification directly in the chatarea is - at least to me - very annoying.
My suggestion is to move it to the friendslist and display it as a change of the status icon of the respective friend.
This also has the advantage, that all typing notifications can be displayed, not only the one of the currently active chat-window.

Possible graphical representations could be changing the color of the icon from green (online) to blue, or putting "..." under the icon.

I am willing to implement that in uTox, but I wanted to ask, what you think about it, first.

**Comment by nachfuellbar** [comment]
I think typing notifications should stay in the chatarea (because you see if someone is typing while you write your own message)
Typing notifications should be optional (if you want them in chatarea or friendlist or maybe both)

**Comment by naryl** [comment]
IMO friendist notification is not as annoying nor as useful so you can make them enabled at all times.
Chatarea notifications should be optional but it's a non-essential option so it shouldn't occupy space on the Settings tab.

**Comment by 2a03** [comment]
What is **really** annoying is the fact that *whole page of previous messages scrolls up while typing notification appears and then scrolls back*. Either it should happen once and then be replaced with whitespace without scrolling back, either there always should be a blank line after last message, to be replaced with «typing» when notification arrives.

**Comment by GrayHatter** [comment]
From the last time this was bumped the typing notifications were changed.  If you really want this still, open a new issue for it...
