### ISSUE TITLE
Doesn't automatically detect sound input/output devices.

### ISSUE THREAD

**Issue by norgor** [notsecure/uTox#911]
As the title says, it doesn't regularly check for input/output which forces the user to restart uTox everytime he/she plugs in a headset.

**Comment by shalnoff** [comment]
confirm, very important issue especially if you use changable headset. 
It would be great to switch the audio IN/OUT source to the "new one" automatically and get back to the previous one if the device was unpluged.

**Comment by GrayHatter** [comment]
I think this is fixed, if not please reopen here https://github.com/GrayHatter/uTox/issues
