### ISSUE TITLE
Can't screen share second screen LEFT of main screen (Windows)

### ISSUE THREAD

**Issue by sinni800** [notsecure/uTox#912]
When I choose a rectangle on a different screen to record with Tox, this happens:

![image](https://cloud.githubusercontent.com/assets/2879097/6642257/99fe984e-c9a3-11e4-947c-2257b6020575.png)

It will choose the correct window size, but nothing will be there.

This only happens on screens that are on the *left* of the main screen, though. The rectangle will, weirdly, be drawn not where my mouse is, but rather... off-set from it. The chosen coordinates still work though (the ones I chose with my mouse cursor, not the ones actually in the rectangle)

![image](https://cloud.githubusercontent.com/assets/2879097/6642448/f9713f56-c9a4-11e4-899f-4fb1270105ad.png)

(Note where the mouse and where the rectangle is!)

If the main screen is the leftmost one, everything is fine.

I think the fix is to allow pixel dimensions that start *below zero*... I have fiddled with the Winapi and I think this is it. I want to prove this with a little tool I have made that incidentially lists the screens *as they come from the WinApi*

![image](https://cloud.githubusercontent.com/assets/2879097/6642495/45a54f66-c9a5-11e4-94dc-7903c9243ff7.png)

When opening a new window (CreateWindowEx?), the dimensions there start from the *leftmost screen*. When recording the screen, the dimensions actually go below zero (I hope I got this right).

**Comment by tsudoko** [comment]
Related(?): #738

**Comment by sinni800** [comment]
@tsudoko It has the "screenshot box pull up" issue that I described, but not the "it doesn't record *at all* if the main screen is not the leftmost one" issue...

**Comment by GrayHatter** [comment]
If i push a fix for this, would you still be able to test it?

**Comment by sinni800** [comment]
@GrayHatter Yes, I will be able to.
