### ISSUE TITLE
Feature request: video compression options

### ISSUE THREAD

**Issue by atgote** [notsecure/uTox#913]
First of all - the video transmission in the uTox as it has appeared was great! The picture quality was 100% as it seemed. However, some time later a high compression was enabled and picture quality for the moment is not so good. I don't know if it can be set in the client app or it must be compiled in the toxcore library, however, in our (at least two users))) opinion it would be great to enable users to select compression ratio, allowing higher picture quality for users with higher bandwidth available... Maybe by default it must be set to some "Auto" or predefined value, but with availability to set another level...

**Comment by GrayHatter** [comment]
This is handled exclusively by toxcore. Maybe submit this there?

**Comment by atgote** [comment]
Submitted there.
https://github.com/irungentoo/toxcore/issues/1291
