### ISSUE TITLE
Wrong symbol appearance

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#915]
Symbol 'ё' with normal DPI (100%) is visually indistinguishable from 'é'.
![100%](http://puu.sh/gE3FY/ec1fd8bffa.png)

With bigger DPI (150%) it seems normally.
![150%](http://puu.sh/gE3Kp/6ef01a3a38.png)

In skype, for a example, with the same font size symbols are clear.
![100%skype](http://puu.sh/gE3Rv/d5ed41581b.png)

Win7 x64, Win 8.1 x64, v.0.2.o

**Comment by GrayHatter** [comment]
@redmanmale can you provide the first two pictures again but with a line of at least 10 of each? maybe throw in some spaces as well?

**Comment by redmanmale** [comment]
@GrayHatter 
100%
![100%](http://puu.sh/gE973/49d492f8f7.png)

150%
![100%](http://puu.sh/gE9bS/67354c14d0.png)

**Comment by GrayHatter** [comment]
@redmanmale thanks! what happens when you set it to tiny? (75%)

**Comment by redmanmale** [comment]
@GrayHatter Tiny is 50%. And it makes my eyes hurt.
![50%](http://puu.sh/gEa2b/60dd5c59c6.png)

**Comment by GrayHatter** [comment]
see also #941

**Comment by redmanmale** [comment]
On Win 8.1 it seems to be fixed, but on Win 7 this bug is still here, uTox versions are the same (0.9.7).
Any chance of fix?
