### ISSUE TITLE
uTox voice chat laging

### ISSUE THREAD

**Issue by normalST** [notsecure/uTox#916]
Hey there.

So the problem is, that the voice chat laging when processor is intensively loaded, usually its happens while playing the game, or when using a lot of programs at the same time, with browser, or even when code is being compiled.

Windows XP x86, and windows 8.1 x64, tested on both.
uTox version: 0.2.o
Don't have this problem with skype, or steam voice chat.
Processor: AMD Athlon64 X2 3800+

Using uTox while working, or playing games is much better then alternatives, it uses a very little RAM, and unlike programs like skype, or for example TS3(which are both use a lot of RAM), are much better, in my opinion, so I hope you will invistigate this problem. I'l answer any your questions.

Sorry for my English, it's not my native language.

**Comment by IneCmb** [comment]
Happened here when rendering something.

**Comment by irungentoo** [comment]
Try disabling audio filtering.

**Comment by normalST** [comment]
Disabling audio filtering is helping I guess, but now the volume level in voice chat is really low, is there solution for that? I can still hear the person that I calling to, but very quiet, there's no such problem with audio filtering enabled.

**Comment by normalST** [comment]
A little update on disabling audio filtering, long story short, it didn't help, it only make volume level lower. -.-

**Comment by irungentoo** [comment]
Audio filtering is the most CPU intensive audio related thing in uTox which is why I thought it was the issue in this case.

What kind of CPU do you have?

**Comment by normalST** [comment]
AMD Athlon64 x2 3800+ (2.0Mhz)
A bit old I know, but as I was saying there is no such problem with other voice chats.
And please do not tell me to use them instead of uTox. T_T

**Comment by irungentoo** [comment]
Is the sound you hear lagging or the sound the other person hears?

**Comment by normalST** [comment]
It's both actually, when my CPU on 100%, I don't hear other person, and he don't hear me, it's not continously lagging, it's like waves, for example:

"1" is all ok
"0" is everything is not ok, we don't hear each other, voice just lagged.
Visualy it'l be something like: 1100011111101010110001100111...

**Comment by irungentoo** [comment]
https://wiki.tox.im/Binaries/debug

Can you try these builds and tell me what it prints in the cmd window when it lags?

**Comment by normalST** [comment]
There's a lot of the same message, and the interesting part is, that my CPU is not loaded on 100% when debug version was online, it was loaded around 15-25%. memory and disk usage are low too, but lag was there anyway!

On the second test, there is no lag on 15-25% CPU, so I started browser with youtube video and twitch at the same time, 100% CPU load in no time, and lag too, log files are missing 90% of errors, and only have some info, so I made a screenshot of cmd(log) window, but links to *.log files included too.

https://www.dropbox.com/s/yrubmq3nkmewvgn/20150321205305.log?dl=0
https://www.dropbox.com/s/2bzp50ajaiqej04/20150321204541.log?dl=0

![1st](https://cloud.githubusercontent.com/assets/7449741/6766399/ccd66394-d00d-11e4-8b7e-39ea073fc480.png)
![2nd](https://cloud.githubusercontent.com/assets/7449741/6766398/cca3b160-d00d-11e4-8b0e-5cd5524b6bdc.png)

**Comment by GrayHatter** [comment]
please reopen this at https://github.com/GrayHatter/uTox if it still exists
