### ISSUE TITLE
groupchats share the same input box buffer

### ISSUE THREAD

**Issue by Doom032** [notsecure/uTox#919]
steps to reproduce
1. join / create a groupchat
2. join / create another groupchat
3. type something in the input box groupchat 1, but don't send
4. switch to groupchat 2

result
You'll see the text you typed visible in the input box groupchat 2

expected result
The input box is cleared, and the text you entered in groupchat 1 comes back when you switch to that groupchat. This is what happens when typing with friends.

**Comment by tsudoko** [comment]
Well I'd prefer a shared buffer for every chat, but I'm probably the only one.

**Comment by Doom032** [comment]
@tsudoko Why? For me the general use case for me is that I'm typing a message to a friend and suddenly get a message from someone else, answer him, and go back to my unfinished message.
