### ISSUE TITLE
After leaving a group chat friends list sometimes takes a long time to redraw

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#921]
Long time == more than 1s

**Comment by Doom032** [comment]
Not sure if this is the same, but I've noticed that if I fill up my screen with groupchats so the scrollbar starts appearing in the friends list, and then scroll down, and leave any groupchat, the whole friends list disappears except for the last groupchat, until I move my mouse. Then it becomes as it should be again. This effect does not disappear after removing enough groupchats to remove the scrollbar. It probably works with both friends and groupchats, but it's easiest to test with groupchats.

**Comment by GrayHatter** [comment]
blocked by #990
