### ISSUE TITLE
Copy (no names) by default

### ISSUE THREAD

**Issue by kovtunos** [notsecure/uTox#929]
Default behaviour of copying text in chat window is very annoying. Can you add an option to switch between "copy" and "copy (no names)"?

**Comment by GrayHatter** [comment]
@kovtunos eventually, as I've been annoyed by that feature as well

**Comment by fcore117** [comment]
for me this is really frustrating too, please swap.

**Comment by tsudoko** [comment]
What's wrong with the current behavior?

**Comment by GrayHatter** [comment]
if someone sends you a message that you want to copy, URI, password, email address, and you select the *simple* option, you get extra data you don't want. 

It boils down to:
```
Copy (extra words) == data
Copy                      == data (extra names)
```
when it should work like
```
Copy                       == data
Copy (extra words) == data (extra names)
```

**Comment by fcore117** [comment]
i do lot searches with text and pass text to others and so many times i curse when name has hovered with text.

**Comment by tsudoko** [comment]
I find myself using `Copy (no names)` less often, but fine. Thought about changing how ctrl-c works, i.e. about making it not prepend a name when there's only a part of the line selected.

**Comment by GrayHatter** [comment]
@tsudoko if you're selecting more than one message you probably want names

**Comment by fcore117** [comment]
from my view this is not some important feature and there is other features that has much higher priority currently. I myself use more (no names), but i do not know which selection is preferred by others in general.
