### ISSUE TITLE
no tray icon in Mate (classic Gnome fork) as well as in LXDE

### ISSUE THREAD

**Issue by shalnoff** [notsecure/uTox#930]
There are no icons in both: window and tray (whatever settings is set). And it doesn't minimise on close as well. It makes application really uncomfortable to use.

**Comment by Xylemon** [comment]
As far I know, Tray Icon support doesn't work on Linux. I hope it does soon, because it's been long overdue...

**Comment by GrayHatter** [comment]
dup #169
