### ISSUE TITLE
Feature Request: Screenshare in group chat.

### ISSUE THREAD

**Issue by Nsheppard01** [notsecure/uTox#933]
Right now it's possible to set the video input as desktop and audio input as loopback, and use that to stream a movie or game to a single person. But there is no way to do this to multiple people.

Would it be possible to a group livestream feature? (or even a group video chat feature) The former could be used to allow the creation of decentralized television broadcasts that do not require relying on a specific provider such as livestream or twitch.

**Comment by tsudoko** [comment]
Yes, it's planned, but toxcore doesn't support that yet.

**Comment by Nsheppard01** [comment]
Why not? Toxcore clearly supports streaming video to a single user.

In the mean time, what about being able to switch between camera and desktop video, or using both loopback and microphone for audio-imput?

**Comment by cguentherTUChemnitz** [comment]
The necessary toxcore features are discussed in the following ticket:
https://github.com/irungentoo/toxcore/issues/1245

**Comment by GrayHatter** [comment]
someone needs to open an issue for toxcore for AV calls in groupchat, then I they can re/open this issue, or a new one
