### ISSUE TITLE
uTox segfaults almost immediately

### ISSUE THREAD

**Issue by kozross** [notsecure/uTox#936]
I just tried launching uTox, and I got the following:

Read 84 bytes (/home/koz/.config/tox/utox_save)
have GTK
new tox object ipv6: 1 no_udp: 0 proxy: 0  0
Segmentation fault (core dumped)

This has never happened before

**Comment by irungentoo** [comment]
where did you download the build?

**Comment by kozross** [comment]
It's the latest utox-git from Parabola's PCR. This *should* be the same as the latest AUR build.

**Comment by GrayHatter** [comment]
@kozross can you run it with gdb and get a bt?

I can provide directions if you need them...

**Comment by kozross** [comment]
@GrayHatter Should I just do ``gdb utox`` and then ``run``?

**Comment by GrayHatter** [comment]
yeah, if it segfaults again then bt, and copy all of that into a https://gist.github.com

**Comment by kozross** [comment]
@GrayHatter [For your viewing pleasure][1].

[1]: https://gist.github.com/kozross/30db3d6bc28b97c55aaa

**Comment by GrayHatter** [comment]
what OS are you on?

**Comment by kozross** [comment]
@GrayHatter Parabola GNU/Linux-libre.

**Comment by GrayHatter** [comment]
@kozross can you clone the git repo and...

```sh
make
gdb ./utox
run
bt
```

The version you're using omits debugging symbols...

**Comment by kozross** [comment]
It seems that cloning *that* one works perfectly. I'll contact the package maintainers and ask them to rebuild the package using the current source.

**Comment by GrayHatter** [comment]
they (or you) may need to upgrade toxcore, but if that was the case, you wouldn't be able to compile.

Thanks for the report @kozross
