### ISSUE TITLE
Problems with Kerning

### ISSUE THREAD

**Issue by IneCmb** [notsecure/uTox#941]
Letters is not alongside.

Have not seen this problem in other IM applications.

**Comment by GrayHatter** [comment]
Are you sure those are the same fonts? (I only ask because it may be as simple as changing the font order)

**Comment by IneCmb** [comment]
Various fonts
Steam use `Arial` and Skype is `Segoe UI`

Also found that in 200% DPI all looks fine

**Comment by GrayHatter** [comment]
> Also found that in 200% DPI all looks fine

that is super helpful, I'll take a look soon, is it unusable or just difficult?

**Comment by IneCmb** [comment]
200% DPI is unusable for me.

**Comment by GrayHatter** [comment]
and it's still broken at 150%?

**Comment by IneCmb** [comment]
Less, but still can see.

**Comment by IneCmb** [comment]
Its really strange... On other machine problem is disappear...

![compared](https://cloud.githubusercontent.com/assets/10771557/6903771/419ad098-d725-11e4-815a-b4ba8ca8f88a.png)

I will try to fix this issue by myself on my local PC.

**Comment by GrayHatter** [comment]
Windows?

**Comment by IneCmb** [comment]
Windows 8.1 64-bit on both machines.

**Comment by IneCmb** [comment]
Tried many different things such as fully reinstalling uTox, fonts, drivers, loading safemode... Nothing helped.
Remember having this problem with my friend from a 0.1 uTox, but few days ago he update hardware and moved from XP to 8.1 and problem for him was resolved.
Found also that qTox shows text correctly.

**Comment by GrayHatter** [comment]
Are both screen resolutions native?

Are either using high dpi scaling?

What are the actual hardware? (Maker and model number?)

**Comment by IneCmb** [comment]
Yes
Using default (Smaller - 100%)

If I get you correct
Motherboard: `ASUS P5Q SE2`
CPU: `Intel Core 2 Duo E8600 @ 3.33GHz (2 CPUs)`
GPU: `ASUS EN 9600 GT 512MB`
SPD: `Kingston 2 GB DDR2-800` (x2)

**Comment by GrayHatter** [comment]
can you try disabling high dpi scaling for utox under program compatibility

**Comment by IneCmb** [comment]
Not helped

**Comment by GrayHatter** [comment]
What is the screen resolution for both systems?

**Comment by IneCmb** [comment]
1680 × 1050 and 1440 × 900

**Comment by IneCmb** [comment]
Resolved!

Removing these 4 files that lived in Font folder fix the problem. 
> GlobalMonospace.CompositeFont
GlobalSansSerif.CompositeFont
GlobalSerif.CompositeFont
GlobalUserInterface.CompositeFont
Dunno where they came from.

**Comment by IneCmb** [comment]
Resolved!

Removing these 4 files that lived in Font folder fix the problem. 
>GlobalMonospace.CompositeFont
GlobalSansSerif.CompositeFont
GlobalSerif.CompositeFont
GlobalUserInterface.CompositeFont

Dunno where they came from.
