### ISSUE TITLE
uTox prefixes messages with the message ID and expects incoming messages to have that prefix as well

### ISSUE THREAD

**Issue by nikwen** [notsecure/uTox#944]
When printing out the hex values of the messages sent by uTox and received by another client, they look like the following: 0000000174657374. The next one is 00000002746573742032. The numbers before the actual messages ("test" and "test 2" in the examples) keep increasing by one after every received message.

I'm using the new API. When messages are sent by toxic, there are no such numbers before the actual message text.

uTox also seems to have problems with receiving messages that aren't prefixed by a message ID. It does not display the first 4 characters in that case.

**Comment by GrayHatter** [comment]
@nikwen I'm assuming you're running the newest uTox, and your friend is running qTox? If so, that's a qTox bug, they're still using the old version of toxcore. You can submit an issue to them, but they already know and working on it

**Comment by nikwen** [comment]
@GrayHatter Thank you very much for your reply.

I've been using uTox to test my self-written Tox client which I updated to use the new API today. However, I'm seeing the issue described above. When I communicate with my own client using Toxic (which also uses the new API), everything works fine.
The same behaviour can be seen when exchanging messages between uTox and Toxic.

Therefore, I believe the issue made it into the uTox code during the transition to the new API.

**Comment by GrayHatter** [comment]
where'd you get your utox?

**Comment by nikwen** [comment]
I was using the one from the debian repository on multiple debian-based Linux distributions (Linux Mint and Ubuntu 14.10). I used the one which was available yesterday. (The same applies to the Toxic version I used for testing.

Try the following: Download the latest version of Toxic and send a message to uTox. The first 4 characters should be missing.

**Comment by irungentoo** [comment]
The uTox builds in the Tox linux repo and from the windows updater are not on the new api yet because we are waiting for qTox.

**Comment by nikwen** [comment]
@irungentoo Thank you very much for your comment. It's my fault then, so feel free to close this issue.

Am I right that the Toxic version from the repo already uses the new API? Thanks again. :smile:
