### ISSUE TITLE
Problem with symbol appearance in notification

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#945]
In tray notification last symbol of new message text appears wrong, looks like this:
![100%](http://puu.sh/gWNGU/5b48874f0a.png).

The message itself is looks fine.
v. 0.2.o, Win 8.1 x64.

That's my thoughts about it:
- Text in message is longer than notification.
- Text in message is in Unicode (UTF-8 maybe) encoding, so one symbol consists of several bytes.
- Text in message cut off, so in notification shows only part of it.
- So, that strange symbols appear when last symbol in notification is only first byte of actual Unicode symbol in text message.

Sorry for some confusion in my description.

**Comment by GrayHatter** [comment]
#dup of 740

**Comment by redmanmale** [comment]
Sorry, next time will lurk a little more in open issues.

**Comment by GrayHatter** [comment]
@redmanmale no worries, you actually got me to fix it. Thanks for the bugreport never be afraid to submit a bug, worst case I close it as a dup and I know which are effecting the most people.
