### ISSUE TITLE
uTox behaves very strangely

### ISSUE THREAD

**Issue by kozross** [notsecure/uTox#947]
Whenever I try to contact my friends, all their messages keep repeating, and apparently, uTox tries to send them random (very large!) files. I have tried a clean install of the client, every supporting library, and even changing IDs - none of this works! I have no clue what is going on or why.

**Comment by irungentoo** [comment]
The downloads at the bottom of the binaries page are on new api core, those big file transfers are just the new way avatars are sent. The reason the files look big is because of protocol changes.

**Comment by GrayHatter** [comment]
>Whenever I try to contact my friends, all their messages keep repeating, and apparently

That because qTox thinks it's a good idea to try to send messages infinitely, instead of failing after a few attempts...

**Comment by GrayHatter** [comment]
Closed because this is a qTox problem, you should tell them to update to a client that uses the new core...
