### ISSUE TITLE
Missing letters in messages (and cannot receive files)

### ISSUE THREAD

**Issue by kozross** [notsecure/uTox#953]
Whenever I send a message to another uTox (or qTox), the first few letters of my message are lost. Additionally, when the person on the other end wants to send me a file, I can't even *see*, let alone receive, it.

Whenever I get a message from them, it has some junk characters at the front (I figured this might be related).

**Comment by tsudoko** [comment]
Downgrade your client to bdd1a009518e325a73a527da152793102b765ef6 for now. qTox isn't yet compatible with the new API and most client updates are held back.

**Comment by GrayHatter** [comment]
I'd suggest you not just downgrade.

But if you want to, make sure you downgrade your toxcore version as well.

Closed as wontfix, qTox needs to upgrade
