### ISSUE TITLE
Feature Request: Notification from group chats.

### ISSUE THREAD

**Issue by Nsheppard01** [notsecure/uTox#954]
This issue was previously labeled a duplicate, but the other issue was only tangentially related so I'm asking again.

Right now there is no visual indication that people are talking in a group chat. This causes people to miss entire conversations. Adding some sort of audible indicator is not a desirable replacement, because unlike audio, visual indicators can inform the user of events that occurred while the user was away, and don't become annoying.

**Comment by GrayHatter** [comment]
#388
