### ISSUE TITLE
Make configuration file human-readable

### ISSUE THREAD

**Issue by muchweb** [notsecure/uTox#958]
I know that one of aims of µTox project is to keep as few dependencies as possible, but I think that this would bring considerable benefit.

**Proposal:** to store settings and themes in `INI`, `CFG`, `JSON` or similar human-readable configuration file.

This will make it easier for users to understand and for developers to add/remove supported options in the future.

Parsing libraries tend to be very small and portable.

**Comment by GrayHatter** [comment]
see #908

**Comment by ElLamparto** [comment]
I would rise the priority.
Currently the language option is not saved at all (WIn XP, Win 7 and Debian), Always the OS language is taken.
The DPI setting sometimes is suddenly set to 250% (Win XP). <-- This is a high priority.

I suppose that the write/read functions are extremely messy and should be rewritten. This is a good opportunity to convert utox_save into an ASCII format. It would also allow to use some advanced config options without complicating the GUI.

I think, that the config of toxic is a good example.
