### ISSUE TITLE
installation too much work on Windows

### ISSUE THREAD

**Issue by Doom032** [notsecure/uTox#959]
From getting some people on Windows to use µTox, I found that the biggest installation issue they run into is that they have to choose an installation path manually. It's also unclear when you select a folder whether it'll create a subfolder or it'll just unpack in the folder you selected.

Probably would be best if the default path was set to "C:\Tox" or something, and you can customize it if you want. Most people won't.

**Comment by tsudoko** [comment]
I think there was a discussion somewhere about moving the default installation dir to `%LOCALAPPDATA%\uTox` or something similar and installing/updating uTox without any user interaction at all. Might be good for people who don't like choice.

**Comment by GrayHatter** [comment]
@Doom032 it's on my radar and coming soon

**Comment by Doom032** [comment]
@tsudoko that'd be nice, truly no configuration required.
@GrayHatter Great!

**Comment by muchweb** [comment]
+1 on this

**Comment by fcore117** [comment]
i personally do not use installers ever as i use portable, but friends complain about uTox launcher flashes some window before starting.

**Comment by Doom032** [comment]
@fcore117 ah yeah, I think it shows a console window when you update µTox with the updater. It's a bit weird if you're not used to it.

**Comment by plumpudding** [comment]
you could work arround that updater window (even if it's a batch script) by using http://www.nirsoft.net/utils/nircmd.html and running the command ' nircmd.exe win hide ititle "window title" '

**Comment by tsudoko** [comment]
Isn't this fixed now?

**Comment by GrayHatter** [comment]
@tsudoko, almost. It'll be fixed when self updating uTox becomes default,
and not a custom build...

But really it'll be fixed once uTox is able to update itself without a
separate exe.

**Comment by dogstarxxx** [comment]
On windows it's not useble from the start. Okey. If it is "intalleted" then where it's store config and additational files? It's not clear for all users. Where is "private" key & buckups to buckup?

And why so simple client can not SIMPLE be "extracted" from the installer and be "PORTABLE" by default? I'm about simple extract the files and use only extracted folder/subfolder for all activity on the system.

I think it must be "portable" by default. And installer must only extract files AND make hyperlinks in the system if it's choosen!

Now it's do not clean work on the system.

**Comment by plumpudding** [comment]
If you want portable utox create a seperate issue.

**Comment by GrayHatter** [comment]
closed, installing and keeping utox up to date is much easier with the new improvements to the updater
