### ISSUE TITLE
Brew installation of uTox gives error message when trying to open from terminal

### ISSUE THREAD

**Issue by olgazd** [notsecure/uTox#962]
I installed uTox from brew, and when I try to run it in my terminal, I get the following result:

```
Cannot open display
```

What is the cause of this and how can I get it work?

**Comment by GrayHatter** [comment]
which brew?

**Comment by tsudoko** [comment]
Do you have XQuartz installed?

**Comment by olgazd** [comment]
Homebrew, XQuartz installed.

**Comment by olgazd** [comment]
Steps:
1. brew tap Tox/tox
2. brew install --HEAD utox
3. brew install Caskroom/cask/xquartz
4. brew install --HEAD utox
5. utox
Cannot open display

**Comment by emanueLczirai** [comment]
can you show the output of this
$ echo $DISPLAY
:0.0

**Comment by olgazd** [comment]
Olgas-MBP:Tutorials olga$ brew tap Tox/tox
==> Tapping Tox/tox
Cloning into '/usr/local/Library/Taps/tox/homebrew-tox'...
remote: Counting objects: 225, done.
remote: Total 225 (delta 0), reused 0 (delta 0), pack-reused 225
Receiving objects: 100% (225/225), 39.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.
Tapped 6 formulae (29 files, 160K)
Olgas-MBP:Tutorials olga$ brew install --HEAD libtoxcore
==> Installing libtoxcore from tox/homebrew-tox
==> Installing dependencies for libtoxcore: libsodium, autoconf, automake
==> Installing libtoxcore dependency: libsodium
==> Downloading https://homebrew.bintray.com/bottles/libsodium-1.0.2.yosemite.bo
######################################################################## 100.0%
==> Pouring libsodium-1.0.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libsodium/1.0.2: 62 files, 1.2M
==> Installing libtoxcore dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.yosemite.bott
######################################################################## 100.0%
==> Pouring autoconf-2.69.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.1M
==> Installing libtoxcore dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.yosemite.bott
######################################################################## 100.0%
==> Pouring automake-1.15.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
==> Installing libtoxcore dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.yosemite.bott
######################################################################## 100.0%
==> Pouring libtool-2.4.6.yosemite.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing libtoxcore dependency: check
==> Downloading https://downloads.sourceforge.net/project/check/check/0.9.14/che
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/check/0.9.14
==> make install
🍺  /usr/local/Cellar/check/0.9.14: 42 files, 940K, built in 27 seconds
==> Installing libtoxcore dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.28.yosemite.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.28.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 612K
==> Installing libtoxcore dependency: opus
==> Downloading https://homebrew.bintray.com/bottles/opus-1.1.yosemite.bottle.ta
######################################################################## 100.0%
==> Pouring opus-1.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/opus/1.1: 14 files, 864K
==> Installing libtoxcore dependency: libvpx
==> Downloading https://homebrew.bintray.com/bottles/libvpx-1.4.0.yosemite.bottl
######################################################################## 100.0%
==> Pouring libvpx-1.4.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libvpx/1.4.0: 16 files, 2.3M
==> Installing libtoxcore
==> Cloning git://github.com/irungentoo/toxcore
Cloning into '/Library/Caches/Homebrew/libtoxcore--git'...
remote: Counting objects: 180, done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 180 (delta 10), reused 42 (delta 4), pack-reused 0
Receiving objects: 100% (180/180), 415.91 KiB | 204.00 KiB/s, done.
Resolving deltas: 100% (10/10), done.
Checking connectivity... done.
==> Checking out branch master
==> autoreconf -if
==> ./configure --prefix=/usr/local/Cellar/libtoxcore/HEAD --disable-testing
==> make
==> make install
==> Caveats
libtoxcore has no UI. If you want to make use of it, try Toxic for a CLI:
  brew install --HEAD toxic
or uTox for a GUI (X11):
  brew install --HEAD utox
==> Summary
🍺  /usr/local/Cellar/libtoxcore/HEAD: 22 files, 1.2M, built in 30 seconds
Olgas-MBP:Tutorials olga$ brew install --HEAD utox
==> Installing utox from tox/homebrew-tox
utox: XQuartz is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/xquartz

You can download from:
  https://xquartz.macosforge.org
Error: An unsatisfied requirement failed this build.
Olgas-MBP:Tutorials olga$ brew install Caskroom/cask/xquartz
==> Tapping Caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 133157, done.
remote: Total 133157 (delta 0), reused 0 (delta 0), pack-reused 133157
Receiving objects: 100% (133157/133157), 39.20 MiB | 584.00 KiB/s, done.
Resolving deltas: 100% (88186/88186), done.
Checking connectivity... done.
Tapped 1 formula (2798 files, 59M)
==> Installing brew-cask from caskroom/homebrew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Cloning into '/Library/Caches/Homebrew/brew-cask--git'...
remote: Counting objects: 2686, done.
remote: Compressing objects: 100% (2531/2531), done.
remote: Total 2686 (delta 198), reused 659 (delta 139), pack-reused 0
Receiving objects: 100% (2686/2686), 5.62 MiB | 259.00 KiB/s, done.
Resolving deltas: 100% (198/198), done.
Checking connectivity... done.
Note: checking out 'e65c40bb2bb02d7aa26f3d0ed6217862f2436055'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Checking out tag v0.53.3
🍺  /usr/local/Cellar/brew-cask/0.53.3: 2421 files, 9.5M, built in 29 seconds
==> brew cask install Caskroom/cask/xquartz
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
==> Downloading https://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg
######################################################################## 100.0%
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
==> installer: Package name is XQuartz 2.7.7
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  xquartz staged at '/opt/homebrew-cask/Caskroom/xquartz/2.7.7' (64M)
Olgas-MBP:Tutorials olga$ brew install --HEAD utox
==> Installing utox from tox/homebrew-tox
==> Installing utox dependency: freealut
==> Downloading http://connect.creativelabs.com/openal/Downloads/ALUT/freealut-1

curl: (6) Could not resolve host: connect.creativelabs.com
Trying a mirror...
==> Downloading http://ftp.de.debian.org/debian/pool/main/f/freealut/freealut_1.
######################################################################## 100.0%
==> Patching
patching file configure.ac
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/freealut/1.1.0 --mandir=/usr/local/Ce
==> make install
🍺  /usr/local/Cellar/freealut/1.1.0: 11 files, 180K, built in 22 seconds
==> Installing utox
==> Cloning git://github.com/notsecure/uTox
Cloning into '/Library/Caches/Homebrew/utox--git'...
remote: Counting objects: 144, done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 144 (delta 10), reused 58 (delta 7), pack-reused 0
Receiving objects: 100% (144/144), 776.87 KiB | 189.00 KiB/s, done.
Resolving deltas: 100% (10/10), done.
Checking connectivity... done.
==> Checking out branch master
==> clang -o /usr/local/Cellar/utox/HEAD/bin/utox -ltoxcore -ltoxav -ltoxdns -lr
🍺  /usr/local/Cellar/utox/HEAD: 4 files, 780K, built in 7 seconds
Olgas-MBP:Tutorials olga$ utox
Cannot open display

**Comment by olgazd** [comment]
It is blank

**Comment by emanueLczirai** [comment]
Is it blank even when you start a new terminal? (inside X I presume)

**Comment by olgazd** [comment]
I have restarted my pc, now echo $DISPLAY is not blank and tox works.
Thanks for help.

**Comment by olgazd** [comment]
Solution was found here:
https://discussions.apple.com/thread/4157422?start=15&tstart=0
