### ISSUE TITLE
Bad font rendering on Linux.

### ISSUE THREAD

**Issue by neodine** [notsecure/uTox#964]
The subpixel rendering looks quite bad compared to other applications. I've had this issue in the past and it was remedied in an update but now it appears to have returned.

Example:
![subpixelrendering](https://cloud.githubusercontent.com/assets/8393359/7104522/433495a8-e0b5-11e4-891e-dbec23c3364f.png)

**Comment by irungentoo** [comment]
Fixed in: https://github.com/notsecure/uTox/commit/1e1758f03d740c6463371910717a40e125de4a63
