### ISSUE TITLE
Font rendering with -O2 and infinality

### ISSUE THREAD

**Issue by haavardp** [notsecure/uTox#975]
![uTox screenshot](http://i.imgur.com/W2yIhn6.png)

Arch Linux with [`infinality-bundle`](https://wiki.archlinux.org/index.php/Infinality) installed, uTox (a147476e0e) compiled with `CFLAGS=-O2` or `CFLAGS=-O3`. Does not happen without infinality. Does not happen with `-O1` or `-O0`.

**Comment by xzfc** [comment]
Can confirm. My configuration: gentoo, no infinality, regardless optimisation level (tested `-O0` `-O1` `-O2` `-O3`).

Ironically,
> 1e1758f03d740c6463371910717a40e125de4a63 is the first bad commit
> Fixed font rendering on linux.

**Comment by irungentoo** [comment]
can you post your fontconfig configs?

**Comment by xzfc** [comment]
[/etc/fonts](http://dump.bitcheese.net/files/ewugeta/etc-fonts.tar.gz), [~/.fonts.conf](http://dump.bitcheese.net/files/osozese/fonts.conf).

Renders ok if remove `<edit name="hintstyle" mode="assign"><const>hintslight</const></edit>` from `~/.fonts.conf`.

**Comment by irungentoo** [comment]
Fixed in: https://github.com/notsecure/uTox/commit/96528bc2ba420c506ad134b64c3ce18234c66fc2
