### ISSUE TITLE
Cannot delete canceled/received files

### ISSUE THREAD

**Issue by fcore117** [notsecure/uTox#976]
I cannot delete canceled, i have to quit utox to get access to files. User who i sent files cannot delete received files.

**Comment by GrayHatter** [comment]
@fcore117 I'm going to need a lot more information then this?

How are you trying to delete the file? What OS are you on/is your friend on?

**Comment by fcore117** [comment]
my side win8 and other side win7, try to start sending file then press cancel and try to delete or move this file.

**Comment by towlie** [comment]
@GrayHatter It seems that you don't release the file on cancel. Maybe you forgot something

**Comment by towlie** [comment]
Oh and shouldn't it delete uncompleted / canceled files? That would also solve the issue.

**Comment by fcore117** [comment]
I hope when patch arrives then uTox releases all files from lock if not transferring or waiting to transfer. Currently only way is to close and delete/move/rename.

**Comment by GrayHatter** [comment]
this is fixed in my newest branch. Still pending testing, you can check it out from #993 and report any bugs there to speed along it's merge into master

**Comment by GrayHatter** [comment]
fixed in master
