### ISSUE TITLE
Font doesn't render properly

### ISSUE THREAD

**Issue by plumpudding** [notsecure/uTox#980]
Ironically since https://github.com/notsecure/uTox/commit/96528bc2ba420c506ad134b64c3ce18234c66fc2

I use Arch Linux with the latest packages of Gnome. 

It looks like this:
https://i.imgur.com/MwrwnTN.png

**Comment by plumpudding** [comment]
After looking at the changes I removed the " / 3" in line 244 and voila - everything looks nice again!

**Comment by irungentoo** [comment]
https://github.com/notsecure/uTox/commit/f0111535f3ae1d820584d401d7f1debc54f9787d

Did this fix it?

**Comment by plumpudding** [comment]
Yes it did @irungentoo
