### ISSUE TITLE
user avatar disappears if you send a 1x1 pixel screenshot

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#984]
Happened to me on Win7x64. Don't know about linux.
The avatar reappears when you send a bigger screenshot. (Bigger than 1x1 pixel).

![avatar1](https://cloud.githubusercontent.com/assets/6986141/7281022/38a4a61c-e927-11e4-9c10-6041cfc92837.jpg)
![avatar2](https://cloud.githubusercontent.com/assets/6986141/7281024/3f468c4c-e927-11e4-8405-508962b48c70.jpg)

**Comment by GrayHatter** [comment]
well THAT'S interesting...

**Comment by GrayHatter** [comment]
@towlie I can't duplicate this on Win8x64, can you restart and still make it happen?

**Comment by towlie** [comment]
I was able to do this again. You just have to wait a bit (maybe 20 s). So it doesn't disappear instantly.

**Comment by towlie** [comment]
The avatar only disappears per contact. So if I click another contact then it reappears until I go back to the faulty one.

**Comment by towlie** [comment]
Arguments of "draw_image" function when this bug happens. https://gist.github.com/towlie/cf486376d8b71c294fe1. 
I also saw that the screenshot function doesn't not show the sent image until I do some mouse movements (leaving the utox window). So when the redraw happens the avatar will disappear. 
@irungentoo said that there is a missing redraw.
Maybe that's why you couldn't repdroduce it?

**Comment by irungentoo** [comment]
https://github.com/notsecure/uTox/commit/ea6d79655dc3d1c2c61a7d7cdbee4c3d98d9af11
