### ISSUE TITLE
uTox doesn't redraw if screenshot filetransfer is finished

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#985]
Because of that uTox will not show the sent image until you leave the chat window with the mouse cursor.

**Comment by towlie** [comment]
Happens on Linux also.

**Comment by towlie** [comment]
The main issue is that people don't notice that a inline image was received until they hover over the uTox window.

**Comment by stal888** [comment]
I might submit a patch for this tomorrow

**Comment by GrayHatter** [comment]
@stal888 it'd be best to add a call to redraw in the update_user function. That is after all it's job, and it's called every time there's an update that the user might want to know about.

**Comment by towlie** [comment]
https://github.com/notsecure/uTox/commit/16b008c56267d8926508c8b21cfa9ecce5c0f517
