### ISSUE TITLE
Text overflow issues

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#992]
Sorry, I don't know how to describe it better.
http://a.pomf.se/dnjapp.webm

**Comment by azlux** [comment]
The same with me, the scrolling makes errors and create a shift between the text and what we see. So we click on an empty area.

**Comment by tsudoko** [comment]
Related: http://a.pomf.se/odjgnk.webm

**Comment by GrayHatter** [comment]
closed until better description is provided
