### ISSUE TITLE
Terrible antialiasing on Linux

### ISSUE THREAD

**Issue by gjedeer** [notsecure/uTox#994]
After upgrading to 0.2.p, uTox on Linux started displaying antialiased text. Font is very hard to read now. Is it possible to disable antialiasing?

![cccc5](https://cloud.githubusercontent.com/assets/315648/7347295/78e8aa70-ece7-11e4-82f8-1dc2d1db73fc.png)

**Comment by gjedeer** [comment]
Okay, the screen doesn't show how unreadable it is because Github magnified the image.

**Comment by irungentoo** [comment]
There's a DPI option to make the UI and text bigger in the options.

**Comment by GrayHatter** [comment]
@gjedeer did changing the dpi help?

**Comment by gjedeer** [comment]
It now looks like lego duplo but at least it's readable. Still looks noticeable worse than rest of the system. 

I wonder if compiling with my system freetype instead of using binary from the repo would look better...

**Comment by GrayHatter** [comment]
can you provide an image with how µTox looks compared to how something else on your system looks (they way you expect µTox to look)

**Comment by gjedeer** [comment]
uTox @ 100% vs Psi+
![image](https://cloud.githubusercontent.com/assets/315648/7421807/18d64270-ef88-11e4-8cf5-5d80e7f5003b.png)

**Comment by gjedeer** [comment]
Also, to clarify: before 0.2.p uTox didn't use antialiasing on my system at all, and it looked great.

**Comment by GrayHatter** [comment]
it's a different font, but I'm not seeing the problem?

**Comment by gjedeer** [comment]
Maybe you have better sight, for me the picture on the left is hardly readable.

Or, to be more scientific: I

**Comment by irungentoo** [comment]
Fixed in: https://github.com/notsecure/uTox/commit/f31f91b422b3735617f46fbb58bdba3697f49874

**Comment by gjedeer** [comment]
Confirmed that it's fixed - the text is readable in 0.2.q
