### ISSUE TITLE
Avatars aren't being sent

### ISSUE THREAD

**Issue by tsudoko** [notsecure/uTox#996]
New API uTox doesn't show other friends' avatars, also my avatar isn't shown on their friends list.
Cached avatars from qTox friends are shown, though.
The `~/.config/tox/avatars` directory doesn't contain any files when cleared or removed before launching uTox.

Sample output when a friend came online after restarting their client:
```
Friend (33):     Online (UDP)
FileTransfer:   Starting avatar to friend 33.
FileTransfer:   New Avatar from friend (33)
FileTransfer:   Avatar Unset from friend(33).
FileTransfer:   We just killed file (33 & 65536)
File already killed.
FileTransfer:   Friend (33) rejected avatar
FileTransfer:   Cleaning up file transfers!
```

**Comment by theCoolkal** [comment]
I have the same problem.

The output shows this:

```
FileTransfer:New Avatar from friend (24)
FileTransfer:Avatar Unset from friend(24).
FileTransfer:We just killed file (24 & 65536)
FileTransfer:Cleaning up file transfers!
```

**Comment by irungentoo** [comment]
qTox bug?

**Comment by theCoolkal** [comment]
@irungentoo We're both using µTox.

**Comment by pcbmaster** [comment]
Have the same issue here. Using uTox.

**Comment by Doom032** [comment]
Avatars work here if you set it manually after start up, but if you restart the avatar seems to not be sent to people anymore, until you set it again.

**Comment by azlux** [comment]
Same here. but avatar changed before the previous update are still here. only new avatars are not saved and not send to others after restart

**Comment by irungentoo** [comment]
Fixed in: https://github.com/notsecure/uTox/commit/a1d8629028da03504895c24a63583021736a7e2c
