### ISSUE TITLE
uTox for 32 bit Linux with a lot of visual issues

### ISSUE THREAD

**Issue by darkman088** [notsecure/uTox#997]
Hello,

today I have installed the latest version of the 32-bit Linux version of uTox (the .rpm version). Unfortunately, I need to complain very loud about it, as it has many many glitches:
1) When I receive text from a contact, it starts with three small rectanlges and a corner-character. I tried to copy-paste them here, but it is not possible... :-/
2) Then, when I am working on something else, there is a black baloon when I receive a chat message. Here I can just see the contact's name. The text of the message is not visible.
3) My contact complained that he is not receiving the first few letters or words of a message, for example this would read for him like this:
"plained that he is not receiving the first few letters or words of a message"

What is this ? Please kindly release a new working version! Thanks !!!

**Comment by theCoolkal** [comment]
Your contacts are probably using older clients from before the recent protocol update.

**Comment by irungentoo** [comment]
tell your friend to update his client.

**Comment by darkman088** [comment]
OK, then we will try that, thanks!!

**Comment by GrayHatter** [comment]
closed as new_api issue, ask your friend to update, and if you still have issues tag me or reopen this.

**Comment by darkman088** [comment]
Yes, we BOTH updated and now it works fine again! Many thanks for the excellent support on this! :-)
