### ISSUE TITLE
Regression: No more progress bar on inline images

### ISSUE THREAD

**Issue by Doom032** [notsecure/uTox#998]
There used to be a progress bar when sending inline images like when you send an attachment, but that seems to have been removed. Not having it is really not handy, because you need that bar to see how the transfer is going and whether it was sent correctly. Inline images feel less polished now.

**Comment by raisingw** [comment]
+1 on this. It also means inline images can't be saved, and coupled with the redraw bug, there's no notification when someone sends me an image because the progress bar doesn't appear.

**Comment by GrayHatter** [comment]
> It also means inline images can't be saved, 

This should not be true, but I'll look into it and get it fixed in the next file transfer update.
