### ISSUE TITLE
µTox on Windows XP 32 bit - µTox window totally messed up

### ISSUE THREAD

**Issue by ElLamparto** [notsecure/uTox#999]
Version 0.2.p.
Windows XP 32 bit: in the µTox window there is only 1/4 of the usual contents - 4x enlarged.
This version works correctly on Windows 7 32 bit and on Debian.

**Comment by ElLamparto** [comment]
![utoxcapture](https://cloud.githubusercontent.com/assets/9163437/7370005/250d9782-edb7-11e4-8cd2-8e21e0ea615f.PNG)

**Comment by irungentoo** [comment]
go in the options, look for the dpi settings and set it to 100%,

**Comment by ElLamparto** [comment]
It worked. Why was it suddenly set to 250%? µTox mystery...
